### ISSUE TITLE
No response after setting render

### ISSUE THREAD

**Issue by liaojiaxin97** [aai-institute/tianshou#1001]
May I ask why I run several algorithm files in discrete directories under the test directory, which can run normally and Final reward appears, but why no animation appears when I set render=0.03?Appreciate very much！！

**Comment by liaojiaxin97** [comment]
![image](https://github.com/thu-ml/tianshou/assets/58950996/28819278-0115-4195-b565-c61daed0e97d)

**Comment by Trinkle23897** [comment]
what's your gym/gymnasium version? also could you try cartpole-v1?

**Comment by liaojiaxin97** [comment]
> what's your gym/gymnasium version? also could you try cartpole-v1?

Thank you for your reply. My gym version is 0.26.2. v1 was also tried. but still no dynamic graph appeared.

**Comment by MischaPanch** [comment]
Could you pls try gymnasium and use the master branch of tianshou? We dopped support for gym on master a while ago

**Comment by MischaPanch** [comment]
Closing as stale

**Comment by zdx3578** [comment]
<img width="1072" alt="image" src="https://github.com/thu-ml/tianshou/assets/382863/a51980a8-7ae9-4ad3-bcd8-55ff5195468b">
when set --render ,i seem like  config not used 
and no any render show ;


when debug

<img width="512" alt="image" src="https://github.com/thu-ml/tianshou/assets/382863/0803784a-3367-4ef2-a4c7-257529c1de8e">

<img width="690" alt="image" src="https://github.com/thu-ml/tianshou/assets/382863/1cf75cf3-63de-43f6-a698-4b8bdd388d8f">


<img width="883" alt="image" src="https://github.com/thu-ml/tianshou/assets/382863/2460238b-fbe5-421f-b300-0da772700c2e">

it is in render func
,but remain no window show render image video.

my env is ubuntin in cpu ; and macos m1 ;
