### ISSUE TITLE
New html docs issue

### ISSUE THREAD

**Issue by Trinkle23897** [aai-institute/tianshou#1005]
1. contents layout is weird:
<img width="1262" alt="Screenshot 2023-12-06 at 9 41 15 AM" src="https://github.com/thu-ml/tianshou/assets/8189182/46847ef9-945f-4a03-a0bd-79ea3019f071">
2. could we remove this notification? `stable` is a very old tag:
<img width="1056" alt="Screenshot 2023-12-06 at 9 42 14 AM" src="https://github.com/thu-ml/tianshou/assets/8189182/90269999-8037-42e8-be10-ccf979ffe745">
3. there should be an interactive plot that shows the curve, but is missing on newest docs, same as atari:
<img width="1249" alt="Screenshot 2023-12-06 at 1 35 08 PM" src="https://github.com/thu-ml/tianshou/assets/8189182/672a9c8b-f440-49d6-a2ad-19e23de9ed90">
<img width="1183" alt="Screenshot 2023-12-06 at 1 36 03 PM" src="https://github.com/thu-ml/tianshou/assets/8189182/d4a0e837-35f9-48c3-86e4-40b4a49f2164">
4. contributor page is old
<img width="1218" alt="Screenshot 2023-12-06 at 1 37 28 PM" src="https://github.com/thu-ml/tianshou/assets/8189182/654c1934-973b-4f73-937b-d634be5df06f">

**Comment by nuance1979** [comment]
+1. "This may be an old version of this documentation" banner is very annoying.

**Comment by carlocagnetta** [comment]
1) for point 1 I can look into it!
2) @MischaPanch if you have access to the official RTD maybe you can fix  this one
3) Will have a look
4) How should this be updated?

**Comment by MischaPanch** [comment]
The thing is, we have a bunch of breaking changes on master compared to the last release, which is the stable version, I guess. So the warning is kinda on point. Most people will just install tianshou from pip, which corresponds to the old version of docs

One more reason to release 0.6.0 asap :)

**Comment by MischaPanch** [comment]
The contributor page was the one from master. I would like to mention my company and the latest contributors there, would do a separate PR for that

**Comment by carlocagnetta** [comment]
1. This is a bug of jupyter-book when adding a bibliography. The bug appears also in the jupyter-book documentation under [Citations and bibliographies](https://jupyterbook.org/en/stable/content/citations.html)

**Comment by MischaPanch** [comment]
Then let's do what they propose and downgrade docutils

**Comment by carlocagnetta** [comment]
https://github.com/executablebooks/jupyter-book/blob/a8b7cf6517188ca837d948ca1f86858e2bb86097/docs/content/citations.md?plain=1#L4-L14

https://sourceforge.net/p/docutils/patches/195/

**Comment by carlocagnetta** [comment]
1st issue resolved by updating to last release of jupyter-book==1.0.0 which came out few weeks ago

**Comment by MischaPanch** [comment]
Also benchmark widget display is now fixed, I also slightly improved the js code

**Comment by carlocagnetta** [comment]
![image](https://github.com/thu-ml/tianshou/assets/50958143/da557e2a-05ad-4357-b232-8b07da899c19)
Unfortunately it does not seem resolved..

**Comment by MischaPanch** [comment]
Yeah, I've seen it, it's more jquery stuff, and maybe symlink things. I'll fix it today or tomorrow
