### ISSUE TITLE
puzzle about parameter set-eps

### ISSUE THREAD

**Issue by GongYanfu** [aai-institute/tianshou#1013]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
    + [ ] design request (i.e. "X should be changed to Y.")
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
for getting hdf5 file of expert data，you show the cmd as follow:
![image](https://github.com/thu-ml/tianshou/assets/46698455/174b8a7d-1eb4-4b2d-a5b3-0d2a91c0a8ca)
For all atari games, is it correct to always set the value of the parameter set-eps to 0.2 when getting the dataset?
can I change it to 0.1 or other value?

**Comment by nuance1979** [comment]
It is up to you to decide what eps to use for your purpose. There is no "correct" value per se.
