### ISSUE TITLE
example of a2c on atari games

### ISSUE THREAD

**Issue by GongYanfu** [aai-institute/tianshou#1023]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
    + [ ] design request (i.e. "X should be changed to Y.")
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
![image](https://github.com/thu-ml/tianshou/assets/46698455/73bb448a-6ffa-4f1b-a01c-833df9a5da28)
can you add an example of a2c for training atari games? 
thanks a lot!

**Comment by Trinkle23897** [comment]
You can follow atari_ppo.py and change algorithm to A2CPolicy

**Comment by GongYanfu** [comment]
just change PPOPolicy to A2CPolicy and remove some useless arguments?
what's the role of scale_obs(DQN)?
and is the definition of actor and critic same as PPO?

**Comment by MischaPanch** [comment]
scale_obs gave the possiblity to preprocess the observations by multiplying them with a scalar (e.g., for normalizing them). This mechanism will be slightly changed by #1022 (to be merged today).

**Comment by MischaPanch** [comment]
I recommend you to try the high-level interfaces for training your models, have a look at the example scripts with `hl` in their names. Some documentation of high level interfaces is also added to the readme with #1022

**Comment by MischaPanch** [comment]
I assume it's answered, and atari was tested from scratch on mac. Closing this
