### ISSUE TITLE
Inquiry version 0.5.1 and version recommendation

### ISSUE THREAD

**Issue by H-xie** [aai-institute/tianshou#1073]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [x] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
    + [ ] design request (i.e. "X should be changed to Y.")
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

**0.5.1 0.29.1 2.2.1+cu121 1.26.4 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] linux**

---

Greetings, I am new to `Tianshou`. I installed `Tianshou` via `pypi`, which is version 0.5.1, but I cannot find a release or tag marked 0.5.1. Which version is the 0.5.1 corresponding to?

I find out the issue  #929 , and notice that this repo is under major upgrading. For a user, which version is recommended? 

Thank you for your time!

**Comment by MischaPanch** [comment]
Hi. I highly recommend to install the version that's on master. The documentation for master reflects it, just ignore the currently appearing warning. I'll try to release the new version on pypi (which will be 1.0.0) today or tomorrow

**Comment by H-xie** [comment]
So exciting! I'm looking forward to the new release! 

Thank you for the prompt response! 

Wishing you a wonderful day!
