### ISSUE TITLE
Chinese document pages return 404

### ISSUE THREAD

**Issue by H-xie** [aai-institute/tianshou#1078]
Really exciting to find out that 1.0.0 version has released. However, when I tried to look up current document, I found Chinese document pages return 404.

**Comment by MischaPanch** [comment]
It's a problem with readthedocs I guess, I'm going to look into it.

However, the Chinese docs haven't been updated in a long time, and they don't reflect the current codebase. Out of curiosity - is it important for you to have them? Does automatic translation not work well enough?

I would be in favor of removing them, since no one from our team can maintain them. Pinging @Trinkle23897

**Comment by H-xie** [comment]
It will be much easier to use if Chinese document is available. But, of course it is not necessary to read Chinese docs, English docs is sufficient for me.

About the removal of Chinese docs, I suggest to **keep** it with highlighting that it is out of date. It is a part of history of this repo.

Thank you again for bring this repo to its 1.0.0 version 🎉

**Comment by MischaPanch** [comment]
The Chinese docs are three years old, they are hopelessly outdated and we have no way of maintaining them. On top of that, automatic translations become better each minute. I removed all references to Chinese docs, hope it's ok for everyone involved. Closing this

**Comment by Trinkle23897** [comment]
It's here https://github.com/thu-ml/tianshou-docs-zh_CN

**Comment by juasen** [comment]
> The Chinese docs are three years old, they are hopelessly outdated and we have no way of maintaining them. On top of that, automatic translations become better each minute. I removed all references to Chinese docs, hope it's ok for everyone involved. Closing this

如果确定不再维护中文文档，直接将该项目的[README](https://github.com/thu-ml/tianshou/blob/master/README.md)中移除 中文文档 标签，同时将[项目文档](https://tianshou.org/en/stable/)中的 [中文文档链接](https://tianshou.readthedocs.io/zh/master/)的引用删除（该文档已经404了）。这样可以节省大家的时间。
