### ISSUE TITLE
Missing Link

### ISSUE THREAD

**Issue by DarkTechPirate** [aai-institute/tianshou#1099]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [x] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
    + [ ] design request (i.e. "X should be changed to Y.")
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
![image](https://github.com/thu-ml/tianshou/assets/145826347/80899e2d-f775-4ef5-9aba-f8fb855653c9)

Here the link for vanila limitations learning is missing

**Comment by MischaPanch** [comment]
Added a link to the wikipedia page, thanks for reporting!

**Comment by DarkTechPirate** [comment]
@MischaPanch let me know shall I complete it or is there any other specifically you need to completed , I need a pr to be merged within a day.

**Comment by MischaPanch** [comment]
I completed it, I just pushed the change on master. The readme is updated

**Comment by DarkTechPirate** [comment]
Okay nice , I will try to  start solving other issues

**Comment by MischaPanch** [comment]
Cool, happy to hear you want to participate in tianshou development! If you want some advice in selecting a suitable issue, feel free to contact me at m.panchenko@appliedai.de
