### ISSUE TITLE
Change log is chaotic and partly uninformative

### ISSUE THREAD

**Issue by opcode81** [aai-institute/tianshou#1129]
Changes pertaining to the same component are not grouped.
I would recommend a more hierarchical change log, where we group all changes according to the function/module/class they pertain to. The first change in a component establishes a bullet item and further changes in the same component change the entry to use sub-items.
This will make it much easier for a reader to determine which changes are relevant to them.

Some changes would benefit from a more detailed description. Reviewers should require good descriptions from contributors.

v1.0.0 should probably appear in the change log along with the release date.

We should also make clear that the topmost version is unreleased for clarity, i.e. "v1.1.0 (unreleased)", and then add the actual date once it's released.

**Comment by MischaPanch** [comment]
I structured it a bit in this [commit](https://github.com/thu-ml/tianshou/pull/1123/commits/e50c67c43ddd68c102754240285692552423e245)

**Comment by MischaPanch** [comment]
Noticed too late that you also structured it on another branch :(. Gonna clean up the conflict
