### ISSUE TITLE
Potential confusion about where start timesteps are collected in HL interfaces

### ISSUE THREAD

**Issue by MischaPanch** [aai-institute/tianshou#1135]
**EDIT:**

After looking a bit closer, I noticed that this was not a bug. We might want to refactor the HL interfaces to make this part a bit clearer. The buffer is prefilled with random steps when `create_train_test_collector`, which I find surprising. I wouldn't have guessed that this method can be potentially very expensive.

Moreover, one lacking feature, that we now actually need, is to collect a certain `n_episodes` prior to training (instead of `n_steps`). See my original text below.

**ORIGINAL DESCRIPTION:**

While going through the high level interfaces @bordeauxred and I noticed that no collection of random samples prior to training is possible there. The problem is in `Experiment.run`, which directly starts the training.

For several algos this can lead to serious performance degradation, for example for SAC. In procedural examples this is done by

```python
    train_collector.reset()
    train_collector.collect(n_step=args.start_timesteps, random=True)
```

prior to calling `trainer.run()`

This raises the question of whether performance was sufficiently tested for the `_hl` scripts. We might a strategy for that asap

@opcode81 @maxhuettenrauch FYI

**Comment by opcode81** [comment]
How can there be any confusion? The agent factory's create method is not a method a user is likely to ever call, as the high-level API performs all object creation tasks behind the scenes. And the prefilling of the collector is clearly logged, after all, so I don't really see how it could create any confusion.

The reasoning is that the creation method is supposed to provide collectors that can directly be used for training. So if the collectors shall be prefilled before the training begins, then the method takes care of that.

**Comment by MischaPanch** [comment]
Let's discuss in a call, this arose in an experimental refactoring of the experiment where the pre-filling behavior on creation gets in the way

**Comment by opcode81** [comment]
So what is this issue really about? Specifying the number of episodes instead of steps? 
Please update the description and delete the superfluous/outdated stuff.

**Comment by MischaPanch** [comment]
I will close it, we can discuss later, when the refactoring of experiment is closer to being merged.

Just didn't want to close without an explanation, since you likely got an email before I did the edit
