### ISSUE TITLE
ImportError: cannot import name 'Self' from 'typing' (/root/miniconda3/lib/python3.10/typing.py)

### ISSUE THREAD

**Issue by luweiagi** [aai-institute/tianshou#1148]
![image](https://github.com/thu-ml/tianshou/assets/19629731/efb4b4e4-e7b3-4988-abf1-d03af2fcf83e)
![image](https://github.com/thu-ml/tianshou/assets/19629731/2baaa15f-0782-4f3f-824a-f23e87e23989)

**Comment by MischaPanch** [comment]
Tianshou only supports python>=3.11, do you have an older python version?

EDIT: I now see from your title that you do, I'm surprised you even got it installed on 3.10 ^^.

Closing this
