### ISSUE TITLE
Improve interface of BasePolicy.compute_action

### ISSUE THREAD

**Issue by opcode81** [aai-institute/tianshou#1169]
- [X] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
    + [X] design request (i.e. "X should be changed to Y.")
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

The interface is not optimal, because not all observations are indeed arrays. Observations can also be array-like only (numpy's `ArrayLike` type). In fact, this is the case for some of gymnasium's standard implementations (e.g. `LazyFrames`).

I am not sure how appropriate the current type annotation is (i.e. `arr_type`, which also includes `Tensor`).

Proposal:
* Change type annotation of `obs` to numpy's `ArrayLike`
* Add first line which ensures array representation: `obs = np.array(obs)`. This will convert anything array-like to an actual array (e.g. using an implementation of `__array__` if necessary).

**Comment by MischaPanch** [comment]
Closed by #1170
