### ISSUE TITLE
tianshou v1.0.0 failed to install on python 3.12.4

### ISSUE THREAD

**Issue by musicaudience** [aai-institute/tianshou#1173]
tianshou 1.0.0 depends on numba<0.58.0 and >=0.57.1, from [numba's version support information](https://numba.readthedocs.io/en/stable/user/installing.html#numba-support-info), the version range is not working on python 3.12, but the [tianshou 1.0.0 installation docs ](https://tianshou.org/en/v1.0.0/) said it requires Python >= 3.11.

**Comment by MischaPanch** [comment]
Yes, some dependencies may fail on 3.12. Sorry for that!

I'll try to bump numba or specify <3.12 tomorrow

**Comment by MischaPanch** [comment]
@musicaudience pls try again :)

Eventually we might add python 3.12 to CI matrix, but the actions are already expensive in the current state
