### ISSUE TITLE
Make Batch.__eq__ work also for scalar values (0-dimensional arrays)

### ISSUE THREAD

**Issue by dantp-ai** [aai-institute/tianshou#1182]
As first noticed here https://github.com/thu-ml/tianshou/issues/1086#issuecomment-2157976997, DeepDiff which is currently used for batch equality cannot handle 0-dimensional arrays.

My current proposal is to leverage `np.atleast_1d` and the newest Batch API's `Batch.apply_values_transform` to convert any 0-dimensional arrays to 1-d while keeping the others as they are (cf. https://github.com/thu-ml/tianshou/issues/1086#issuecomment-2263079148).

**Comment by MischaPanch** [comment]
Hi @dantp-ai . All the merges of the new utils were delayed, but better late than never :D. 

Sounds good, this a good application of the new method. Feel free to open a PR

**Comment by MischaPanch** [comment]
And thanks for hanging in there! I want to devote significantly more time to tianshou in the next weeks and months. Ideally, we'd get to better internals, an automated benchmark that reproduces the results in the docs, and generally more inviting docs and readme over the next few weeks
