### ISSUE TITLE
Discrete distributions are broken

### ISSUE THREAD

**Issue by opcode81** [aai-institute/tianshou#1192]
In the current source version, discrete distributions are broken. (This is a new issue which is not present in the v1.0.0 release.)
Running, for example, `examples/atari/atari_ppo.py` gives this error:

```
  File "F:\Users\Dominik Jain\Dev\AI\tianshou\tianshou\policy\modelfree\pg.py", line 198, in forward
    dist = self.dist_fn(action_dist_input_BD)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dominik Jain\.conda\envs\tianshou\Lib\site-packages\torch\distributions\categorical.py", line 70, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "C:\Users\Dominik Jain\.conda\envs\tianshou\Lib\site-packages\torch\distributions\distribution.py", line 68, in __init__
    raise ValueError(
ValueError: Expected parameter probs (Tensor of shape (10, 6)) of distribution Categorical(probs: torch.Size([10, 6])) to satisfy the c
onstraint Simplex(), but found invalid values:
tensor([[-2.6794,  3.7065, -1.8398, -0.2533, -0.3333,  2.3994],
        [-2.6794,  3.7065, -1.8398, -0.2533, -0.3333,  2.3994],
        [-2.6794,  3.7065, -1.8398, -0.2533, -0.3333,  2.3994],
        [-2.6794,  3.7065, -1.8398, -0.2533, -0.3333,  2.3994],
        [-2.6794,  3.7065, -1.8398, -0.2533, -0.3333,  2.3994],
        [-2.6794,  3.7065, -1.8398, -0.2533, -0.3333,  2.3994],
        [-2.6794,  3.7065, -1.8398, -0.2533, -0.3333,  2.3994],
        [-2.6794,  3.7065, -1.8398, -0.2533, -0.3333,  2.3994],
        [-2.6794,  3.7065, -1.8399, -0.2533, -0.3333,  2.3994],
        [-2.6794,  3.7065, -1.8399, -0.2533, -0.3333,  2.3994]])

```

<hr>

- [X] I have marked all applicable categories:
    + [X] exception-raising bug
    + [X] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
    + [ ] design request (i.e. "X should be changed to Y.")
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

**Comment by maxhuettenrauch** [comment]
I figured what the problem is.

The examples now take 

```
    policy: PPOPolicy = PPOPolicy(
        actor=actor,
        critic=critic,
        optim=optim,
        dist_fn=Categorical,
...
```

whereas before, the `dist_fn` was defined as 

```
def dist(logits: torch.Tensor) -> Distribution:
    return Categorical(logits=logits)
```

The difference is that before, the input to the policy was given as a kwarg to be the logits. Now, it's a positional argument referring to the `probs` argument of Categorical which, of course, expects probabilities (i.e., numbers larger than 0, and summing to 1).

I can prepare a PR reverting these changes.

**Comment by opcode81** [comment]
Thanks, @maxhuettenrauch. I had already figured this out earlier but hadn't posted it here. Sorry for wasting your time.
