### ISSUE TITLE
Prioritized Replay Buffer: Anneal Beta or not?

### ISSUE THREAD

**Issue by hanghoo** [aai-institute/tianshou#1210]
Hello, I have a question about PER implementation. When instantiating one buffer with PER, I must set up Alpha and Beta parameters. I don't know if you anneal Beta. If yes, could you please point out where you implement it? Thank you very much.

**Comment by MischaPanch** [comment]
@Trinkle23897 do you know this one?

**Comment by Trinkle23897** [comment]
Sorry for the delay, the only two places are:
https://github.com/thu-ml/tianshou/blob/8eb27954192ebabb0dc8d28f88448f25a4186ed5/tianshou/data/buffer/prio.py#L79
https://github.com/thu-ml/tianshou/blob/8eb27954192ebabb0dc8d28f88448f25a4186ed5/tianshou/data/buffer/prio.py#L106

**Comment by hanghoo** [comment]
@Trinkle23897 Thank you for pointing out these places. To my understanding, I need to implement annealing the beta by myself, right?

**Comment by Trinkle23897** [comment]
Yes

**Comment by hanghoo** [comment]
Okay, thank you so much.
