### ISSUE TITLE
Modify the reward used for learning on the fly

### ISSUE THREAD

**Issue by drozzy** [aai-institute/tianshou#451]
Assuming my environment returns:

`state, reward, done, info={'extra_reward': 1}`

Is it possible to somehow modify the reward the agent uses for learning to be: `reward + info['extra_reward']`?

I assume this is to be do in process_fn, but I am not sure how to do it.

**Comment by Trinkle23897** [comment]
gym.wrapper to change the reward individually?

**Comment by drozzy** [comment]
Nvm, I'm going to rethink this question.
