### ISSUE TITLE
run atari_dqn.py .  error :has no attribute 'ALGymEnv'

### ISSUE THREAD

**Issue by 1abner1** [aai-institute/tianshou#452]
**run:** python atari_dqn.py 
**error:** AttributeError: module 'ale_py.gym' has no attribute 'ALGymEnv'
**but：**i have succed install ale_py of module.

**Comment by Trinkle23897** [comment]
It is because of the recent update of gym and ale_py. I'll post a link

**Comment by Trinkle23897** [comment]
https://github.com/openai/gym/issues/2407

**Comment by 1abner1** [comment]
thank you

**Comment by Trinkle23897** [comment]
https://github.com/openai/gym/releases/tag/v0.21.0
