### ISSUE TITLE
Bach split on a particular axis

### ISSUE THREAD

**Issue by abstrcode** [aai-institute/tianshou#454]
Hello, currently, it doesn't support batch split on a particular axis other than the first axis. How to modify the code to support this feature? Thanks.

**Comment by Trinkle23897** [comment]
Just a work around solution:
```python
def split_2ndaxis(batch):
  shape = batch.shape
  for i in range(shape[1]):
    yield batch[:, i]

for b in split_2ndaxis(batch):
  print(b)
```
