### ISSUE TITLE
Reproducibility for Atari tasks

### ISSUE THREAD

**Issue by nuance1979** [aai-institute/tianshou#456]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

Related to #449. I was trying to fix the reproducibility issue in `atari_bcq.py` and I initially believed it was coming from `set(a.parameters()).union(b.parameters())`. However, even if I kept the order of parameters fixed, I still got different results between two runs with the same seed. For example, I ran `python3 ./atari_dqn.py --task PongNoFrameskip-v4 --epoch 5` for 3 times and got 3 different results:

```
❯ grep best_reward log.dqn.pong.epoch_5*
log.dqn.pong.epoch_5:Epoch #1: test_reward: -21.000000 ± 0.000000, best_reward: -21.000000 ± 0.000000 in #0
log.dqn.pong.epoch_5:Epoch #2: test_reward: -21.000000 ± 0.000000, best_reward: -21.000000 ± 0.000000 in #0
log.dqn.pong.epoch_5:Epoch #3: test_reward: -21.000000 ± 0.000000, best_reward: -21.000000 ± 0.000000 in #0
log.dqn.pong.epoch_5:Epoch #4: test_reward: -21.000000 ± 0.000000, best_reward: -21.000000 ± 0.000000 in #0
log.dqn.pong.epoch_5:Epoch #5: test_reward: -21.000000 ± 0.000000, best_reward: -21.000000 ± 0.000000 in #0
log.dqn.pong.epoch_5: 'best_reward': -21.0,
log.dqn.pong.epoch_5.1:Epoch #1: test_reward: -19.000000 ± 1.264911, best_reward: -19.000000 ± 1.264911 in #1
log.dqn.pong.epoch_5.1:Epoch #2: test_reward: -16.100000 ± 2.385372, best_reward: -16.100000 ± 2.385372 in #2
log.dqn.pong.epoch_5.1:Epoch #3: test_reward: -19.100000 ± 0.943398, best_reward: -16.100000 ± 2.385372 in #2
log.dqn.pong.epoch_5.1:Epoch #4: test_reward: -18.600000 ± 1.624808, best_reward: -16.100000 ± 2.385372 in #2
log.dqn.pong.epoch_5.1:Epoch #5: test_reward: 2.400000 ± 2.059126, best_reward: 2.400000 ± 2.059126 in #5
log.dqn.pong.epoch_5.1: 'best_reward': 2.4,
log.dqn.pong.epoch_5.2:Epoch #1: test_reward: -20.800000 ± 0.600000, best_reward: -20.800000 ± 0.600000 in #1
log.dqn.pong.epoch_5.2:Epoch #2: test_reward: -12.800000 ± 0.600000, best_reward: -12.800000 ± 0.600000 in #2
log.dqn.pong.epoch_5.2:Epoch #3: test_reward: -16.000000 ± 1.843909, best_reward: -12.800000 ± 0.600000 in #2
log.dqn.pong.epoch_5.2:Epoch #4: test_reward: -12.700000 ± 3.689173, best_reward: -12.700000 ± 3.689173 in #4
log.dqn.pong.epoch_5.2:Epoch #5: test_reward: -10.400000 ± 1.562050, best_reward: -10.400000 ± 1.562050 in #5
log.dqn.pong.epoch_5.2: 'best_reward': -10.4,
```

I wonder where the randomness comes from given we already set the seeds like:

```
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    train_envs.seed(args.seed)
    test_envs.seed(args.seed)
```

Does it come from the vector replay buffer? Or does it come from GPU? Is it possible to remove it?

**Comment by Trinkle23897** [comment]
It comes from Atari random seed.

**Comment by nuance1979** [comment]
I found some discussion [here](https://github.com/openai/atari-py/issues/40). But they seemed to point to the opposite direction, i.e., lack of randomness in Atari games.

**Comment by Trinkle23897** [comment]
Oops, it comes from atari wrapper, the wrapper needs to overwrite `seed()` as `super().seed(seed); np.random.seed(seed)`

To reproduce this:
```python
In [14]: def sum_obs(acts):
    ...:     env = wrap_deepmind("PongNoFrameskip-v4")
    ...:     np.random.seed(0)
    ...:     env.seed(0)
    ...:     obs = env.reset() * 1.0
    ...:     for a in acts:
    ...:         obs_, rew, done, info = env.step(a)
    ...:         obs += obs_
    ...:         if done:
    ...:             obs += env.reset()
    ...:     return obs.sum()
    ...: 

In [15]: action_list = np.random.randint(6, size=1000)

In [16]: sum_obs(action_list)
Out[16]: 3008422279.0

In [17]: sum_obs(action_list)
Out[17]: 3008422279.0

In [18]: sum_obs(action_list)
Out[18]: 3008422279.0

In [19]: action_list = np.random.randint(6, size=2000)

In [20]: sum_obs(action_list)
Out[20]: 6010576927.0

In [21]: sum_obs(action_list)
Out[21]: 6010576927.0

In [22]: sum_obs(action_list)
Out[22]: 6010576927.0

In [23]: sum_obs(action_list)
Out[23]: 6010576927.0

In [24]: action_list = np.random.randint(6, size=10000)

In [25]: sum_obs(action_list)
Out[25]: 30060197806.0

In [26]: sum_obs(action_list)
Out[26]: 30060197806.0

In [27]: def sum_obs(acts):
    ...:     env = wrap_deepmind("PongNoFrameskip-v4")
    ...:     # np.random.seed(0)
    ...:     env.seed(0)
    ...:     obs = env.reset() * 1.0
    ...:     for a in acts:
    ...:         obs_, rew, done, info = env.step(a)
    ...:         obs += obs_
    ...:         if done:
    ...:             obs += env.reset()
    ...:     return obs.sum()
    ...: 

In [28]: action_list = np.random.randint(6, size=1000)

In [29]: sum_obs(action_list)
Out[29]: 3004471154.0

In [30]: sum_obs(action_list)
Out[30]: 3005675309.0

In [31]: sum_obs(action_list)
Out[31]: 3004489182.0
```

**Comment by Trinkle23897** [comment]
But I remember that one years ago I came across an issue in either gym or baselines or atari_py that said atari_py set only one of the two seeds in its `seed` function and that causes this issue. I cannot find this issue now, unfortunately. And maybe that's wrong.

**Comment by nuance1979** [comment]
> Oops, it comes from atari wrapper, the wrapper needs to overwrite `seed()` as `super().seed(seed); np.random.seed(seed)`

I tried it but the results were still different between runs. It's possible that there is still some unintended randomness in the code. I poked around but did not succeed. (For example, I tried `--training-num 1 --test-num 1` but the results were still different.)

Is there a version where `atari_dqn.py` gets reproducible results that I can go back to? What is the situation in MuJoCo experiments? Are they reproducible?

**Comment by Trinkle23897** [comment]
Mujoco experiments are fully reproducible. I'll take a look when I'm free...

**Comment by Trinkle23897** [comment]
First interesting finding: when using DummyVectorEnv it is deterministic, however, SubprocVectorEnv and ShmemVectorEnv's result is not deterministic.

**Comment by Trinkle23897** [comment]
@nuance1979 sorry for the extremely late response, please check if #467 works for you, thanks!

**Comment by nuance1979** [comment]
> @nuance1979 sorry for the extremely late response, please check if #467 works for you, thanks!

That was a brilliant fix. However, even after this fix, the results on Pong with DQN are still not deterministic. What's more troubling, even if I ran with `--training-num 1 --test-num 1`. The results were still not deterministic.

I don't know whether it's due to my environment. I was running with `torch==1.6.0`. Should I upgrade torch to a higher version ?

**Comment by nuance1979** [comment]
> > @nuance1979 sorry for the extremely late response, please check if #467 works for you, thanks!
> 
> That was a brilliant fix. However, even after this fix, the results on Pong with DQN are still not deterministic. What's more troubling, even if I ran with `--training-num 1 --test-num 1`. The results were still not deterministic.
> 
> I don't know whether it's due to my environment. I was running with `torch==1.6.0`. Should I upgrade torch to a higher version ?

After upgrading to `torch==1.8.2`, I set `torch.use_deterministic_algorithms(True)` and found that:

- When running on GPU, I got RuntimeError about cublas matrix op not being deterministic;
- When running on CPU, I got DETERMINISTIC results!

So I think the remaining non-deterministicity should attribute to CUDA/GPU, which we can't control.

**Comment by Trinkle23897** [comment]
> So I think the remaining non-deterministicity should attribute to CUDA/GPU, which we can't control.

Is it because of CNN layer?
