### ISSUE TITLE
Is the result of sac normal?

### ISSUE THREAD

**Issue by FulChou** [aai-institute/tianshou#465]
i run the example mujoco/mujoco_sac.py in my machine
result is :
![image](https://user-images.githubusercontent.com/46887649/137650387-9d096d27-fab5-4149-88dd-38a34db36737.png)

Seeing that there is a lot of uneven jitter and not as good as you Give the results picture so good results, why is this?

**Comment by Trinkle23897** [comment]
Because we use 10 trials (with different random seeds) to draw that curve with (mean, std).

**Comment by FulChou** [comment]
Thank you very much for your answer, so the dotted line in the benmark graph is the upper and lower term of the standard deviation of the ten  trials? Also I would like to ask if the random seeds for the 10 times are 0~9?

**Comment by Trinkle23897** [comment]
Exactly. See https://github.com/thu-ml/tianshou/blob/master/examples/mujoco/README.md

**Comment by FulChou** [comment]
> Exactly. See https://github.com/thu-ml/tianshou/blob/master/examples/mujoco/README.md

Thanks
