### ISSUE TITLE
results in examples/atari/atari_dqn are in fact double DQN?

### ISSUE THREAD

**Issue by initial-h** [aai-institute/tianshou#471]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
I'm trying to reproduce the results of atari_dqn.py, but I get much lower performance on BreakoutNoFrameskip-v4 (<200). Then I dig into the code and find another problem as shown here.
It seems the default algorithm is double dqn not nature dqn, is it right?
https://github.com/thu-ml/tianshou/blob/098d466467946bf6fa0bc4daf1c9e711a0ed16d7/tianshou/policy/modelfree/dqn.py#L44
And it also uses n-step return, where n=3, not 1?
https://github.com/thu-ml/tianshou/blob/098d466467946bf6fa0bc4daf1c9e711a0ed16d7/examples/atari/atari_dqn.py#L28

**Comment by Trinkle23897** [comment]
Yes you are right. You can use --n-step 1 and usually it'll get higher result in breakout
