### ISSUE TITLE
Some questions about RecurrentCritic().

### ISSUE THREAD

**Issue by wakeupppp** [aai-institute/tianshou#472]
- [ ] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:

Version: `0.4.4 1.8.1+cu111 1.20.3 3.7.0 (default, Oct  9 2018, 10:31:47)  [GCC 7.3.0] linux`
## Question
Hey, I am using PPO with RNN. 
But in `RecurrentCritic()`, I'm not sure the network structure is totally right. Like line 302 of `continuous.py`. My code works correctly with the next line without action_shape:
```python
self.fc2 = nn.Linear(hidden_layer_size + int(np.prod(action_shape)), 1)
# self.fc2 = nn.Linear(hidden_layer_size, 1)
```
Cause in `ppo.py`, just use `obs`:
![image](https://user-images.githubusercontent.com/39750646/139387680-4f2af956-568e-4dd1-9ed7-3cc9eb2f5585.png)
Did I do something wrong :(

**Comment by Trinkle23897** [comment]
But actually by default it can accept only obs as input: 
https://github.com/thu-ml/tianshou/blob/098d466467946bf6fa0bc4daf1c9e711a0ed16d7/tianshou/utils/net/continuous.py#L288
https://github.com/thu-ml/tianshou/blob/098d466467946bf6fa0bc4daf1c9e711a0ed16d7/tianshou/utils/net/continuous.py#L307
as you can see the `action=None` and `action_shape=[0]`.

Could you please provide more details like is the environment in continuous space? Not sure what's going wrong.

**Comment by wakeupppp** [comment]
Thanks!  I know where is the problem. If I give param `action_shape=[24]` in `RecurrentCritic's __init__`( 24 is the action dim of my env), the `fc2` layer's dim will be `hiddensize+ 24` instead of `hiddensize + 0`.  `fc2` layer's cacultion would be wrong.  
https://github.com/thu-ml/tianshou/blob/098d466467946bf6fa0bc4daf1c9e711a0ed16d7/tianshou/utils/net/continuous.py#L288

**Comment by Trinkle23897** [comment]
oh okay, glad to hear that!
