### ISSUE TITLE
Code Not Correcly Formatted

### ISSUE THREAD

**Issue by Markus28** [aai-institute/tianshou#474]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:

Hey,

I followed https://tianshou.readthedocs.io/en/latest/contributing.html to install Tianshou. `make check-codestyle` tells me that a file is not correctly formatted. More specifically:

```
$ isort examples/vizdoom/vizdoom_c51.py --diff
--- /?/tianshou/examples/vizdoom/vizdoom_c51.py:before    2021-10-31 10:46:27.907566
+++ /?/tianshou/examples/vizdoom/vizdoom_c51.py:after     2021-10-31 11:25:14.541484
@@ -4,10 +4,10 @@
 
 import numpy as np
 import torch
-from env import Env
 from network import C51
 from torch.utils.tensorboard import SummaryWriter
 
+from env import Env
 from tianshou.data import Collector, VectorReplayBuffer
 from tianshou.env import ShmemVectorEnv
 from tianshou.policy import C51Policy
```
I will raise a (very) small pull request to fix this.

Best,
Markus

**Comment by Trinkle23897** [comment]
However in my local environment everything looks fine. Not sure what happens... I'm in ubuntu 20.04

![2021-10-31 09-33-39屏幕截图](https://user-images.githubusercontent.com/8189182/139586176-8445c33c-6131-468c-92f0-7e589b092621.png)

BTW, don't worry about that, I can fix these issues at the end of your new PR.

**Comment by Markus28** [comment]
I think I found the reason: I mistakenly called my virtual environment `env` instead of `venv`. That probably messed up the ordering of the imports. Sorry for causing the confusion, it is working now!
