### ISSUE TITLE
Filter the data that train_collector collects and then add the data to the buffer

### ISSUE THREAD

**Issue by xinglu-pnnl** [aai-institute/tianshou#493]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [X] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [X] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

I am working on applying Tianshou PPO to a customized environment. For each episode in this specific environment, there are certain periods at which I do not want the agent to learn since the agent's decision will not do anything for the environment output. 
Therefore, I am thinking of discarding/filtering these experience before added to the buffer. I wonder what is way to implement that. 

For example, I am collecting `episode_per_collect` episodes during each training epoch, and I want to filter out some steps when `obs` reach some conditions.
`result = train_collector.collect(n_step=step_per_collect, n_episode=episode_per_collect)`

Any advice would be greatly appreciated.

**Comment by Trinkle23897** [comment]
I think there are two approaches:
1. add mask in policy.learn: need an extra class inheriting PPOPolicy and overwrite `learn`
2. or create a new class `FilterVectorBuffer` that inherits `VectorReplayBuffer` and only overwrites `.add()`, e.g.,
```python
class FilterVectorBuffer(VectorReplayBuffer):
  def __init__(self, filter_fn, *args, **kwargs):
    self.filter_fn = filter_fn
    super().__init__(*args, **kwargs)
  def add(self, batch, buffer_ids):
    mask = np.ones_like(buffer_ids, dtype=bool)
    for i, o in enumerate(batch.obs):
      if not self.filter_fn(o):
        mask[i] = False
    batch = batch[mask]
    buffer_ids = np.array(buffer_ids)[mask]
    super().add(batch, buffer_ids)
```

**Comment by xinglu-pnnl** [comment]
Thanks for pointing out these two approaches. Really appreciate that!
