### ISSUE TITLE
Multiple configurations with SubprocVectorEnv only adopt the last config

### ISSUE THREAD

**Issue by abstrcode** [aai-institute/tianshou#495]
I want to configure envs with different configurations in the SubprocVectorEnv function. However, self.env only create repeated env with the last configure. For example, self.env = [env_n, env_n, ..., env_n]. I have already checked to ensure config_list contain different configure dictionaries.
`self.env = SubprocVectorEnv([lambda: single_env(ci) for ci in config_list])`

**Comment by Trinkle23897** [comment]
Actually the current unit test has demonstrated this kind of usage. You can do either
https://github.com/thu-ml/tianshou/blob/3592f45446e6cc98423df2f1c28d8ca0ef2be821/test/base/test_env.py#L128-L131
or
https://github.com/thu-ml/tianshou/blob/3592f45446e6cc98423df2f1c28d8ca0ef2be821/test/base/test_env.py#L86-L91

For your case, it should be 
```
self.env = SubprocVectorEnv([lambda ci=ci: single_env(ci) for ci in config_list])
```

**Comment by abstrcode** [comment]
Thanks.
