### ISSUE TITLE
PPO example for Spaceinvaders

### ISSUE THREAD

**Issue by Will-Nie** [aai-institute/tianshou#497]
May I ask if there are any examples using PPO to train spaceinvaders ?

I noticed there was a pong_ppo.py file in the past opened issue. Is it going to achieve good performance on spaceinvaders simply by changing the env_id?

**Comment by Trinkle23897** [comment]
#374 
will do in these two weeks

**Comment by Will-Nie** [comment]
Ok, thx for the quick reply!
