### ISSUE TITLE
A question: LSTM + PPO

### ISSUE THREAD

**Issue by tesla-cat** [aai-institute/tianshou#498]
## A question

- I want to build a small scale version of **Open AI Five**
- And I learnt that it uses LSTM + PPO
- suppose I build a network model using LSTM, then should I use this network for both Actor and Critic? 
- if not, what should I use?
---
- I have tried to find online tutorials about using RNN as model for RL, but didn't find useful ones
- can you recommend some hands-on tutorials on this?
- it would be even better if you can create a tutorial on this using `tianshou`, thank you!

**Comment by Trinkle23897** [comment]
https://tianshou.readthedocs.io/en/master/tutorials/cheatsheet.html#rnn-style-training
https://github.com/thu-ml/tianshou/issues/486#issuecomment-1002665193

**Comment by vwxyzjn** [comment]
Hey @tesla-cat, coincidentally we have been building OpenAI Five style bots in [gym-microrts](https://github.com/vwxyzjn/gym-microrts), which looks like 

![](https://github.com/vwxyzjn/gym-microrts/raw/master/static/fullgame.gif)


We have successfully prototyped [PPO + LSTM in the Atari games](https://github.com/vwxyzjn/cleanrl/pull/83), and we hope to prototype PPO + LSTM in gym-microrts as well. If you are interested in helping with this prototype, please let me know :)
