### ISSUE TITLE
Loading ReplayBuffer checkpoint into Collector

### ISSUE THREAD

**Issue by Markus28** [aai-institute/tianshou#500]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:

I am using the commit 8f19a8696672fa49ead41e4e93d5d79855e5d6aa with Torch: 1.9.0+cu111 Numpy: 1.20.0 Sys: 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0] linux 

I have a long-running job which is executed on a cluster. To avoid resource fragmentation and keep running costs low, I have to make frequent checkpoints, abort the training process, then schedule a new job to resume it. I save the model and optimizers via PyTorch. The `VectorReplayMemory` is saved via `save_hdf5`. Since `Collector` has no interface for serialization (understandably so), I tried to initialize a new `Collector` object with the deserialized replay memory. However, I learned that `Collector` resets the memory upon initialization. Thus, it is currently impossible to resume training in this fashion. I could set the `buffer` attribute manually, but this seems problematic, especially since there is a private `_assign_buffer` method, that checks certain constraints.

Is there any way around this problem? If not, is there a good reason to reset the replay memory whenever a `Collector` is initialized? What would you think about adding a keyword argument `reset_buffer=True` to `Collector.__init__`? 
I'd be happy to raise a pull request for this.

Thanks for your help!

Best,
Markus

**Comment by Trinkle23897** [comment]
How about just removing `self.reset_buffer()` in `collector.reset()`?

**Comment by Markus28** [comment]
That would definitely work for me and could arguably be the more intuitive behavior of reset. Though I'd be afraid that it might break someone's code without them noticing. But if you think that it's the right way to go, I'll do it like that :)
