### ISSUE TITLE
gpu test action times out

### ISSUE THREAD

**Issue by jc-bao** [aai-institute/tianshou#508]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:

The Actions of tianshou repository that runs on the CPU went well, but the GPU Test is not working as it cannot find the self-hosted idle server.
The error of GitHub is as follows:

```
This request was automatically failed because there were no enabled runners online to process the request for more than 1 days.
```

**Comment by Trinkle23897** [comment]
You can just ignore that. That needs a private machine with GPU and connect to github action service.

**Comment by jc-bao** [comment]
Thanks for the information!
