### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by abstrcode** [aai-institute/tianshou#511]
I found the cpu usage can be as high as 1200% for each process when using parallel simulation. How to restrict the cpu usage? Thanks.

**Comment by Trinkle23897** [comment]
Which environment do you use? I guess it's mujoco?

**Comment by abstrcode** [comment]
I used my own created environment. Is there a general method to handle this issue?

**Comment by Trinkle23897** [comment]
Actually we can do nothing with the current SubprocVectorEnv because of python subprocess. However, if the vector env is [based on threadpool](https://github.com/sail-sg/envpool), we can easily control the total number of threads and limit CPU usage (and also faster!).

**Comment by abstrcode** [comment]
It seems a bit complex to create a new environment using envpool.

**Comment by Trinkle23897** [comment]
Yes, so right now I'm working on easier customized env integration with envpool...
