### ISSUE TITLE
Collector issue: TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by dhruvsreenivas** [aai-institute/tianshou#516]
- [ ] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

Hi,

I am currently trying to run experiments with Tianshou's QR-DQN, and have this issue where I create a collector and the ```collector.collect()``` call fails. The full stack trace is below.

<img width="1094" alt="error_msg" src="https://user-images.githubusercontent.com/16987782/151681049-71777edc-0542-449a-8e3d-e7f2423aaf13.png">

The code for the training loop I have here is as follows:

<img width="745" alt="main_code" src="https://user-images.githubusercontent.com/16987782/151681091-38237e34-d46d-4f1a-872b-bfeb0212bf46.png">

> I am trying to make the training procedure as similar as possible to the atari_qrdqn example in the Tianshou repo, but am refraining from using an off-policy trainer here, as I do some modifications to the batch/replay buffer rewards before I update the policy. The environment here is a Dreamer-like wrapped gym environment, where we use all color channels and have 64x64 images (so the observations are of shape (3, 64, 64) as opposed to the (4, 84, 84) frame-stacked grayscale images that DeepMind uses to wrap observations). I have tried to debug this error, although I haven't gotten anywhere on it for the past few days, and was wondering if someone from the Tianshou team could help here. Thank you so much!

I've tried to make it as similar to the training loop shown in ```examples/atari/atari_qrdqn.py``` in the repository, but due to some reward modifications I'm making for my own work I'm not using the ```offpolicy_trainer``` already in the library. The environment here is a Dreamer-like wrapped Atari Gym environment (hence the ```C, H, W``` shown in the code). I was wondering how to fix this error--any help would be greatly appreciated. Thanks!

This is with ```tianshou``` version 0.4.5, with ```torch``` version 1.10.1, ```numpy``` version 1.19.2, python 3.7.

**Comment by Trinkle23897** [comment]
> The environment here is a Dreamer-like wrapped Atari Gym environment

Could you please check if there's any dynamic key creation in your environment? You can add a print in batch.py L259 `__setitem__` function to see what happens.

**Comment by dhruvsreenivas** [comment]
Yeah, it seems that there are no keys in the self.__dict__() when it is initialized (there is nothing in the dict it looks like). Meanwhile, the value keys are the normal (info, obs_next, obs, etc.).

**Comment by Trinkle23897** [comment]
That's normal, by design the buffer support dynamic key adding. However, if it has the following case:
```
step 1: rew=1
step 2: rew=np.array([[1]])
```
The shape would mismatch thus causing error. Could you please check with that? You can just print all of the data in one episode and put it here.
Or could you please provide a minimal example for `buffer.add(data)` that will trigger such an exception?

**Comment by dhruvsreenivas** [comment]
I see, I've edited ```base.py``` to see what the batch looks like when getting added to the buffer.

A screenshot of what I see is here (it looks like there is only 1 step):
<img width="715" alt="Screen Shot 2022-01-30 at 9 45 58 AM" src="https://user-images.githubusercontent.com/16987782/151704533-f9bcfc0f-b273-4fce-a60d-e07c561dac48.png">

**Comment by Trinkle23897** [comment]
what's your detailed modification in `base.py`?

I run this:
```python
In [3]: from tianshou.data import Batch, ReplayBuffer

In [4]: b=ReplayBuffer(100)

In [5]: import numpy as np

In [8]: data = Batch(obs=np.zeros([1, 3, 64, 64], np.uint8), info={"env_id": [0], "ale.lives": [0]}, rew=np.array([0.]), act=[4], obs_next=np.zeros([1, 3, 64, 64], np.uint8), done=[False])

In [9]: data
Out[9]: 
Batch(
    obs: array([[[[0, 0, 0, ..., 0, 0, 0],
                  [0, 0, 0, ..., 0, 0, 0],
                  [0, 0, 0, ..., 0, 0, 0],
                  ...,
                  [0, 0, 0, ..., 0, 0, 0],
                  [0, 0, 0, ..., 0, 0, 0],
                  [0, 0, 0, ..., 0, 0, 0]],
         
                 [[0, 0, 0, ..., 0, 0, 0],
                  [0, 0, 0, ..., 0, 0, 0],
                  [0, 0, 0, ..., 0, 0, 0],
                  ...,
                  [0, 0, 0, ..., 0, 0, 0],
                  [0, 0, 0, ..., 0, 0, 0],
                  [0, 0, 0, ..., 0, 0, 0]],
         
                 [[0, 0, 0, ..., 0, 0, 0],
                  [0, 0, 0, ..., 0, 0, 0],
                  [0, 0, 0, ..., 0, 0, 0],
                  ...,
                  [0, 0, 0, ..., 0, 0, 0],
                  [0, 0, 0, ..., 0, 0, 0],
                  [0, 0, 0, ..., 0, 0, 0]]]], dtype=uint8),
    info: Batch(
              env_id: array([0]),
              ale.lives: array([0]),
          ),
    rew: array([0.]),
    act: array([4]),
    obs_next: array([[[[0, 0, 0, ..., 0, 0, 0],
                       [0, 0, 0, ..., 0, 0, 0],
                       [0, 0, 0, ..., 0, 0, 0],
                       ...,
                       [0, 0, 0, ..., 0, 0, 0],
                       [0, 0, 0, ..., 0, 0, 0],
                       [0, 0, 0, ..., 0, 0, 0]],
              
                      [[0, 0, 0, ..., 0, 0, 0],
                       [0, 0, 0, ..., 0, 0, 0],
                       [0, 0, 0, ..., 0, 0, 0],
                       ...,
                       [0, 0, 0, ..., 0, 0, 0],
                       [0, 0, 0, ..., 0, 0, 0],
                       [0, 0, 0, ..., 0, 0, 0]],
              
                      [[0, 0, 0, ..., 0, 0, 0],
                       [0, 0, 0, ..., 0, 0, 0],
                       [0, 0, 0, ..., 0, 0, 0],
                       ...,
                       [0, 0, 0, ..., 0, 0, 0],
                       [0, 0, 0, ..., 0, 0, 0],
                       [0, 0, 0, ..., 0, 0, 0]]]], dtype=uint8),
    done: array([False]),
)

In [10]: b.add(data)
Out[10]: (array([0]), array([[0.]]), array([0]), array([0]))
```

**Comment by dhruvsreenivas** [comment]
I did this, in ```base.py```:

<img width="602" alt="Screen Shot 2022-01-30 at 9 53 47 AM" src="https://user-images.githubusercontent.com/16987782/151704838-530384aa-d698-4141-a91a-952edeaec5f4.png">

This yielded the output in terminal.

**Comment by Trinkle23897** [comment]
try this:
```python
try:
    print(batch)  # <-- print here
    self._meta[ptr] = batch
except ValueError:
    ...
```

**Comment by dhruvsreenivas** [comment]
<img width="784" alt="Screen Shot 2022-01-30 at 9 55 50 AM" src="https://user-images.githubusercontent.com/16987782/151704899-4feaeca7-47f6-4de2-8570-75d766cd5d12.png">

yields the above

**Comment by Trinkle23897** [comment]
```python
BUFFER_SIZE = int(1e4)
```

float is not allowed for allocating arrays. In fact the following will generate the same issue:
```python
In [1]: import numpy as np

In [2]: np.zeros([1.0])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-f399acbed80a> in <module>
----> 1 np.zeros([1.0])

TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by dhruvsreenivas** [comment]
Ah, I see. I think it works now. Thank you so much! I think we can close this issue now
