### ISSUE TITLE
Question about Trainer.py

### ISSUE THREAD

**Issue by chuong98** [aai-institute/tianshou#519]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [x] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system aXnd environment, where applicable:
```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
 ```
Print Result: 0.4.5 1.10.2 1.21.2 3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0] linux

Hi, I am reading the code of trainer, and I can't quite understand the following code lines.
https://github.com/thu-ml/tianshou/blob/c25926dd8f5b6179f7f76486ee228982f48b4469/tianshou/trainer/offpolicy.py#L99
My appologize if this question is too obvious, but I hope that you can help me clarify it:
```python
  if test_collector is not None:
        test_c: Collector = test_collector  # for mypy
        test_collector.reset_stat()
        test_result = test_episode(
            policy, test_c, test_fn, start_epoch, episode_per_test, logger, env_step,
            reward_metric
        )
``` 
What is the purpose of `test_c: Collector = test_collector  # for mypy`. Why don't we directly use?
```python
test_collector.reset_stat()
test_result = test_episode(
            policy, test_collector, test_fn, start_epoch, episode_per_test, logger, env_step,
            reward_metric
        )
 ```

**Comment by Trinkle23897** [comment]
It's because of mypy... The 2nd version of code is exactly the same as above, but the annoying mypy needs to ensure collector is not None...

**Comment by chuong98** [comment]
I see, but doesn't the 
`if test_collector is not None:`  already ensure that ?
Thank you.

**Comment by Trinkle23897** [comment]
```python
$ mypy                             
tianshou/trainer/offpolicy.py: note: In function "offpolicy_trainer":
tianshou/trainer/offpolicy.py:137: error: Argument 2 to "test_episode" has incompatible type "Optional[Collector]"; expected "Collector"  [arg-type]
                                policy, test_collector, test_fn, epoch, episode_per_test, logger,
                                        ^
Found 1 error in 1 file (checked 71 source files)
```
