### ISSUE TITLE
policy gradient learn function casting episode returns to int when using discrete actions

### ISSUE THREAD

**Issue by Kenneth-Schroeder** [aai-institute/tianshou#520]
In the `learn(...)` function of the PGPolicy class, the `to_torch_as(...)` function is used on the return values of the input batch to convert them to a tensor of similar characteristics as the actions. When using discrete actions, this results in a problem as continuous rewards/returns are casted to integers.
https://github.com/thu-ml/tianshou/blob/c25926dd8f5b6179f7f76486ee228982f48b4469/tianshou/policy/modelfree/pg.py#L134

This can be fixed by checking `self.action_type` of the PGPolicy object and transforming the return values accordingly.

**Comment by Trinkle23897** [comment]
How about 
```python
ret = to_torch(minibatch.returns, result.act.device, torch.float)
```

**Comment by Kenneth-Schroeder** [comment]
works as well :)

**Comment by Trinkle23897** [comment]
Thanks for pointing it out! Are you willing to submit a pull request to fix this issue? (I believe it occurs many times)

**Comment by Kenneth-Schroeder** [comment]
Yes, I will take a look at it :)

**Comment by Kenneth-Schroeder** [comment]
Done for PGPolicy. The parameter order is actually `ret = to_torch(minibatch.returns, torch.float, result.act.device)` :)

**Comment by Kenneth-Schroeder** [comment]
I fixed code style, ran tests etc. and also checked all other occurrences of `to_torch_as(...)`, but none other looked suspicious. PR should be ready for merge. @Trinkle23897
