### ISSUE TITLE
How to use self defined environment and set actions?

### ISSUE THREAD

**Issue by mf093087** [aai-institute/tianshou#524]
env.render() 
    action=env.action_space.sample() 
    s_,r,done,info=env.step(action)

How do I define the actions in Tianshou framework?

**Comment by Trinkle23897** [comment]
Examples: https://github.com/thu-ml/tianshou/blob/master/test/base/env.py

APIs (follow gym): https://tianshou.readthedocs.io/en/master/tutorials/cheatsheet.html#user-defined-environment-and-different-state-representation

**Comment by mf093087** [comment]
> Examples: https://github.com/thu-ml/tianshou/blob/master/test/base/env.py
> 
> APIs (follow gym): https://tianshou.readthedocs.io/en/master/tutorials/cheatsheet.html#user-defined-environment-and-different-state-representation

Hi thanks a lot. But this example is used for defining the environment. Once I defined the environment and register it in gym. How can I call the method from this environment? For example, normally I can write
action=env.action_space.sample() 
s_,r,done,info=env.step(action)

to give the action definitions and use the step method. How can I do this in Tianshou framework?

**Comment by Trinkle23897** [comment]
https://github.com/thu-ml/tianshou/blob/40289b8b0e41c49ddf02942d688cdf2199d4919d/tianshou/data/collector.py#L160-L161

**Comment by mf093087** [comment]
> https://github.com/thu-ml/tianshou/blob/40289b8b0e41c49ddf02942d688cdf2199d4919d/tianshou/data/collector.py#L160-L161

Thanks a lot, could you please elaborate it a little bit?

**Comment by Trinkle23897** [comment]
> action=env.action_space.sample()
> s_,r,done,info=env.step(action)

This is to use the random action to sample episodes. `Collector` is in charge of this job (handle interactions between env and policy). You can use `collector.collect(..., random=True)` and the collected episode (from random policy) is in the corresponding buffer.

More examples: https://github.com/thu-ml/tianshou/blob/40289b8b0e41c49ddf02942d688cdf2199d4919d/test/base/test_collector.py#L98

**Comment by mf093087** [comment]
> > action=env.action_space.sample()
> > s_,r,done,info=env.step(action)
> 
> This is to use the random action to sample episodes. `Collector` is in charge of this job (handle interactions between env and policy). You can use `collector.collect(..., random=True)` and the collected episode (from random policy) is in the corresponding buffer.
> 
> More examples:
> 
> https://github.com/thu-ml/tianshou/blob/40289b8b0e41c49ddf02942d688cdf2199d4919d/test/base/test_collector.py#L98

Thanks a lot, is there a comprehensive example using self-defined environment with Tianshou framework?

**Comment by mf093087** [comment]
> 

Normally, it should be 
action=env.action_space.sample()
s_,r,done,info=env.step(action)

So, in Tianshou framework, I should use the collector.collect() like you said. Shoud I do it like this?
collector.collect(action, random = True)

**Comment by mf093087** [comment]
> > > action=env.action_space.sample()
> > > s_,r,done,info=env.step(action)
> > 
> > 
> > This is to use the random action to sample episodes. `Collector` is in charge of this job (handle interactions between env and policy). You can use `collector.collect(..., random=True)` and the collected episode (from random policy) is in the corresponding buffer.
> > More examples:
> > https://github.com/thu-ml/tianshou/blob/40289b8b0e41c49ddf02942d688cdf2199d4919d/test/base/test_collector.py#L98
> 
> Thanks a lot, is there a comprehensive example using self-defined environment with Tianshou framework?

what does n_step mean here?

**Comment by Trinkle23897** [comment]
> what does n_step mean here?

The number of steps to be collected and save into replay buffer. See the parameter list here:
https://tianshou.readthedocs.io/en/master/api/tianshou.data.html#tianshou.data.Collector.collect
