### ISSUE TITLE
Where to put the arguments? obs_next, rew, done, _ = env.step(act)                      # collector.collect(...)

### ISSUE THREAD

**Issue by mf093087** [aai-institute/tianshou#525]
According to the pseudo code, 
https://tianshou.readthedocs.io/en/master/tutorials/concepts.html

    act = agent.compute_action(obs)                             # act = policy(batch, ...).act
    obs_next, rew, done, _ = env.step(act)                      # collector.collect(...)
![image](https://user-images.githubusercontent.com/67538561/153679483-e2c584f8-f6ac-4240-aba7-975a99012eca.png)

May I ask, can you describe them in more detail? For example, collector.collect(...), where should I put act(as mentioned in the pseudo code) as an argument in the collect method? Because in collect method, I only find these parameters, there seem to be no parameters for the act.         
        n_step: Optional[int] = None,
        n_episode: Optional[int] = None,
        random: bool = False,
        render: Optional[float] = None,
        no_grad: bool = True,

I

**Comment by Trinkle23897** [comment]
The `act` is generated by either random action (`env.action_space.sample()`) or policy's forward function. There's no need to manually add action to the environment.

https://github.com/thu-ml/tianshou/blob/40289b8b0e41c49ddf02942d688cdf2199d4919d/tianshou/data/collector.py#L220-L241

**Comment by mf093087** [comment]
> The `act` is generated by either random action (`env.action_space.sample()`) or policy's forward function. There's no need to manually add action to the environment.
> 
> https://github.com/thu-ml/tianshou/blob/40289b8b0e41c49ddf02942d688cdf2199d4919d/tianshou/data/collector.py#L220-L241

Thanks a lot for the promt reply! My environment is like this:

```python
class SimulateEV(gym.Env):
     def __init__(self, img_w, img_h, n_channels, n_actions, port=PORT, step_factor=1):
         super(SimulateEV, self).__init__()
 
         self.img_w = img_w
         self.img_h = img_h
         self.num_channels = n_channels
         self.step_factor = step_factor
         self.action_space = gym.spaces.Discrete(n_actions)
         self.observation_space = gym.spaces.Box(low=0, high=500, shape=(self.num_channels, 2), dtype=np.int32)
         self.socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
         self.socket.connect(('127.0.0.1', port))
 
 
     def step(self, action):
         step = action
         msg_as_byte_arr = str.encode('step_' + ','.join([str(x) for x in step]))
         return self.__send_msg__(msg_as_byte_arr)
 
     def reset(self):
         return self.__send_msg__(b"reset")
 
     def render(self, mode='rgb_array'):
         return self.observation
  
     def __send_msg__(self, msg_as_byte_arr):
         msg_id = self.__generate_4_chars_id__()
         self.socket.sendall(msg_id + msg_as_byte_arr)
         msg = self.socket.recv(926214400*2)
         return self.__parse_msg__(msg, msg_id.decode("utf-8"))
 
     def __parse_msg__(self, msg, id):
         json_string = msg
         msg_dict = json.loads(json_string)
 
         msg_received_id = msg_dict["msgID"]
         msg_received_content = json.loads(msg_dict['msgContent'])
 
         observation = msg_received_content["observation"]
         reward = msg_received_content["reward"]
         info = msg_received_content["info"]
         done = msg_received_content["done"]
 
         if msg_received_id != id[:-1]:
             print('WRONG ID', msg_received_id, id)
 
         for camera in observation['cameras']:
             camera['image'] = np.array(camera['image']).transpose((2, 1, 0))
 
         self.observation, self.reward, self.done, self.info = observation, reward, done, info
         return observation, reward, done, info
```

The start action is a list. For example, 
action = [ a1, a2, a3]

In my previous code, I use this function :
obs_next, rew, done, _ = env.step(action)  

May I ask, in Tianshou framework, as you said, if there is no need to manually add action to the environment, where can I put the argument 'action'?  How can Tianshou framework identify my action? Thanks a lot in advance.

**Comment by Trinkle23897** [comment]
>          self.action_space = gym.spaces.Discrete(n_actions)

This means your env's action is an integer within the discrete range of [0, n_actions).
This is the same as CartPole example in readme. To get the things work,
1. First get action size from env.action_space, denoted as `n_action`;
2. Define the policy network with given `n_action`. For example, the output shape is `[batch_size, n_action]` for a Q network in DQN algorithm;
3. Use this network to initialize a policy, for example, DQNPolicy; after that when we call `policy.forward(obs)`, it returns a `Batch` where action is in `batch.act`.
4. `Collector` will automatically handle the interaction between policy and environment.

So for your question, 
- if your environment's action space is a single integer in `[0, 1, 2]`, if I understand correctly, by properly initializing policy network with an algorithm that can handle discrete action space, all of the stuff should work; see the examples in [test/discrete/](https://github.com/thu-ml/tianshou/tree/master/test/discrete);
- if that is three integers, that's called MultiDiscrete action space and can always be converted to a single integer case; 
- if that is three floats, that's continuous action space and similarly can be handled by a list of RL algorithms; you can refer to Pendulum examples provided in [test/continuous/](https://github.com/thu-ml/tianshou/tree/master/test/continuous).

**Comment by mf093087** [comment]
> > ```
> >      self.action_space = gym.spaces.Discrete(n_actions)
> > ```
> 
> This means your env's action is an integer within the discrete range of [0, n_actions). This is the same as CartPole example in readme. To get the things work,
> 
> 1. First get action size from env.action_space, denoted as `n_action`;
> 2. Define the policy network with given `n_action`. For example, the output shape is `[batch_size, n_action]` for a Q network in DQN algorithm;
> 3. Use this network to initialize a policy, for example, DQNPolicy; after that when we call `policy.forward(obs)`, it returns a `Batch` where action is in `batch.act`.
> 4. `Collector` will automatically handle the interaction between policy and environment.
> 
> So for your question,
> 
> * if your environment's action space is a single integer in `[0, 1, 2]`, if I understand correctly, by properly initializing policy network with an algorithm that can handle discrete action space, all of the stuff should work; see the examples in [test/discrete/](https://github.com/thu-ml/tianshou/tree/master/test/discrete);
> * if that is three integers, that's called MultiDiscrete action space and can always be converted to a single integer case;
> * if that is three floats, that's continuous action space and similarly can be handled by a list of RL algorithms; you can refer to Pendulum examples provided in [test/continuous/](https://github.com/thu-ml/tianshou/tree/master/test/continuous).

Thanks a lot! I think now I am much more clear about this framework. I checked this example [test_dqn](https://github.com/thu-ml/tianshou/blob/40289b8b0e41c49ddf02942d688cdf2199d4919d/test/discrete/test_dqn.py). As you said, I should properly initialize policy network with an algorithm that can handle discrete action space. From my understanding, I should put the arguments 'action' in here [DQN policy](https://github.com/thu-ml/tianshou/blob/40289b8b0e41c49ddf02942d688cdf2199d4919d/test/discrete/test_dqn.py#L79), but I am still not clear how to put my arguments. My action is a list of three random floats. Could you please write a code to put this 'action' arguments? I am sorry for this kind of 'simple' question...

**Comment by Trinkle23897** [comment]
`action` size determines the neural network output shape. We use nn to init a policy.

> My action is a list of three random floats.

This is the last case I mentioned above, so the list of policies are: PG/A2C/PPO/TRPO for on-policy algorithm, and DDPG/TD3/SAC for off-policy algorithm. DQN cannot handle such a continuous action space due to its limitation.
Please refer to the Pendulum examples provided in [test/continuous/](https://github.com/thu-ml/tianshou/tree/master/test/continuous).

**Comment by mf093087** [comment]
> `action` size determines the neural network output shape. We use nn to init a policy.
> 
> > My action is a list of three random floats.
> 
> This is the last case I mentioned above, so the list of policies are: PG/A2C/PPO/TRPO for on-policy algorithm, and DDPG/TD3/SAC for off-policy algorithm. DQN cannot handle such a continuous action space due to its limitation. Please refer to the Pendulum examples provided in [test/continuous/](https://github.com/thu-ml/tianshou/tree/master/test/continuous).

Thanks a lot! I am kind of unfamiliar with reinforcement learning. As you said, action size determines the neural network output shape. But this is only size, for example, if my action is a list of three floats, then the size is 3. But I still don't use the content of the arguments. If my action is [1.5, 2.5, 3.6]. Should I change here [test_ppo](https://github.com/thu-ml/tianshou/blob/40289b8b0e41c49ddf02942d688cdf2199d4919d/test/continuous/test_ppo.py#L63)  

from
    args.max_action = env.action_space.high[0]

to 
    args.max_action = [1.5, 2.5, 3.6]?

**Comment by Trinkle23897** [comment]
No. `env.action_space.high` and `env.action_space.low` indicates the range of action space. If your action range is `[-4, -5, -2]` ~ `[4, 5, 2]`, the `args.max_action` shoule be set to `max(env.action_space.high) = 5`.

**Comment by mf093087** [comment]
> No. `env.action_space.high` and `env.action_space.low` indicates the range of action space. If your action range is `[-4, -5, -2]` ~ `[4, 5, 2]`, the `args.max_action` shoule be set to `max(env.action_space.high) = 5`.

Thanks a lot, I will have a try. To help me understand better, how about the discrete action [test/discrete/](https://github.com/thu-ml/tianshou/tree/master/test/discrete)? Where should I add the action, if my action = [1,2,3]?

**Comment by Trinkle23897** [comment]
Again, no need to manually add your action because tianshou has already written this logic inside collector about how to send action from policy to env (or vectorized env).

**Comment by mf093087** [comment]
> Again, no need to manually add your action because tianshou has already written this logic inside collector about how to send action from policy to env (or vectorized env).

Thanks a lot, I think there is a misunderstanding. 

I know that there is no need to manually add my action. But if I don't put the argument 'action' inside collector, how does it know my initial actions? For example, the initial action is the coordinates of a robot, which is a list, such as random numbers between [0,0,0] and [ 3, 3, 3]. From my understanding, the meaning of not manually adding the action is that we don't need to use 'action' as an arguments alone. There should be some places to put the 'action' together with other arguments as the precondition. I can change the arguments somewhere in the collector from the random numbers between [0,0,0] and [3,3,3] to the random numbers between [1,1,1] and [10,10,10]. What I want to know is where to change this in Tianshou framework. 

In my previous code, 
action = [0,0,0]
observation, reward, done, action = env.step(action)

I can change the action to have a different initial action easily. But how can I change it in Tianshou framework?

**Comment by Trinkle23897** [comment]
There's no need to send a random action. Instead, here's another way (if I understand correctly):

```python
class SimulateEV(gym.Env):
  def __init__(self, ...):
    ...
  def reset(self):
    # random position here
    rand_pos = np.random.randint(self.low, self.high, size=3)
    return self.__send_msg__(b"reset", pos=rand_pos)
  def __send_msg__(self, cmd, pos=None):
    ...
```

**Comment by mf093087** [comment]
> ```python
> cmd
> ```
Hi, many many thanks for the quick help! 👍 May I ask, what does here cmd mean?
  def __send_msg__(self, cmd, pos=None):

Is there any other solution which doesn't need to change the environment ?

What I am trying to use reinforcement learning to do is that I send the initial random coordinates of the robots to the simulation environment, then the robots in the simulation will receive the coordinates and move to the locations. Then the robots will execute some actions in the simulation environment, after that, the robots will send back the feedback to the agent, this can be regarded as the observation and the reward, then the agent will do optimizations based on the feedback.

From my previous code, it works, now I want to simplify it with tianshou framework and try different reinforcement learning algorithms. So if there is a solution which doesn't need to change the environment, that would be very helpful. :)

**Comment by Trinkle23897** [comment]
Let's say your original environment can initialize via `gym.make("Simulate-v0")`. The easiest way is to write a env wrapper:

```python
class EnvWrapper(gym.Wrapper):
  def __init__(self, env, low, high):
    super().__init__(env)
    self.low, self.high = low, high
  def reset(self):
    super().reset()  # original reset
    rand_pos = np.random.randint(self.low, self.high, size=3)
    return super().step(rand_pos)[0]
  def step(self, action):
    return super().step(action)

# the new environment would be
env = EnvWrapper(gym.make("Simulate-v0"), 0, 10)
```

**Comment by mf093087** [comment]
> Let's say your original environment can initialize via `gym.make("Simulate-v0")`. The easiest way is to write a env wrapper:
> 
> ```python
> class EnvWrapper(gym.Wrapper):
>   def __init__(self, env, low, high):
>     super().__init__(env)
>     self.low, self.high = low, high
>   def reset(self):
>     super().reset()  # original reset
>     rand_pos = np.random.randint(self.low, self.high, size=3)
>     return super().step(rand_pos)[0]
>   def step(self, action):
>     return super().step(action)
> 
> # the new environment would be
> env = EnvWrapper(gym.make("Simulate-v0"), 0, 10)
> ```

Thanks a lot, may I ask, if the coordinate should be between [-1000, -800, 0] and [1000, 800, 0], How should I define the actions? 

rand_pos = np.random.randint(self.low, self.high, size = 3). If I set self.low = -1000, self.high = 1000, then I think it is not so accurate, because the z coordinate is always 0.

**Comment by Trinkle23897** [comment]
```python
In [7]: np.random.randint(low=[-1000, -800, 0], high=[1001, 801, 1])
Out[7]: array([ 395, -698,    0])
```

**Comment by mf093087** [comment]
> ```python
> In [7]: np.random.randint(low=[-1000, -800, 0], high=[1001, 801, 1])
> Out[7]: array([ 395, -698,    0])
> ```

Thanks a lot, from my understanding, another solution is to change the action_space to gym.spaces.Box(low=-1000, high = 1000, shape = (3, ) dtype = np.int32)  . Then the tianshou framework will get this action automatically, do I understand right? If yes, in this case, how to define x, y, z coordinates in different range with gym.spaces.Box function?

```python
class SimulateEV(gym.Env):
     def __init__(self, img_w, img_h, n_channels, n_actions, port=PORT, step_factor=1):
         super(SimulateEV, self).__init__()
 
         self.img_w = img_w
         self.img_h = img_h
         self.num_channels = n_channels
         self.step_factor = step_factor
         self.action_space = gym.spaces.Discrete(n_actions)
         self.observation_space = gym.spaces.Box(low=0, high=500, shape=(self.num_channels, 2), dtype=np.int32)
         self.socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
         self.socket.connect(('127.0.0.1', port))
 
 
     def step(self, action):
         step = action
         msg_as_byte_arr = str.encode('step_' + ','.join([str(x) for x in step]))
         return self.__send_msg__(msg_as_byte_arr)
 
     def reset(self):
         return self.__send_msg__(b"reset")
 
     def render(self, mode='rgb_array'):
         return self.observation
  
     def __send_msg__(self, msg_as_byte_arr):
         msg_id = self.__generate_4_chars_id__()
         self.socket.sendall(msg_id + msg_as_byte_arr)
         msg = self.socket.recv(926214400*2)
         return self.__parse_msg__(msg, msg_id.decode("utf-8"))
 
     def __parse_msg__(self, msg, id):
         json_string = msg
         msg_dict = json.loads(json_string)
 
         msg_received_id = msg_dict["msgID"]
         msg_received_content = json.loads(msg_dict['msgContent'])
 
         observation = msg_received_content["observation"]
         reward = msg_received_content["reward"]
         info = msg_received_content["info"]
         done = msg_received_content["done"]
 
         if msg_received_id != id[:-1]:
             print('WRONG ID', msg_received_id, id)
 
         for camera in observation['cameras']:
             camera['image'] = np.array(camera['image']).transpose((2, 1, 0))
 
         self.observation, self.reward, self.done, self.info = observation, reward, done, info
         return observation, reward, done, info
```

**Comment by Trinkle23897** [comment]
> another solution is to

I don't think this is for the same problem because you said you need an extra step to send a random position to reset previously.

For your question, I think the ideal solution should be

```python
gym.spaces.Box(low=np.array([-1000, -800, 0]), high=np.array([1000, 800, 0]), dtype=int)
```

But in order to get a good performance, you need to do two extra things:
1. change `dtype=int` to `dtype=float`, because for algorithms to handle continuous action space, the output of policy's action is float;
2. remove the third dimension of action because there's no need to learn such a constant 0 output.

So the environment code is:

```python
class SimulateEV(gym.Env):
     def __init__(self, img_w, img_h, n_channels, n_actions, port=PORT, step_factor=1):
         super(SimulateEV, self).__init__()
 
         self.img_w = img_w
         self.img_h = img_h
         self.num_channels = n_channels
         self.step_factor = step_factor
         self.action_space = gym.spaces.Box(low=np.array([-1000, -800]), high=np.array([1000, 800]), dtype=float)
         self.observation_space = gym.spaces.Box(low=0, high=500, shape=(self.num_channels, 2), dtype=np.int32)
         self.socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
         self.socket.connect(('127.0.0.1', port))
 
 
     def step(self, action):
         step = action.astype(int)  # <-- this action has shape [2] instead of [3]
         msg_as_byte_arr = str.encode('step_' + ','.join([str(x) for x in step] + ["0"]))  # <-- adding 0 here
         return self.__send_msg__(msg_as_byte_arr)
 
     def reset(self):
         return self.__send_msg__(b"reset")
 
     def render(self, mode='rgb_array'):
         return self.observation
  
     def __send_msg__(self, msg_as_byte_arr):
         msg_id = self.__generate_4_chars_id__()
         self.socket.sendall(msg_id + msg_as_byte_arr)
         msg = self.socket.recv(926214400*2)
         return self.__parse_msg__(msg, msg_id.decode("utf-8"))
 
     def __parse_msg__(self, msg, id):
         json_string = msg
         msg_dict = json.loads(json_string)
 
         msg_received_id = msg_dict["msgID"]
         msg_received_content = json.loads(msg_dict['msgContent'])
 
         observation = msg_received_content["observation"]
         reward = msg_received_content["reward"]
         info = msg_received_content["info"]
         done = msg_received_content["done"]
 
         if msg_received_id != id[:-1]:
             print('WRONG ID', msg_received_id, id)
 
         for camera in observation['cameras']:
             camera['image'] = np.array(camera['image']).transpose((2, 1, 0))
 
         self.observation, self.reward, self.done, self.info = observation, reward, done, info
         return observation, reward, done, info
```

**Comment by mf093087** [comment]
> ```python
> step = action.astype(int)  
> ```

Many thanks for the very kind help! Could you please help me to check what is wrong here? This is my environment, I have two robots, thus I need 6 coordinates of the robots. The environment is registered with the name 'foo-v0'. 

```
import json
import random
import socket
import string
import gym_foo
import gym
import numpy as np

PORT = 1011
ID_LEN = 4


class ProcessSimulateEV(gym.Env):
    def __init__(self, img_w, img_h, n_channels, n_actions, port=PORT, step_factor=1):
        super(ProcessSimulateEV, self).__init__()

        self.img_w = img_w
        self.img_h = img_h
        self.num_channels = n_channels
        self.step_factor = step_factor
        self.action_space = gym.spaces.Box(low=np.array([-1000, -800,0,-1000, -800,0]), high=np.array([1000, 8000,0, -1000, -800,0]), dtype=float)
        self.observation_space = gym.spaces.Box(low=0, high=500, shape=(self.num_channels, 2), dtype=np.int32)
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.socket.connect(('127.0.0.1', port))


    def step(self, action):
        # You can try to play with it by adding prints or debug the Python code.
        print(action)
        step = action
        msg_as_byte_arr = str.encode('step_' + ','.join([str(x) for x in step]))
        return self.__send_msg__(msg_as_byte_arr)

    def reset(self):
        return self.__send_msg__(b"reset")

    def render(self, mode='rgb_array'):
        return self.observation

    @staticmethod
    def __generate_4_chars_id__():
        letters = string.ascii_lowercase
        word = ''.join(random.choice(letters) for i in range(ID_LEN))
        return str.encode(word + '_')

    def __send_msg__(self, msg_as_byte_arr):
        msg_id = self.__generate_4_chars_id__()
        self.socket.sendall(msg_id + msg_as_byte_arr)
        msg = self.socket.recv(926214400*2)
        return self.__parse_msg__(msg, msg_id.decode("utf-8"))

    def __parse_msg__(self, msg, id):
        json_string = msg
        msg_dict = json.loads(json_string)

        msg_received_id = msg_dict["msgID"]
        msg_received_content = json.loads(msg_dict['msgContent'])

        observation = msg_received_content["observation"]
        reward = msg_received_content["reward"]
        info = msg_received_content["info"]
        done = msg_received_content["done"]

        if msg_received_id != id[:-1]:
            print('WRONG ID', msg_received_id, id)

        for camera in observation['cameras']:
            camera['image'] = np.array(camera['image']).transpose((2, 1, 0))

        self.observation, self.reward, self.done, self.info = observation, reward, done, info
        return observation, reward, done, info

```


Below is the reinforcement learning code with Tianshou framework based on [test_ppo](https://github.com/mf093087/tianshou/blob/master/test/continuous/test_ppo.py)

```
import argparse
import os
import pprint

import gym
import gym_foo
import numpy as np
import torch
from torch.distributions import Independent, Normal
from torch.utils.tensorboard import SummaryWriter

from tianshou.data import Collector, VectorReplayBuffer
from tianshou.env import DummyVectorEnv
from tianshou.policy import PPOPolicy
from tianshou.trainer import onpolicy_trainer
from tianshou.utils import TensorboardLogger
from tianshou.utils.net.common import ActorCritic, Net
from tianshou.utils.net.continuous import ActorProb, Critic


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--task', type=str, default='foo-v0')
    parser.add_argument('--seed', type=int, default=1)
    parser.add_argument('--buffer-size', type=int, default=20000)
    parser.add_argument('--lr', type=float, default=1e-3)
    parser.add_argument('--gamma', type=float, default=0.95)
    parser.add_argument('--epoch', type=int, default=5)
    parser.add_argument('--step-per-epoch', type=int, default=150000)
    parser.add_argument('--episode-per-collect', type=int, default=16)
    parser.add_argument('--repeat-per-collect', type=int, default=2)
    parser.add_argument('--batch-size', type=int, default=128)
    parser.add_argument('--hidden-sizes', type=int, nargs='*', default=[64, 64])
    parser.add_argument('--training-num', type=int, default=16)
    parser.add_argument('--test-num', type=int, default=100)
    parser.add_argument('--logdir', type=str, default='log')
    parser.add_argument('--render', type=float, default=0.)
    parser.add_argument(
        '--device', type=str, default='cuda' if torch.cuda.is_available() else 'cpu'
    )
    # ppo special
    parser.add_argument('--vf-coef', type=float, default=0.25)
    parser.add_argument('--ent-coef', type=float, default=0.0)
    parser.add_argument('--eps-clip', type=float, default=0.2)
    parser.add_argument('--max-grad-norm', type=float, default=0.5)
    parser.add_argument('--gae-lambda', type=float, default=0.95)
    parser.add_argument('--rew-norm', type=int, default=1)
    parser.add_argument('--dual-clip', type=float, default=None)
    parser.add_argument('--value-clip', type=int, default=1)
    parser.add_argument('--norm-adv', type=int, default=1)
    parser.add_argument('--recompute-adv', type=int, default=0)
    parser.add_argument('--resume', action="store_true")
    parser.add_argument("--save-interval", type=int, default=4)
    args = parser.parse_known_args()[0]
    return args

class EnvWrapper(gym.Wrapper):
   def __init__(self, env, low, high):
     super().__init__(env)
     self.low, self.high = low, high
   def reset(self):
     super().reset()  # original reset
     rand_pos = np.random.randint(self.low, self.high, size=3)
     return super().step(rand_pos)[0]
   def step(self, action):
     return super().step(action)


def test_ppo(args=get_args()):

    env = gym.make(
        'foo-v0',
        img_w=96,
        img_h=96,
        n_channels=2,  # grayscale + depth
        n_actions=6,
        step_factor=1000,
        port=1011
    )

    #env = gym.make(args.task)
    if args.task == 'foo-v0':
        env.spec.reward_threshold = -250
    args.state_shape = env.observation_space.shape or env.observation_space.n
    args.action_shape = env.action_space.shape or env.action_space.n
    args.max_action = env.action_space.high[0]
    # you can also use tianshou.env.SubprocVectorEnv
    # train_envs = gym.make(args.task)
    train_envs = DummyVectorEnv(
        [lambda: env for _ in range(args.training_num)]
    )
    # test_envs = gym.make(args.task)
    test_envs = DummyVectorEnv(
        [lambda: env for _ in range(args.test_num)]
    )
    # seed
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    train_envs.seed(args.seed)
    test_envs.seed(args.seed)
    # model
    net = Net(args.state_shape, hidden_sizes=args.hidden_sizes, device=args.device)
    actor = ActorProb(
        net, args.action_shape, max_action=args.max_action, device=args.device
    ).to(args.device)
    critic = Critic(
        Net(args.state_shape, hidden_sizes=args.hidden_sizes, device=args.device),
        device=args.device
    ).to(args.device)
    actor_critic = ActorCritic(actor, critic)
    # orthogonal initialization
    for m in actor_critic.modules():
        if isinstance(m, torch.nn.Linear):
            torch.nn.init.orthogonal_(m.weight)
            torch.nn.init.zeros_(m.bias)
    optim = torch.optim.Adam(actor_critic.parameters(), lr=args.lr)

    # replace DiagGuassian with Independent(Normal) which is equivalent
    # pass *logits to be consistent with policy.forward
    def dist(*logits):
        return Independent(Normal(*logits), 1)

    policy = PPOPolicy(
        actor,
        critic,
        optim,
        dist,
        discount_factor=args.gamma,
        max_grad_norm=args.max_grad_norm,
        eps_clip=args.eps_clip,
        vf_coef=args.vf_coef,
        ent_coef=args.ent_coef,
        reward_normalization=args.rew_norm,
        advantage_normalization=args.norm_adv,
        recompute_advantage=args.recompute_adv,
        dual_clip=args.dual_clip,
        value_clip=args.value_clip,
        gae_lambda=args.gae_lambda,
        action_space=env.action_space
    )
    # collector
    train_collector = Collector(
        policy, train_envs, VectorReplayBuffer(args.buffer_size, len(train_envs))
    )
    test_collector = Collector(policy, test_envs)
    # log
    log_path = os.path.join(args.logdir, args.task, 'ppo')
    writer = SummaryWriter(log_path)
    logger = TensorboardLogger(writer, save_interval=args.save_interval)

    def save_fn(policy):
        torch.save(policy.state_dict(), os.path.join(log_path, 'policy.pth'))

    def stop_fn(mean_rewards):
        return mean_rewards >= env.spec.reward_threshold

    def save_checkpoint_fn(epoch, env_step, gradient_step):
        # see also: https://pytorch.org/tutorials/beginner/saving_loading_models.html
        torch.save(
            {
                'model': policy.state_dict(),
                'optim': optim.state_dict(),
            }, os.path.join(log_path, 'checkpoint.pth')
        )

    if args.resume:
        # load from existing checkpoint
        print(f"Loading agent under {log_path}")
        ckpt_path = os.path.join(log_path, 'checkpoint.pth')
        if os.path.exists(ckpt_path):
            checkpoint = torch.load(ckpt_path, map_location=args.device)
            policy.load_state_dict(checkpoint['model'])
            optim.load_state_dict(checkpoint['optim'])
            print("Successfully restore policy and optim.")
        else:
            print("Fail to restore policy and optim.")

    # trainer
    result = onpolicy_trainer(
        policy,
        train_collector,
        test_collector,
        args.epoch,
        args.step_per_epoch,
        args.repeat_per_collect,
        args.test_num,
        args.batch_size,
        episode_per_collect=args.episode_per_collect,
        stop_fn=stop_fn,
        save_fn=save_fn,
        logger=logger,
        resume_from_log=args.resume,
        save_checkpoint_fn=save_checkpoint_fn
    )
    assert stop_fn(result['best_reward'])

    if __name__ == '__main__':
        pprint.pprint(result)
        # Let's watch its performance!
        env = gym.make(args.task)
        policy.eval()
        collector = Collector(policy, env)
        result = collector.collect(n_episode=1, render=args.render)
        rews, lens = result["rews"], result["lens"]
        print(f"Final reward: {rews.mean()}, length: {lens.mean()}")


def test_ppo_resume(args=get_args()):
    args.resume = True
    test_ppo(args)


if __name__ == '__main__':
    test_ppo()


```

From my understanding, the step method in the environment will be called automatically in Tianshou framework. After I checked my simulation, I found that the message that my simulation environment receive is like this, it is not the coordinates of the robots. I don't know what is wrong with my code. 
![image](https://user-images.githubusercontent.com/67538561/153731178-0be37c89-1e79-4d46-9bd3-ab0523d66e4a.png)


In my previous code, it works. I can easily receive the right message.

```
simularCount = 0

pick_size = 2000
welding_size = 500

env = gym.make(
    'foo-v0',
    img_w=96,
    img_h=96,
    n_channels=2,  # grayscale + depth
    n_actions=6,
    step_factor=1000,
    port=1011  # 8686
)

mutation_percent_genes = 10

def fitness_func(solution, solution_idx):

    global simularCount
    observation, reward, done, info = env.step(solution)

    now = datetime.datetime.now()

    simularCount = simularCount + 1

    now = datetime.datetime.now()

    print("\n", simularCount, now.strftime("%H:%M:%S"), solution, reward)
    rewards = 1.0 / np.abs(reward)
    return rewards

sol_per_pop = 10  # population size
num_genes = 6 # number of genes
num_generations = 50

ga_instance = pygad.GA(num_generations=num_generations,  # number of generation
                       num_parents_mating=4,  # Solutions chosen from parents
                       fitness_func=fitness_func,
                       sol_per_pop=sol_per_pop,
                       num_genes=num_genes,
                       init_range_low=-pick_size,
                       init_range_high=pick_size,
                       save_solutions=True,
                       mutation_by_replacement=True,
                       mutation_type= "random",
                       crossover_type= "single_point",
                       crossover_probability = 0.5,
                       gene_space=[None,
                                   None,
                                   [0],
                                   range(-welding_size,welding_size),
                                   range(-welding_size,welding_size),
                                   [0]],
                       mutation_percent_genes=mutation_percent_genes)
```

**Comment by Trinkle23897** [comment]
What's gym_foo?

**Comment by mf093087** [comment]
> What's gym_foo?

gym_foo is the folder where I put my simulation environment. I name it by myself. My simulation environment is inside this folder

**Comment by Trinkle23897** [comment]
Could you please send that to my email trinkle23897@gmail.com? If not, we can also talk about the details via email or WeChat or Zoom. I think that would be more efficient.

**Comment by mf093087** [comment]
> Could you please send that to my email [trinkle23897@gmail.com](mailto:trinkle23897@gmail.com)? If not, we can also talk about the details via email or WeChat or Zoom. I think that would be more efficient.

Yes sure

**Comment by mf093087** [comment]
Very nice help, thanks a lot!
