### ISSUE TITLE
E   OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "E:\Anaconda3\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by mf093087** [aai-institute/tianshou#527]
When I run the test example from Tianshou framework, I always met this error. I changed already the memory in advanced system settings, but it still doesn't work. 

```python
test/discrete/test_fqf.py:None (test/discrete/test_fqf.py)
test_fqf.py:7: in <module>
    import torch
E:\Anaconda3\lib\site-packages\torch\__init__.py:124: in <module>
    raise err
E   OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "E:\Anaconda3\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
```

I am using Nvidia RTX 3070 gpu, AMD Ryzen 7 5800H with Radeon Graphics 3.20 GHz and

**Comment by mf093087** [comment]
> When I run the test example from Tianshou framework, I always met this error. I changed already the memory in advanced system settings, but it still doesn't work.
> 
> test/discrete/test_fqf.py:None (test/discrete/test_fqf.py) test_fqf.py:7: in import torch E:\Anaconda3\lib\site-packages\torch__init__.py:124: in raise err E OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "E:\Anaconda3\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
> 
> I am using Nvidia RTX 3070 gpu, AMD Ryzen 7 5800H with Radeon Graphics 3.20 GHz and

Is it because that I put my anaconda in portable drive disk not the ssd disk?

**Comment by Trinkle23897** [comment]
I'm not quite sure because, again, this is a pytorch issue instead of tianshou.

```python
# in a single file test.py
import torch
# and run it by `python3 test.py` to see the same error occurs or not
```

> Is it because that I put my anaconda in portable drive disk not the ssd disk?

I don't think so. For OS perspective there's no difference.
