### ISSUE TITLE
How to define self.observation_space when observation is a tuple?

### ISSUE THREAD

**Issue by mf093087** [aai-institute/tianshou#532]
When I want to use Tianshou framework to do reinforcement learning, I need to define self.observation_space in my environment. May I ask, if my obsertion is like this, how should I define the self.observation_space?

```python
{'cameras': [],
 'parts': [],
 'robots': [{'joints': {'accelerations': None,
                        'jerks': None,
                        'values': [-3.49720252756924e-15,
                                   -1.57079637050629,
                                   1.57079637050629,
                                   -1.28680621420685e-05,
                                   2.22044604925031e-16,
                                   -1.66533453693773e-16,
                                   -0.21001379464870884,
                                   240.44773391027763],
                        'velocities': None},
             'model': 'R1',
             'rotation_base': [0.0, 0.0, -1.5707963267948966],
             'rotation_tcp': [0.0, -1.2717066342586147e-05, 0.0],
             'translation_base': [1681.520374, -556.973504, 39.999933],
             'translation_tcp': [1681.5203638859189,
                                 -2555.338168819264,
                                 1823.9999739568048]},
            {'joints': {'accelerations': None,
                        'jerks': None,
                        'values': [8.88178419700125e-16,
                                   -1.57079637050629,
                                   1.57079637050629,
                                   0.0,
                                   0.0,
                                   8.88178419700125e-16,
                                   -0.21001379464870884,
                                   240.44773391027763],
                        'velocities': None},
             'model': 'R2',
             'rotation_base': [0.0, 0.0, -5.799999999999973e-05],
             'rotation_tcp': [-2.2340213248215286, 0.0, 1.5707389210116605],
             'translation_base': [-1421.748974, -772.608939, 50.0],
             'translation_tcp': [728.8980741349669,
                                 -772.7328246292461,
                                 1826.153837822905]}],
 'sensors': []}
```

**Comment by Trinkle23897** [comment]
We don't support Tuple obs_space because of undefined behavior of `Batch.cat` and `Batch.stack`. Instead, you can use Dict observation space in gym and modify the neural network to accept this dict-style batch observation as input. For example,

```python
obs = {"a": [4], "b": np.array([1, 2, 3])}

# in the network forward function
  def forward(self, obs, ...):
    concat_arr = to_torch(np.concatenate([obs.a, obs.b]), torch.float32)
    ...
```

Another solution is using an env wrapper to directly convert the original messy observation into a single numpy array.

**Comment by mf093087** [comment]
> We don't support Tuple obs_space because of undefined behavior of `Batch.cat` and `Batch.stack`. Instead, you can use Dict observation space in gym and modify the neural network to accept this dict-style batch observation as input. For example,
> 
> ```python
> obs = {"a": [4], "b": np.array([1, 2, 3])}
> 
> # in the network forward function
>   def forward(self, obs, ...):
>     concat_arr = to_torch(np.concatenate([obs.a, obs.b]), torch.float32)
>     ...
> ```
> 
> Another solution is using an env wrapper to directly convert the original messy observation into a single numpy array.

Thanks a lot! I will have a try. Could you please elaborate a little about how to use env wrapper?

**Comment by Trinkle23897** [comment]
```python
class EnvWrapper(gym.ObservationWrapper):
  def __init__(self, env):
    super().__init__()
    self.observation_space = gym.spaces.Box(...)

  def observation(self, obs):
    # obs is the original observation returned by original env
    new_obs = np.concatenate([obs["a"], obs["b"]])
    return new_obs

env = EnvWrapper(gym.make("your-env-id"))
```

**Comment by mf093087** [comment]
> ```python
> class EnvWrapper(gym.ObservationWrapper):
>   def __init__(self, env):
>     super().__init__()
>     self.observation_space = gym.spaces.Box(...)
> 
>   def observation(self, obs):
>     # obs is the original observation returned by original env
>     new_obs = np.concatenate([obs["a"], obs["b"]])
>     return new_obs
> 
> env = EnvWrapper(gym.make("your-env-id"))
> ```

Thanks a lot!
