### ISSUE TITLE
how to collect other information using Collector?

### ISSUE THREAD

**Issue by Zebin-Li** [aai-institute/tianshou#535]
Hello,

I want to track other information when the agent interacts with the environment for every time step. I saw that the Collector.collect returns the below keys but not includes the "info". I just wonder is there a way to modify the Collector so that I can track other information beyond the already provided keys? Thank you!
![image](https://user-images.githubusercontent.com/52910998/155602700-709d3eac-e029-4cd5-a6f5-a0eaa1c01821.png)

**Comment by Trinkle23897** [comment]
https://github.com/thu-ml/tianshou/issues/455#issuecomment-981706129

**Comment by Zebin-Li** [comment]
Thank you very much!
