### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'state'

### ISSUE THREAD

**Issue by Zebin-Li** [aai-institute/tianshou#540]
tianshou version 0.4.5 64 bit (AMD64)] win32 python 3.8
I have searched for related issues (e.g., #528, #538) but didn't find a solution

Hello,

I was trying to perform RL algorithm in a customized environment. It was supposed to select an instance from a pool, so that the state is the characterization of the pool, i.e., a 2-column matrix where each row represents an instance and each column represents the features. And the action size is the number of instances in the pool. Therefore, you can see the input_dim and output_dim are the same in `net`. I used the following code to train the policy,
```
net = ts.utils.net.common.MLP(input_dim = train_RL.shape[0], output_dim = train_RL.shape[0], hidden_sizes = [256, 128, 128])
optim = torch.optim.Adam(net.parameters(), lr=1e-3)
policy = ts.policy.RainbowPolicy(net, optim, discount_factor=0.99, estimation_step=1, target_update_freq=10)
replay_buffer = ReplayBuffer(size=500)
policy.set_eps(0.1)
    for i in trange(5):
        obs, terminal = env.reset(), False
            while not terminal:
                batch = Batch(obs=[obs], info=None)
                act = policy(batch).act[0]
```
but a type error occurred as 

>  File "C:\Users\lizeb\Box\research projects\Multiclass RAL\src\running.py", line 194, in runmanytimes
    act = policy(batch).act[0]
  File "C:\Users\lizeb\Box\research projects\Multiclass RAL\venv\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\lizeb\Box\research projects\Multiclass RAL\venv\lib\site-packages\tianshou\policy\modelfree\dqn.py", line 155, in forward
    logits, h = model(obs_, state=state, info=batch.info)
  File "C:\Users\lizeb\Box\research projects\Multiclass RAL\venv\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'state'

I printed out the `batch`, and it showed as expected:

> batch= Batch(
    obs: array([[[ 0.        , -0.5470247 ],
                 [ 0.        , -0.21920934],
                 [ 0.        ,  0.914239  ],
                 [ 0.        ,  0.83558101],
                 [ 0.        ,  1.25221329],
                 [ 0.        ,  0.86927777],
...
                 [ 0.        , -1.98332234],
                 [ 0.        , -0.07568094],
                 [ 0.        ,  1.11442044]]]),
    info: None,
)

I also ran the code in #538 and printed out the `batch`, it was the same as above, which contains an `obs` and `info`, so I am not sure why this type error occurred. Any help will be appreciated! Thank you!

**Comment by Trinkle23897** [comment]
You should change `net = ts.utils.net.common.MLP` to `net = ts.utils.net.common.Net`. MLP is the internal implementation for Net, where `Net` follows the network API definition [here](https://tianshou.readthedocs.io/en/master/tutorials/dqn.html#build-the-network).

**Comment by Zebin-Li** [comment]
Thank you very much for your quick response!
