### ISSUE TITLE
There is a logical loophole in the pg strategy regarding the acquisition of act.

### ISSUE THREAD

**Issue by 127161782** [aai-institute/tianshou#543]
-  I have marked all applicable categories:
    +  exception-raising bug
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:

  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  0.4.5 1.8.0 1.20.3 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:36:15) Clang 11.1.0 ] darwin
  ```

- When I applied ppo, I found an error:

      UnboundLocalError: local variable 'act' referenced before assignment
      https://github.com/thu-ml/tianshou/blob/master/tianshou/policy/modelfree/pg.py
line 115-121 code ,he logic is not rigorous, there are omissions:
```python
        if self._deterministic_eval and not self.training:
            if self.action_type == "discrete":
                act = logits.argmax(-1)
            elif self.action_type == "continuous":
                act = logits[0]
        else:
            act = dist.sample()
        return Batch(logits=logits, act=act, state=hidden, dist=dist)
```

- By reading the source [code,](https://github.com/thu-ml/tianshou/blob/master/tianshou/policy/base.py) ,line 71-75,I found that action_type is rarely an empty string, and the action_space of my env is of Discrete type. Other policies such as DQN, c51, etc. do not have this problem. Do you have any suggestions?
```python
  if isinstance(action_space, (Discrete, MultiDiscrete, MultiBinary)):
            self.action_type = "discrete"
  elif isinstance(action_space, Box):
            self.action_type = "continuous"```

**Comment by Trinkle23897** [comment]
Could you please provide the full training script you used (or minimal example) so that I can reproduce the error on my local side?

**Comment by 127161782** [comment]
I put the environment under the gym package and it worked successfully. The problem is solved.

**Comment by 127161782** [comment]
For 115-121, I personally think that there should be another else below the elif

**Comment by Trinkle23897** [comment]
So I guess you create a tuple action space?

**Comment by zzw1123** [comment]
Hi, I have the same problem. Do you add another else below the elif? @127161782
