### ISSUE TITLE
reward_threshold is better to be as argument for the test scripts

### ISSUE THREAD

**Issue by BFAnas** [aai-institute/tianshou#547]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
In test_cql.py there is a hardcoded part of the code to the task "Pendulum-v1":

```python
  if args.task == 'Pendulum-v1':
      env.spec.reward_threshold = -1200  # too low?
```
Better to have an argument `parser.add_argument('--reward_treshold', type=float, default=-1200)` and set it up `env.spec.reward_threshold = args.reward_threshold`

I can make a pull request for this if you agree.

**Comment by Trinkle23897** [comment]
Good suggestion, please make PR!

**Comment by BFAnas** [comment]
Done!
