### ISSUE TITLE
How do the training and test environments use random seeds?

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#554]
-  I have marked all applicable categories:
    +  exception-raising bug
    +  RL algorithm bug
    +  documentation request (i.e. "X is missing from the documentation.")
    +  new feature request
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
import tianshou, torch, numpy, sys
print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.6.post1 1.10.2+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```
How do the training and test environments use random seeds?
because args.seed==0,
The following code I think does not use random seeds, right?
```python
train_envs.seed(args.seed)
test_envs.seed(args.seed)
```
If I'm going to use a random seed, should I just comment out these two lines?

**Comment by nuance1979** [comment]
train_envs and test_envs would simply pass the random seed to its underlying env. See https://tianshou.readthedocs.io/en/master/api/tianshou.env.html for details.

**Comment by jaried** [comment]
Thanks for your answer.
