### ISSUE TITLE
Not able to reproduce DQN Atari results

### ISSUE THREAD

**Issue by vwxyzjn** [aai-institute/tianshou#556]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  >>> print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  0.4.6.post1 1.10.2+cu102 1.21.5 3.9.5 (default, Jul 19 2021, 13:27:26) 
  [GCC 10.3.0] linux
  ```

When running `python3 atari_dqn.py --task "BreakoutNoFrameskip-v4" --test-num 100` I can no longer reproduce the results presented [here[(https://github.com/thu-ml/tianshou/tree/master/examples/atari#dqn-single-run). Experiment is still running but after 4M steps the average return is about 4, and test return 80. I installed envpool which should be used for running the experiments.

![image](https://user-images.githubusercontent.com/5555347/156839268-1d4e6878-a9cc-42d9-b4da-0361874604b5.png)
![image](https://user-images.githubusercontent.com/5555347/156839294-c4791dde-6572-40d4-88e5-a5796320de25.png)

See the tracked experiment [here](https://wandb.ai/costa-huang/tianshou/runs/2b7w4yt7?workspace=user-costa-huang)

**Comment by Trinkle23897** [comment]
Have you tried `python3 atari_dqn.py --task "BreakoutNoFrameskip-v4" --n-step 1`? I think maybe it's a typo for the previous PR...
