### ISSUE TITLE
'tianshou.env.venvs' found in sys.modules after import of package 'tianshou.env'

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#560]
-  I have marked all applicable categories:
    +  exception-raising bug
    +  RL algorithm bug
    +  documentation request (i.e. "X is missing from the documentation.")
    +  new feature request
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
import tianshou, torch, numpy, sys
print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.6.post1 1.10.2+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```
I use the following code, \test\continuous\test_sac_with_il.py
Among them, env is replaced by my own env, and DummyVectorEnv is replaced by SubprocVectorEnv. When the following statement is executed, it does not move for a long time and throws a warning.
With DummyVectorEnv, this line of code is executed within 0.1 seconds.
```python
     train_envs = SubprocVectorEnv([lambda: env for _ in range(args.training_num)], wait_num=3, timeout=0.2)
```
```python
D:\Anaconda3\lib\runpy.py:127: RuntimeWarning: 'tianshou.env.venvs' found in sys.modules after import of package 'tianshou.env', but prior to execution of 'tianshou.env.venvs'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
```
1.Does this warning matter?
2.Using DummyVectorEnv can't take advantage of my cpu, but SubprocVectorEnv never executes the next sentence. How to solve it?
3.When I use DummyVector Envback ,  I encounter the assertion in D:\Anaconda3\Lib\site-packages\tianshou\data\collector.py
D:\Anaconda3\Lib\site-packages\tianshou\data\collector.py line 185:
```
assert not self.env.is_async, "Please use AsyncCollector if using async venv."
```

**Comment by Trinkle23897** [comment]
1. if `wait_num` and `timeout` are set, you need to replace `Collector` with `AsyncCollector` at current stage.
2. `lambda: env` is not the right way to initialize the vectorized environment, because it passes the same object reference to different processes, and all `env.step` will direct to the same environment.
3. I don't think that warning matters.

**Comment by jaried** [comment]
Thanks for your answer.
