### ISSUE TITLE
Combining continuous action and discrete action together

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#563]
-  I have marked all applicable categories:
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
import tianshou, torch, numpy, sys
print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.6.post1 1.10.2+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```

The action space of my environment is:
```python
self.action_space = spaces.Box(low=np.array([0, 0]), high=np.array([3, 1]))
```
The first action range of 0-3 is discrete action, where <1 represents a discrete action 0, 1<= and <2 represents another discrete action 1, 2<= and <3 represents action 2,
Since tianshou defaults to a value near 1.5 of the normal distribution, it is difficult to take the action of 0 or 3. How should I deal with it?

**Comment by Trinkle23897** [comment]
I'd like to use `space.Discrete(3)` instead of `space.Box`, and using an env wrapper to convert to the original continuous action space (there's no need to learn such a convert and may hurt the performance):
```python
class Wrapper(gym.ActionWrapper):
  def __init__(self, env):
    super().__init__(env)
    self.action_space = gym.spaces.Discrete(3)
  def action(self, act):
    # convert distrete action to continuous space
    # act in [0, 1, 2]
    return act + 0.5

env = Wrapper(gym.make(...))
```

**Comment by jaried** [comment]
The reason I do this is that actions[0] is a discrete action, and actions[1] is a continuous action, so this method is adopted.

**Comment by Trinkle23897** [comment]
Hmm... I think your proposal is the easiest way to let it work. But for performance concerns, it's better to use another `Distribution` class to produce action (also need another policy head).

**Comment by jaried** [comment]
But these two actions are closely related, and it may be a bit troublesome to use two policies.

**Comment by Trinkle23897** [comment]
I agree. It depends on the env setting.
