### ISSUE TITLE
Why is the action obtained by the step of the environment all the same value again?

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#564]
-  I have marked all applicable categories:
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
import tianshou, torch, numpy, sys
print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.6.post1 1.10.2+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```
[Pick up my question from yesterday.](https://github.com/thu-ml/tianshou/issues/561)
It's normal for me to call the environment with other code today,
Use tianshou's sac to call the environment, the actions are always [3., 1.]
The scope of actions is:
```python
self.action_space = spaces.Box(low=np.array([0, 0]), high=np.array([3, 1]))
```
I checked the observation and it was ok.

**Comment by Trinkle23897** [comment]
I need a runnable example to figure out what happens, including `MyEnv`. Feel free to send the email.

**Comment by Trinkle23897** [comment]
It seems like the observation has one large value that dominates the output of the neural network. After performing observation normalization, the result looks good.
