### ISSUE TITLE
There are something wrong in VectorReplaybuffer

### ISSUE THREAD

**Issue by ccfdfvapour** [aai-institute/tianshou#571]
I have tried to print the observation of the agent's state while training, however, when I use buffer.__get__item to print the state I got something like this, which made me feel confused.
Does somebody meet with this problem?
![image](https://user-images.githubusercontent.com/96712519/158521418-96eab782-86b2-49d7-8929-22b3d076df05.png)

**Comment by Trinkle23897** [comment]
1. Which env?
2. What does `cost` mean?
3. Could you please paste the code snippet here to demonstrate this error?
