### ISSUE TITLE
ReplayBuffer sampling invalid elements?

### ISSUE THREAD

**Issue by Kenneth-Schroeder** [aai-institute/tianshou#572]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

Hi,
I am getting confused frequently with setting ReplayBuffer parameters.

**Main question**: Suppose we run an on-policy trainer and choose a buffer size > step_per_epoch. This means there will always be unwritten elements in the buffer, as it will be cleared after each network update. Is there a mechanism in the code (I couldn't find one) that prevents sampling of those random, invalid elements?

In my experiments, I have been seeing much worse results when the buffer size wasn't set exactly to step_per_epoch.
In off-policy training, I expect similar issues until the buffer is filled up for the first time.

Best,
Kenneth

**Comment by Trinkle23897** [comment]
Old version: https://github.com/thu-ml/tianshou/blob/c248b4f87e46d8fca229f29d5cabb15211c842e9/tianshou/trainer/onpolicy.py#L168
New version: https://github.com/thu-ml/tianshou/blob/10d919052bb2a07fce9d1cf3d890a57d93209b96/tianshou/trainer/onpolicy.py#L131

For buffer.reset: https://github.com/thu-ml/tianshou/blob/10d919052bb2a07fce9d1cf3d890a57d93209b96/tianshou/data/buffer/manager.py#L52-L56
https://github.com/thu-ml/tianshou/blob/10d919052bb2a07fce9d1cf3d890a57d93209b96/tianshou/data/buffer/base.py#L102-L107

**Comment by Kenneth-Schroeder** [comment]
Thank you Trinkle,
for some reason I didn't realize there is a _size variable in the replay buffers, keeping track of the number of valid elements in the buffer, which is used for sampling.

https://github.com/thu-ml/tianshou/blob/10d919052bb2a07fce9d1cf3d890a57d93209b96/tianshou/data/buffer/base.py#L247
