### ISSUE TITLE
Make flush() optional in Tensoboard logger write() method

### ISSUE THREAD

**Issue by alexnikulkov** [aai-institute/tianshou#580]
- [X] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [X] new feature request
- [X] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [X] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
Flushing at every write creates problems in file systems which store metadata about every file append. Can we make the flushing at write optional?

**Comment by Trinkle23897** [comment]
Sure!
