### ISSUE TITLE
Application of TianShou Platform in CFD Environment

### ISSUE THREAD

**Issue by 1900360** [aai-institute/tianshou#585]
-  I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:

I need to apply a deep reinforcement learning environment in CFD and TianShou is a very good choice. But CFD runs very slowly per time step and takes a lot of time. I noticed that TianShou separates training and testing. If it is actually running, it must be trained before testing, just like Test-Train-Test. Can I train and test at the same time? Please let me know how to change it if you can, thanks!
Best,
Yan

**Comment by Trinkle23897** [comment]
Our solution is to use vectorized environment for all rl algorithms. The vectorized environment can execute multiple env.step at the same time. Check out https://tianshou.readthedocs.io/en/master/tutorials/cheatsheet.html#parallel-sampling for details.

**Comment by 1900360** [comment]
I have separated the training and testing parts, and the implemented functions can meet my requirements. This is a good reinforcement learning platform, and I hope to develop more functions in the future.
Best,
Yan
