### ISSUE TITLE
h5py import error

### ISSUE THREAD

**Issue by luckywlj** [aai-institute/tianshou#587]
Ubuntu18.02, AnacondaAnaconda3-2021.11-Linux-x86_64.sh
$conda create -n tianshou python==3.7.5
$conda activate tianshou
$conda install -c conda-forge tianshou
$python
=>import tianshou
display error information as follows
![2022-04-07 14-05-00 的屏幕截图](https://user-images.githubusercontent.com/53700751/162131358-a7ddff5a-f323-49f9-9e58-53febd51f6f0.png)

I search the problem from google but do not find the exact answer. I run : pip3 install h5py and the error still exists.
Could you tell me how to resolve the install problem?

**Comment by Trinkle23897** [comment]
#479
