### ISSUE TITLE
log_prob in SAC

### ISSUE THREAD

**Issue by Jimenius** [aai-institute/tianshou#588]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [X] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [X] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [X] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
https://github.com/thu-ml/tianshou/blob/f13e415eb0de55baca5dc0d6fae39d6a38e8bc0b/tianshou/policy/modelfree/sac.py#L131
Is it still correct to keep the `action_scale` here?

**Comment by Trinkle23897** [comment]
@ChenDRAG

**Comment by ChenDRAG** [comment]
@Jimenius 
Why do you think `action_scale` is incorrect, please? I think there is no problem in that equation.
You may notice that we haven't scaled the action in the forward function, the scaling is done later by the data collector.

**Comment by Jimenius** [comment]
@ChenDRAG 
I haven't thought it thoroughly, but, the action remap takes place out of the policy learning without gradient computation involved, so I think maybe the policy should be unaware of the action scale, especially when estimating `logprob(s',a')`?

**Comment by Jimenius** [comment]
PARL https://github.com/PaddlePaddle/PARL/blob/88e43d309278c34ca857939fe251813d4cad4b03/parl/algorithms/torch/sac.py#L81
Ray https://github.com/ray-project/ray/blob/9655851f32d68013734dd44321914b27ad8fe633/rllib/models/torch/torch_action_dist.py#L337
Stable-baselines3 https://github.com/DLR-RM/stable-baselines3/blob/254bb10c42e8f892e43af9da25aefc7c604c317c/stable_baselines3/common/distributions.py#L225

**Comment by ChenDRAG** [comment]
@Jimenius I re-checked the code, you are indeed right. It is my mistake because When sac is first implemented, action scaling wasn't a part of the action remap, and is done in the algorithm. Now that it can be considered as a black box inside the env, it shouldn't be considered in the algorithm. Started a pr to fix this.
