### ISSUE TITLE
When I train with Tianshou SAC, how can I improve GPU utilization and video memory utilization?

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#592]
-  I have marked all applicable categories:

-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.7 0.21.0 1.11.0+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```
my configuration:
CPU: Xeon E5-2680 V2 @2.8G *2, a total of 20 cores and 40 logical processors
Memory: 128G, the usage rate is about 70G
GPU1: RTX970, video memory 4G
The CPU utilization rate is relatively high, and it has reached 60%-70%. There is basically no room for improvement.
When using GPU1, the utilization rate of GPU is only 4%, and only 1.2G of video memory is used.
How can I improve the utilization of GPU and video memory?

**Comment by ChenDRAG** [comment]
One way to do this. i think, is to run multiple random seeds at the same time. It's normal that you have low GPU (memory) utilization, because network used in SAC is a rather small network. RL algorithms relies more on cpus than gpus.

**Comment by jaried** [comment]
Thanks for your answer.
