### ISSUE TITLE
Why does the parallel environment need to specify the number of seeds?

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#594]
-  I have marked all applicable categories:
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.7 0.21.0 1.11.0+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```

I have always wondered, why does Tianshou's parallel environment specify the number of seeds. 

If the seed is not specified in the environment code, what are the advantages and disadvantages of pure random?

**Comment by Trinkle23897** [comment]
We need to control the different variables to produce a deterministic experiment result. Otherwise, other people may not reproduce ours.

**Comment by jaried** [comment]
Can I train myself without specifying the number of seeds?

**Comment by Trinkle23897** [comment]
Yes of course, as long as you don't need to make your experiment reproducible.

**Comment by jaried** [comment]
Thanks for your answer.
