### ISSUE TITLE
SAC algorithm, what is the maximum batch_size?

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#597]
-  I have marked all applicable categories:
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.7 0.21.0 1.11.0+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```

My nn is [512,512,512,512], and the batch_size currently used is 512. Excuse me, what is the best batch_size to use?

**Comment by Trinkle23897** [comment]
It's hard to say. It depends.

**Comment by jaried** [comment]
Others say 32-4096 is better. I'll try 1024 first.
