### ISSUE TITLE
Exploration noise takes the action outside the [-1;1] range

### ISSUE THREAD

**Issue by alexnikulkov** [aai-institute/tianshou#601]
- [X] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [X] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [X] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [X] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
In SAC the exploration noise is added to the action (https://github.com/thu-ml/tianshou/blob/c25926dd8f5b6179f7f76486ee228982f48b4469/tianshou/policy/modelfree/ddpg.py#L179). The action before noise is in the [-1;1] range, but after we add noise to it, it can have unbounded values, I've observed anything between -10 and 10 in my runs.
Since in `map_action()` we assume that the action will be in [-1;1], we'll end up producing the actions outside the action space boundaries.
A simple solution to this would be to clip the action to [-1;1] in `exploration_noise()` method of DDPG (not sure about other algorithms)

**Comment by Trinkle23897** [comment]
That's indeed a bug. Thanks for reporting this issue!

> not sure about other algorithms

Only DDPG/TD3/SAC are affected. Others like PPO don't use this kind of noise.

**Comment by alexnikulkov** [comment]
I can push a fix. Do you like the idea of just clipping action+noise to [-1;1]?

**Comment by Trinkle23897** [comment]
Yep.

**Comment by ChenDRAG** [comment]
@Trinkle23897 @alexnikulkov 
Actually I think this is not bug. See here,
https://github.com/thu-ml/tianshou/blob/57ecebde38e40778b0ac076ed67a22d21ee040bc/tianshou/data/collector.py#L251

Before that action is finally passed to the environment. it's remapped, which includes clipping the action. As a result all actions passed to the environment are legal.

**Comment by ChenDRAG** [comment]
Plus, clip this noise in exploration module may change the actions saved in buffer. This will lead to a slightly lower final performance in Mujoco according to my experiments. The reason behind this is (maybe) that now in your dataset you have too much data with the value -1 or 1, which breaks the distribution of the data.

**Comment by alexnikulkov** [comment]
OK, the clipping is indeed applied in `map_action()`, but I think this is still problematic, for the exact reason which you mentioned above - this creates a discrepancy between the actions saved in the buffer (from which we learn the actor/critic) and the actual actions which get executed in the environment. If we save action -7 into the buffer, but action -1 was actually executed in the environment, we are misleading the critic; it will think that the reward was a result of taking action -7, not -1.

**Comment by ChenDRAG** [comment]
Yes, but I personally think this really doesn't matter.  The agent will soon learn that action -7, -6, -5, 5, 6, 7 are actually all the same and they result in the same rewards. Plus, you seldomly get an action that is so far beyond range [-1, 1]. Most of the time the action is in the range [-1.2, 1.2] or something like that.

**Comment by alexnikulkov** [comment]
With the current setup we're essentially asking the critic to learn that the value function has to be flat in the regions [-inf; -1] and [1; +inf]. This might consume some of the network's capacity. Also, it might have an unintended consequence of making the value function more flat than it should be in regions [-1;-1+eps] and [1-eps; 1] because NN is a smooth function, so it can't abruptly change from having a non-zero slope to zero slope.
Do you see any reasons not to clip before we add it to the buffer?

**Comment by ChenDRAG** [comment]
Well, I actually thought about this when `map_action()` is first introduced in Tianshou.
I've got three reasons.
First is that the Mujoco benchmark is created in this way. The results presented [here](https://github.com/thu-ml/tianshou/tree/master/examples/mujoco) shows that this at least doesn't harm the performance.
Second is that in this way, we can make offpolicy and onpolicy algorithms consistent. Because for on-policy algorithms, if you save the clipped action in the buffer, it will greatly harm the performance in my Mujoco experiments. The reason might be that on-policy algorithms relies more on the right action distribution (It needs to compute `log_prob `or something like that based on the right action taken)
Third is that this method is actually consistent with that implemented in [SB3](https://github.com/DLR-RM/stable-baselines3/blob/3c468ff5582f1c05374f674331fe8ff8e7cfc70d/stable_baselines3/common/on_policy_algorithm.py#L172).
