### ISSUE TITLE
It is recommended to keep save_fn.

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#603]
-  I have marked all applicable categories:
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.7 0.21.0 1.11.0+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```

I personally think save_fn is better than save_best_fn, and it is recommended to keep it.
```
DeprecationWarning: save_fn in trainer is marked as deprecated and will be removed in the future. Please use save_best_fn instead.
```

**Comment by Trinkle23897** [comment]
However, it will cause some kind of confusion. Thus I change this name from `save_fn` to `save_best_fn`.

**Comment by jaried** [comment]
Because what I need is what the worst training can achieve, the results of each training need to be saved. If save_fn just changes the name, it will not affect me. If the logic of saving changes, I still prefer save_fn.

**Comment by Trinkle23897** [comment]
So in this case I would prefer to use `save_checkpoint_fn` instead of `save_best_fn`.

**Comment by jaried** [comment]
That's fine too. thanks.
