### ISSUE TITLE
reproduce issue using parallel environments

### ISSUE THREAD

**Issue by abstrcode** [aai-institute/tianshou#604]
When I use single environment, I can reproduce the result. However, when I set the number of parallel environments to be greater than 1, I can not reproduce. I also manually set the seed in each parallel environment and I used a customized environment. Thanks.

**Comment by abstrcode** [comment]
The reason seems to be that we need to set train_env.seed(args.seed). But I already manually set the seed the the environment. What's the difference?

**Comment by Trinkle23897** [comment]
Which venv class do you use? How do you set the seed (it's even better if you share the related code)?

**Comment by abstrcode** [comment]
code  related to venv class:
`self.env = SubprocVectorEnv([lambda ci=ci: single_env(ci) for ci in config_list])
self.env.seed(seed)`
For the env.seed function, I just set the torch seed and random seed.

**Comment by Trinkle23897** [comment]
Do you overwrite the `seed` function in your environment implementation?

**Comment by abstrcode** [comment]
Yes, the seed function  in env is:
```python
def seed(self, seed=0):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
```

**Comment by Trinkle23897** [comment]
How about using:
```python
def seed(self, seed):
  self.rng = np.random.default_rng(seed)
```

and replace `np.random.XXX` with `self.rng.XXX` every place?

**Comment by abstrcode** [comment]
I try your suggested function. For the reproduce, the first several epochs are the same. However, they have small divergence after that and get different result. I also observe divergence for single env.

**Comment by Trinkle23897** [comment]
Is there any other place you use random number generator inside env?
