### ISSUE TITLE
Atari benchmark visualization not working in Safari

### ISSUE THREAD

**Issue by nuance1979** [aai-institute/tianshou#609]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [x] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

First of all, great work on benchmark visualization in the tutorial section! It looks really nice. However, the Atari part is not working properly when viewed in Safari Version 15.4 (17613.1.17.1.13). (Chrome is fine.) Screenshot below:

<img width="1297" alt="Screen Shot 2022-04-24 at 8 46 08 AM" src="https://user-images.githubusercontent.com/10931178/164984959-4ee4b575-4aac-4d03-bdfd-f4379db84078.png">

I also have a question for @gogoduan. How did you get the benchmark results (those json files)? From WandB? Did you need to process them further or just export from WandB?

**Comment by Trinkle23897** [comment]
> How did you get the benchmark results (those json files)? From WandB? Did you need to process them further or just export from WandB?

Exported from wandb: https://wandb.ai/tianshou/atari.benchmark

>  However, the Atari part is not working properly when viewed in Safari Version 15.4 (17613.1.17.1.13). (Chrome is fine.)

How about refreshing the whole page? My chrome was also not working at first, but after pressing shift+F5 everything looks good.

Update: It works with my safari and chrome on mac M1.

**Comment by nuance1979** [comment]
> How about refreshing the whole page? My chrome was also not working at first, but after pressing shift+F5 everything looks good.

I tried refreshing and restarting. Now the Atari benchmark is fine. However, the Mujoco part is not working. See screenshot:
<img width="1288" alt="Screen Shot 2022-04-24 at 1 38 30 PM" src="https://user-images.githubusercontent.com/10931178/164995744-bef553ac-5a65-443a-af5a-57c127b0eb5c.png">

When I chose "View source" option from the top right corner of the plot, I found the following problem:
<img width="623" alt="Screen Shot 2022-04-24 at 1 39 23 PM" src="https://user-images.githubusercontent.com/10931178/164995788-a3248a8a-f206-42d4-aa37-9ced73166371.png">

The correct url should be "/en/master/_static/js/mujoco/benchmark/Ant-v3/result.json". So I checked the source and found the bug at https://github.com/thu-ml/tianshou/blob/5eab7dc2180a2f3915943c439c173b4520bd829e/docs/_static/js/benchmark.js#L29
