### ISSUE TITLE
In a parallel environment, how to make workers use only part of the data?

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#614]
-  I have marked all applicable categories:
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.7 0.21.0 1.11.0+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```
The amount of data in the environment is too large. 
When I use a parallel environment, is there a way for a main program to read all the data and the subprograms to use only part of the data?

**Comment by Trinkle23897** [comment]
You need to use a share-memory vectorized env and write a customized share memory worker.
- init: pass the share-memory address and env_id to determine which part of memory it should use
- others: act as other workers

**Comment by jaried** [comment]
Excuse me, is there a demo?

**Comment by Trinkle23897** [comment]
Currently no...

**Comment by jaried** [comment]
However, the memory problem is not the biggest impact on me at present, the biggest bottleneck of my computer is the CPU.
