### ISSUE TITLE
How can I log more information without changing the offpolicy_trainer?

### ISSUE THREAD

**Issue by KeXue-NJU** [aai-institute/tianshou#615]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

Hi, I want to save some information from my customized env. The information is recored in the info. How can I log it without changing the offpolicy_trainer? Is there anyway to log it?

**Comment by Trinkle23897** [comment]
You can use [collector.preprocess_fn](https://tianshou.readthedocs.io/en/master/tutorials/cheatsheet.html#handle-batched-data-stream-in-collector).

**Comment by GF-Huang** [comment]
@Trinkle23897 Hello, how can I get the `global step` when I use `logger.write(..., step, ...)` in `preprocess_fn`?

**Comment by Trinkle23897** [comment]
A dirty workaround is to do sth like this:
```py
class MyProcessFn:
  def __init__(self, logger):
    self.logger = logger
  def preprocess_fn(self, ...):
    global_step = self.logger.global_step
    ...
    return Batch(...)

logger = ...
pfn = MyProcessFn(logger)
collector = Collector(..., process_fn=pfn.preprocess_fn)
trainer = Trainer(..., logger=logger)
```

**Comment by GF-Huang** [comment]
> A dirty workaround is to do sth like this:
> 
> ```python
> class MyProcessFn:
>   def __init__(self, logger):
>     self.logger = logger
>   def preprocess_fn(self, ...):
>     global_step = self.logger.global_step
>     ...
>     return Batch(...)
> 
> logger = ...
> pfn = MyProcessFn(logger)
> collector = Collector(..., process_fn=pfn.preprocess_fn)
> trainer = Trainer(..., logger=logger)
> ```

`AttributeError: 'TensorboardLogger' object has no attribute 'global_step'`

**Comment by Trinkle23897** [comment]
`global_step` -> `last_log_train_step`
