### ISSUE TITLE
Questions about MAPolicy

### ISSUE THREAD

**Issue by xihuai18** [aai-institute/tianshou#620]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

Do these 2 code blocks have the same functions?

https://github.com/thu-ml/tianshou/blob/7f23748347d6bf4aebce3931f7e57291012cd98d/tianshou/policy/multiagent/mapolicy.py#L166-L167

https://github.com/thu-ml/tianshou/blob/7f23748347d6bf4aebce3931f7e57291012cd98d/tianshou/policy/multiagent/mapolicy.py#L155-L162

**Comment by Trinkle23897** [comment]
No. L155-162 is creating a placeholder array, and L167 places the actions in the right order.
