### ISSUE TITLE
How to set the value of a certain property of envs?

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#622]
-  I have marked all applicable categories:
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.7 0.21.0 1.11.0+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```

After I generate train_envs in the following way, I need to modify a class instance attribute of each env. How can I modify it:
```
         train_envs = SubprocVectorEnv(
             [MyEnv for _ in range(args.training_num)],
             wait_num=args.training_wait_num, timeout=0.2)
```

**Comment by Trinkle23897** [comment]
See set_env_attr function for venv.

**Comment by jaried** [comment]
I saw it, thanks.
