### ISSUE TITLE
0 value in segtree causes wrong index

### ISSUE THREAD

**Issue by yffbit** [aai-institute/tianshou#625]
https://github.com/thu-ml/tianshou/blob/dd16818ce4392cd82a44a8450529450dbf759666/tianshou/data/utils/segtree.py#L123-L137

should  be `direct = lsons <= value` rather than `direct = lsons < value`?  The weight sum for left son and right son is `[0,lsons)` and `[lsons,lsons+rsons)` respectively. For example, assume segtree is `[0,1,0,1]` and `bound=2`, for `vlaue=0`, you should return `index=1`  rather than `index=0`

**Comment by Trinkle23897** [comment]
That's indeed a problem, but we have the assumption that there are no 0 for all segtree values:

https://github.com/thu-ml/tianshou/blob/dd16818ce4392cd82a44a8450529450dbf759666/tianshou/data/buffer/prio.py#L86

With this approach, we can simply ignore the issue above.

**Comment by yffbit** [comment]
The init weight of segtree is all zero. When buffer is not full, it may sample indices with zero weight.
https://github.com/thu-ml/tianshou/blob/dd16818ce4392cd82a44a8450529450dbf759666/tianshou/data/utils/segtree.py#L27
https://github.com/thu-ml/tianshou/blob/dd16818ce4392cd82a44a8450529450dbf759666/tianshou/data/buffer/prio.py#L59-L62

**Comment by Trinkle23897** [comment]
In that case, it should be `<` rather than `<=`. For example, if the segtree is `[1, 1, 0, 0]`, when indexing `value=2`, `<=` will go to 0 (index=3) but `<` will go to `1` (index=1).

**Comment by yffbit** [comment]
The output range of `np.random.rand` is `[0,1)`
![image](https://user-images.githubusercontent.com/38515904/166238575-cbc78d36-9fc7-4e74-8d16-b507d73479fd.png)

**Comment by Trinkle23897** [comment]
How about value==0?

value: [ )

- `<`: [ ), [ ), ..., [ )
- `<=`: ( ], ( ], ..., ( ]

**Comment by yffbit** [comment]
value never touch the right point of interval
https://github.com/thu-ml/tianshou/blob/dd16818ce4392cd82a44a8450529450dbf759666/tianshou/data/utils/segtree.py#L79

**Comment by Trinkle23897** [comment]
> When buffer is not full, it may sample indices with zero weight.

This is not true.

So I'm still not sure what's your point. I've already demonstrated these cases will not fail with the current code, since we have non-zero value assumption. If possible, could you please provide a minimal working code example to state your point?

**Comment by yffbit** [comment]
You are right. In the leaf of segtree, when buffer is not full, zero weight indices is always on the right, so it can't sample indices with zero weight.
My point is, if zero weight is in the first, such as `[0,1,0,1,0,1]`, (not `[1,1,1,0,0,0]`), `value=0` and `<` may return zero weight index.
