### ISSUE TITLE
Does it make sense to change to torch.set_num_threads(10)?

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#630]
-  I have marked all applicable categories:
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.7 0.21.0 1.11.0+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```
In the test related code, there is the following line:
`torch.set_num_threads(1) # we just need only one thread for NN`
Does it make sense to change to `torch.set_num_threads(10)` or higher?

**Comment by Trinkle23897** [comment]
Feel free to change that number, or even delete this line.

**Comment by jaried** [comment]
Thanks for your answer.
