### ISSUE TITLE
How does sac adjust the speed of learning?

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#631]
-  I have marked all applicable categories:
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.7 0.21.0 1.11.0+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```

How does sac adjust the speed of learning?
The default learning rate of sac is to learn once per step or? 
If I want to learning 20 times per step, how can I do it?

**Comment by Trinkle23897** [comment]
You can compare these two versions of mujoco sac:
https://github.com/thu-ml/tianshou/blob/cd481423dc4e63efda83f10213cfbe8680e71b76/examples/mujoco/mujoco_sac.py
https://github.com/thu-ml/tianshou/blob/2a7c1517382177f25095753c9b01b72819dc3ac4/examples/mujoco/mujoco_sac.py

**Comment by jaried** [comment]
Is it this parameter? 
`update_per_step=args.update_per_step`

**Comment by Trinkle23897** [comment]
yes but there's a slightly different comparing with current version: see `Trainer` at https://github.com/thu-ml/tianshou/releases/tag/v0.4.0

**Comment by jaried** [comment]
Thanks for your answer.
