### ISSUE TITLE
How to get the shape of a Dict observation space?

### ISSUE THREAD

**Issue by pepsibetter** [aai-institute/tianshou#632]
Dear Jiayi,

Related to issue #532, when the observation space is a Dict, how to get the input dimension for a network model since the code line (state_shape = env.observation_space.shape or env.observation_space.n) returns an error, thank you.

**Comment by Trinkle23897** [comment]
Feel free to modify that line of code. It's up to the user to define the network input size and what should be sent into the network.

```python
In [1]: import gym

In [2]: import gym_robotics

In [3]: e=gym.make("FetchReach-v1")

In [4]: e
Out[4]: <TimeLimit<OrderEnforcing<FetchReachEnv<FetchReach-v1>>>>

In [5]: e.observation_space
Out[5]: Dict(achieved_goal:Box(-inf, inf, (3,), float32), desired_goal:Box(-inf, inf, (3,), float32), observation:Box(-inf, inf, (10,), float32))

In [6]: e.observation_space["observation"]
Out[6]: Box(-inf, inf, (10,), float32)

In [7]: e.observation_space["observation"].shape
Out[7]: (10,)
```

**Comment by pepsibetter** [comment]
I see, thank you so much.

**Comment by pepsibetter** [comment]
Hi, Jiayi. Just out of curiosity, what will the self.observation_space defined in __init__ function of environment be like given the state {'graph': nx.Graph()}? 

According to the gym doc, it must conform to gym.Space format. So will it be a Dict like {"nodes":, "edges":, "weights":}?

Meanwhile, I've seen several customized environments which exclude self.observation_space from the init function, e.g. #362. Is it acceptable?

Thanks for your time, really appreciate it.

**Comment by Trinkle23897** [comment]
Please refer to the test script:
https://github.com/thu-ml/tianshou/blob/2a7c1517382177f25095753c9b01b72819dc3ac4/test/base/env.py#L147-L172
https://github.com/thu-ml/tianshou/blob/2a7c1517382177f25095753c9b01b72819dc3ac4/test/base/test_env.py#L211-L219

> So will it be a Dict like {"nodes":, "edges":, "weights":}?

Sure, you can do that.

> Is it acceptable?

Yes but I'd suggest using a fake observation space to avoid any potential problems.

**Comment by pepsibetter** [comment]
Much appreciated, Jiayi.
