### ISSUE TITLE
Why is the action obtained by eval outside the scope of env.action_space?

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#635]
-  I have marked all applicable categories:
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.7 0.21.0 1.11.0+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```
The sac algorithm was normal in the training mode before.

My action_space is:
`self.action_space = spaces.Box(low=np.array([0, 0]), high=np.array([5, 1]))`

The code executed is:
````
batch = Batch(obs=[self.state], info={})
action = self.agent.policy(batch).act[0]
````

The result obtained is:
`tensor([-0.4636, -0.0997]`

Why is the obtained action outside action_space?

**Comment by Trinkle23897** [comment]
You need to use `policy.map_action` to correct this to your desired action space.
https://tianshou.readthedocs.io/en/master/api/tianshou.policy.html#tianshou.policy.BasePolicy.map_action

**Comment by jaried** [comment]
1. I use the following code to get a batch without act in it:
`act = self.agent.policy.map_action(batch)`

2. I use the following code to get
````
act = self.agent.policy.map_action(act, batch)
TypeError: map_action() takes 2 positional arguments but 3 were given
````
````
act = self.agent.policy(batch).act # doesn't map to the target action range
act = self.agent.policy.map_action(act,batch)
````
3. I use the following code, the obtained act is still outside the action_space:
````
act = self.agent.policy(batch).act # doesn't map to the target action range
act = self.agent.policy.map_action(act)
````
`tensor([[-0.3993, 0.2555]], device='cuda:0', grad_fn=<TanhBackward0>)`

**Comment by Trinkle23897** [comment]
Have you tried setting `action_space`, `action_scaling` and ``action_bound_method`` in SACPolicy?

https://github.com/thu-ml/tianshou/blob/bf8f63ffc3557950303fac74c416662226696fc0/tianshou/policy/base.py#L174-L182
https://github.com/thu-ml/tianshou/blob/bf8f63ffc3557950303fac74c416662226696fc0/tianshou/policy/base.py#L65-L67

**Comment by jaried** [comment]
I have set `action_space` in SACPolicy, however, `action_scaling` and `action_bound_method` are not set during training. I tried setting `action_scaling` and `action_bound_method`.

1. When I set `action_scaling=True` in SACPolicy, set a breakpoint on the line of `base.py`, and found that the following code was not executed:
```python
  if self.action_scaling:
      assert np.min(act) >= -1.0 and np.max(act) <= 1.0, \
          "action scaling only accepts raw action range = [-1, 1]"
      low, high = self.action_space.low, self.action_space.high
      act = low + (high - low) * (act + 1.0) / 2.0 # type: ignore
```
2.When I set  `action_bound_method ='tanh'`  in SACPolicy, I got an Error
```python
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2021.2.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2021.2.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Tony/Documents/yunpan/invest/2022/quant/code/myclasses/Tq_DRLStrategy/DrlRunEval.py", line 651, in <module>
    drl = DrlRunEval()
  File "D:\Tony\Documents\yunpan\invest\2022\quant\code\myclasses\Tq_DRLStrategy\DRLFutStrategy.py", line 73, in __init__
    self.agent = Agent()
  File "D:\Tony\Documents\yunpan\invest\2022\quant\code\myclasses\Tq_DRLStrategy\SacAgent.py", line 56, in __init__
    self.build_network()
  File "D:\Tony\Documents\yunpan\invest\2022\quant\code\myclasses\Tq_DRLStrategy\SacAgent.py", line 116, in build_network
    self.policy = SACPolicy(
  File "D:\Anaconda3\lib\site-packages\tianshou\policy\modelfree\sac.py", line 69, in __init__
    super().__init__(
  File "D:\Anaconda3\lib\site-packages\tianshou\policy\modelfree\ddpg.py", line 62, in __init__
    assert action_bound_method != "tanh", "tanh mapping is not supported" \
AssertionError: tanh mapping is not supportedin policies where action is used as input of critic , becauseraw action in range (-inf, inf) will cause instability in training
python-BaseException
Backend Qt5Agg is interactive backend. Turning interactive mode on.
```

**Comment by Trinkle23897** [comment]
email?

**Comment by jaried** [comment]
I found the reason, `map_action` requires act to be `np.ndarray`, and the previous input was `tensor`, so just convert it.
```python
act = self.agent.policy(batch).act[0].cpu().detach().numpy()
action = self.agent.policy.map_action(act)
```
