### ISSUE TITLE
Join PyTorch ecosystem

### ISSUE THREAD

**Issue by nuance1979** [aai-institute/tianshou#639]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

We should join the PyTorch ecosystem for better visibility: https://pytorch.org/ecosystem/join @Trinkle23897

**Comment by Trinkle23897** [comment]
just submit

**Comment by Trinkle23897** [comment]
still no reply :(
