### ISSUE TITLE
How to create my own environment using Tianshou

### ISSUE THREAD

**Issue by noc-turne** [aai-institute/tianshou#644]
If I want to create my own environment, is it necessary to inherit gym.env?
Or I only need to create my entirely new env and realize several functions like step(), reset(), render().

**Comment by Trinkle23897** [comment]
Please see https://tianshou.readthedocs.io/en/master/tutorials/cheatsheet.html#user-defined-environment-and-different-state-representation

**Comment by noc-turne** [comment]
Thanks very much!
Wish you the best.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thu-ml/tianshou"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 晚上7:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thu-ml/tianshou] How to create my own environment using Tianshou (Issue #644)





 
Please see https://tianshou.readthedocs.io/en/master/tutorials/cheatsheet.html#user-defined-environment-and-different-state-representation

**Comment by cy1034429432** [comment]
> Please see https://tianshou.readthedocs.io/en/master/tutorials/cheatsheet.html#user-defined-environment-and-different-state-representation

This website is invalid. Can you provide another one？

**Comment by Trinkle23897** [comment]
https://tianshou.org/en/master/01_tutorials/07_cheatsheet.html#user-defined-environment-and-different-state-representation
