### ISSUE TITLE
How can trainer automatically run?

### ISSUE THREAD

**Issue by noc-turne** [aai-institute/tianshou#646]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
![image](https://user-images.githubusercontent.com/86636997/169247059-6991e9b1-b4be-4f16-b6ad-b316d08bdecb.png)
Sorry, I can't understand that how trainer automatically run without calling any function.
I read the source code of trainer and Base, but I didn't see __call__(), I hope you can help me with that.

**Comment by Trinkle23897** [comment]
It's the `run` function: https://github.com/thu-ml/tianshou/blob/277138ca5b050518aacaaea367192f910fbe666d/tianshou/trainer/base.py#L427-L443

`deque` triggers `__iter__` and `__next__` until finishing all epochs.

**Comment by noc-turne** [comment]
Sorry, but how the trainer automatically call the run function?

**Comment by Trinkle23897** [comment]
https://github.com/thu-ml/tianshou/blob/277138ca5b050518aacaaea367192f910fbe666d/tianshou/trainer/onpolicy.py#L143-L150

**Comment by noc-turne** [comment]
ok, thanks
