### ISSUE TITLE
The usage of exploration noise

### ISSUE THREAD

**Issue by Molmes** [aai-institute/tianshou#647]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

![image](https://user-images.githubusercontent.com/105957833/169631540-99004816-fee2-4d09-a70d-81c912b95284.png)
I'm confused about how exploration noise works.
What's the difference if setting exploration_noise = False

**Comment by Trinkle23897** [comment]
For DQN-family, it uses epsilon-greedy to add some noise to discrete action. For some other policies, it directly adds random noise generated by a distribution to the existing continuous action.

Setting it to False means each step there's no random noise applied to action.

**Comment by phoenixsfly** [comment]
> For DQN-family, it uses epsilon-greedy to add some noise to discrete action. For some other policies, it directly adds random noise generated by a distribution to the existing continuous action.
> 
> Setting it to False means each step there's no random noise applied to action.

I found ε-greedy exploration method be used in this code:
```python3
train_fn=lambda epoch, env_step: policy.set_eps(0.1),
test_fn=lambda epoch, env_step: policy.set_eps(0.05),
```
That means eps is fixed to 0.1 on traing, and 0.05 on testing.
However, I want to set eps a bit larger at the beginning of the training and  decaying with the training progress.
How can I do that?

**Comment by Trinkle23897** [comment]
https://github.com/thu-ml/tianshou/blob/277138ca5b050518aacaaea367192f910fbe666d/test/discrete/test_dqn.py#L118-L127

**Comment by felixcrazzolara** [comment]
I feel like it might be easier to understand the purpose of exploration noise if it wasn't set to `True` for PPO in the MuJoCo examples. If I'm not mistaken, the PPO implementation doesn't implement the function overwrite `exploration_noise` and no *exploration noise* is added even though, the argument is set to `True`. I think this is quite confusing as the deviation from the mean, i.e. the stochastic nature of PPO can also be seen as exploration noise.
