### ISSUE TITLE
Error on installing tianshou on Mac M1 chip

### ISSUE THREAD

**Issue by ngctnnnn** [aai-institute/tianshou#648]
I got an error on installing tianshou on M1 chip. Although I installed numba successfully via conda, I still got error from install numba with pip on installing tianshou.
```
clang: errorclang: : unsupported option '-fopenmp'error
      : unsupported option '-fopenmp'
      error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/ngctnnnn/miniforge3/include -fPIC -O2 -isystem /Users/ngctnnnn/miniforge3/include -arch x86_64 -arch x86_64 -I/Users/ngctnnnn/miniforge3/include/python3.9 -c numba/np/ufunc/gufunc_scheduler.cpp -o build/temp.macosx-11.0-arm64-3.9/numba/np/ufunc/gufunc_scheduler.o -fopenmp -std=c++11" failed with exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> numba
```

**Comment by Trinkle23897** [comment]
Which python version did you use? ~My M1 has py38 and just now I can successfully install `numba==0.55.1` (which is the newest) via pip install.~

I use py38 from conda.
<img width="1440" alt="截屏2022-05-23 上午7 50 52" src="https://user-images.githubusercontent.com/8189182/169813180-7d8a1c57-fef8-4693-8eec-40b518d1441c.png">

**Comment by ngctnnnn** [comment]
When I install 0.55.1 numba and re-install tianshou, there is no problem. However, when I tried to import tianshou, I still got errors.

<img width="1045" alt="Screen Shot 2022-05-24 at 14 00 13" src="https://user-images.githubusercontent.com/67086934/169968598-5ac59e9d-5648-499d-aa2c-bd7a116c431c.png">

**Comment by Trinkle23897** [comment]
This is related to h5py. Could you please do the same thing on h5py?
It's because conda builds python and pip from x86 instead of arm, and the packages you previously installed from system-provided pip are based on arm instead of x86. That's being said, the current numba is x86 but h5py is arm-based.

<img width="1033" alt="截屏2022-05-24 上午8 31 51" src="https://user-images.githubusercontent.com/8189182/170035286-86234d58-4193-449e-bdc6-d2db75a0eca1.png">

**Comment by ngctnnnn** [comment]
okay I appreciate very much for your help. I did succeed in using tianshou after installing h5py with conda.
