### ISSUE TITLE
Can we get the action probability in C51?

### ISSUE THREAD

**Issue by janeliao0105** [aai-institute/tianshou#656]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

Hi, I am playing the C51 with my custom gym environment, 
and I am curious how can we get the information on the action distribution?
Just like the visualization in the C51 paper.

**Comment by Trinkle23897** [comment]
Feel free to inherit C51Policy:
```python
class C51Visualize(C51Policy):
  def __init__(self, summary_writer, *args, **kwargs):
    super().__init__(*args, **kwargs)
    # native tensorboard SummaryWriter, not tianshou.utils.logger.TensorboardLogger
    # just to demonstrate how to customize logging process
    self.sw = summary_writer
    self.sw_cnt = 0

  # a demo for recording dist
  # https://github.com/thu-ml/tianshou/blob/6ad5b520faf6ecb526ba574bffe74d847b625690/tianshou/policy/modelfree/dqn.py#L122
  def forward(self, batch):
    result = super().forward(batch)
    # use different flags at https://tianshou.readthedocs.io/en/master/tutorials/concepts.html#states-for-policy
    if not self.training:
      self.sw.add_histogram("distribution", batch.logits, self.sw_cnt)
      self.sw_cnt += 1
    return result

writer = SummaryWriter(log_path)
writer.add_text("args", str(args))
logger = TensorboardLogger(writer)

policy = C51Visualize(writer, ...)  # add original params
...
```

**Comment by janeliao0105** [comment]
Thanks for the response!
I tried the code, but I encountered an error:
TypeError: forward() takes 2 positional arguments but 3 were given
How do I  fix this error?

**Comment by Trinkle23897** [comment]
My bad.
```diff
-    def forward(self, batch):
-      result = super().forward(batch)
+    def forward(self, batch, **kwargs):
+      result = super().forward(batch, **kwargs)
```

**Comment by janeliao0105** [comment]
Thanks for the code.
But still the same error...😓

**Comment by Trinkle23897** [comment]
Could you please paste your code here to reproduce the error?

**Comment by Trinkle23897** [comment]
Close due to no response, feel free to re-open this issue.
