### ISSUE TITLE
save_checkpoint_fn is expected to have no return value but WandbLogger use it as checkpoint_path

### ISSUE THREAD

**Issue by chengruiz** [aai-institute/tianshou#658]
https://github.com/thu-ml/tianshou/blob/f13e415eb0de55baca5dc0d6fae39d6a38e8bc0b/tianshou/utils/logger/wandb.py#L100

https://github.com/thu-ml/tianshou/blob/f13e415eb0de55baca5dc0d6fae39d6a38e8bc0b/tianshou/utils/logger/wandb.py#L112

So when I use WandbLogger and save_checkpoint_fn, I meet a Error:
ValueError: Path is not a file: None

**Comment by Trinkle23897** [comment]
Thanks for reporting this issue. I'll fix it right now.
