### ISSUE TITLE
How to print the  (watch) image of test_pistonball

### ISSUE THREAD

**Issue by ccfdfvapour** [aai-institute/tianshou#661]
I used to try to set it to true, but it didn't work...
<img width="338" alt="Snipaste_2022-06-05_16-42-45" src="https://user-images.githubusercontent.com/96712519/172042936-9201ae4e-c26b-4bed-8c98-a5eba8ab03ea.png">
<img width="695" alt="Snipaste_2022-06-05_16-43-26" src="https://user-images.githubusercontent.com/96712519/172042940-791fbae0-1d0d-4265-a4a5-610a021e9982.png">

**Comment by Trinkle23897** [comment]
@ycheng517 Could you please take a look at this issue? Thanks in advance!

**Comment by ycheng517** [comment]
@Trinkle23897 sure I can take a look sometime this week.
