### ISSUE TITLE
np.Generator has no attribute 'randint'

### ISSUE THREAD

**Issue by taigaoma1997** [aai-institute/tianshou#662]
I was running the Atari examples using the PPO algorithm, and it gives me an error that says 
AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'
![WeChat Image_20220607114702](https://user-images.githubusercontent.com/78004072/172424343-be1cab65-d8f0-40a2-8479-87e1a3e87881.png)

**Comment by nuance1979** [comment]
What is your numpy version? Try upgrade it to a higher version.

**Comment by taigaoma1997** [comment]
> What is your numpy version? Try upgrade it to a higher version.

Just upgrade it and it works, thanks!

**Comment by Trinkle23897** [comment]
https://github.com/DLR-RM/stable-baselines3/issues/875
