### ISSUE TITLE
How to run multiple seeds?

### ISSUE THREAD

**Issue by ezhang7423** [aai-institute/tianshou#668]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  0.4.8 0.21.0 1.10.2 1.21.5 3.7.13 (default, Mar 29 2022, 02:18:16)
  [GCC 7.5.0] linux
  ```

**Comment by Trinkle23897** [comment]
Pass a list of seed:
```python
# if len(venv) == 5, for example
venv.seed(seed=[1, 3, 5, 7, 9])
```
