### ISSUE TITLE
Does tianshou support multi-agent parallel env besides pettingzoo aec env?

### ISSUE THREAD

**Issue by ZiyiLiubird** [aai-institute/tianshou#671]
In most multi-agent scenarios, e.g., sc2, dota2, agents should execute actions simultaneously instead of step by step. So the parallel environment where the step function receives actions of all ready agents is a much more natural choice rather than the pettingzoo aec env. I hope that tianshou can support the two paradigms so we can custom multi-agent environments and algorithms more flexible.

**Comment by Trinkle23897** [comment]
See https://tianshou.readthedocs.io/en/master/tutorials/cheatsheet.html#multi-agent-reinforcement-learning
It's quite welcome if you'd like to contribute such an example!

**Comment by maayanorner** [comment]
> See https://tianshou.readthedocs.io/en/master/tutorials/cheatsheet.html#multi-agent-reinforcement-learning It's quite welcome if you'd like to contribute such an example!

Just to make sure I understand it correctly:

"For simultaneous move, the solution is simple: we can just add a num_agent dimension to state, action, and reward. Nothing else is going to change." 

Does it mean (assuming n agents) that I should return (n X obs tensor, n X mask), n X rewards vector, and as long as I use MultiAgentPolicyManager information between observations will not be shared (important for imperfect information games)? It's not quite clear what it does behind the scenes and what input it expects from the description.

Many thanks!

**Comment by Trinkle23897** [comment]
Yes but you are free to not use MAPM. This division can be done either in MAPM or in your customized network.
