### ISSUE TITLE
Any equivalent function similar to SB3 model.predict(observation) or rllib compute_action(observation) to get action?

### ISSUE THREAD

**Issue by adiyaDalat** [aai-institute/tianshou#672]
- [v ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [v ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates

To test model in other lib:
  ```python
# SB3
action, state = model.predict(observation=obs)

# rllib
action = model.compute_single_action(obs)

  ```
I did not find equivalent method in tianshou. Could you please give a hint on that?  Thanks :)

**Comment by Trinkle23897** [comment]
`action = policy(Batch(obs=obs)).act`

**Comment by adiyaDalat** [comment]
Took this line to calculate action but got error bellow:
`IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
`
from which the observation was a 1D array.

**Comment by Trinkle23897** [comment]
`action = policy(Batch(obs=np.array([obs]))).act[0]`

**Comment by adiyaDalat** [comment]
Got it, thanks! 

Since this is a pretty important/frequent feature when testing model, I suggest it could be shown more clearly in the doc.

And to be honest for beginners on RL, Tianshou has so many hyper parameters to define in the config like MLP nets. 

I guess it will be much easier if more configs were defined by default like SB3. This would help more people using Tianshou.

Great work btw!

**Comment by ashercn97** [comment]
@Trinkle23897 Sorry if this is stupid but I am new to tianshou and what is the batch thing supposed to be? I am trying to render my model doing something in google colab and the thing i found to do it needs me to do like a single step just like this quesiton was talking about, but I dont know what the batch is. Sorry if this is dumb!!

**Comment by Trinkle23897** [comment]
https://github.com/thu-ml/tianshou/issues/672#issuecomment-1166559988 could you try this? Batch is an internal data structure used by tianshou, the code is under [`data/batch.py`](https://github.com/thu-ml/tianshou/blob/master/tianshou/data/batch.py)

**Comment by ashercn97** [comment]
Oh! Sorry im v new to this. Tysm!
