### ISSUE TITLE
Why is the absolute value of the sac reward getting smaller and smaller in the training mode?

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#673]
-  I have marked all applicable categories:
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.8 0.21.0 1.11.0+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
```

As shown in the figure, after 17 hours of sac training, there are few cases where the reward is greater than 0, but the cases where the absolute value is close to 0 and the negative value are relatively large.

When I use the test mode, the reward is also more negative and less positive.

![738e0c7aa911a29b952cb4688eef59a](https://user-images.githubusercontent.com/26672425/175795004-9d3c68fe-671b-448d-a53f-6d359844825a.png)
![4d7a239811d1acb0d847eff6d85b9ec](https://user-images.githubusercontent.com/26672425/175795005-27093224-a796-4967-ae5e-7a1dc203c105.png)

**Comment by Trinkle23897** [comment]
Maybe the agent went to the local minimum. Try other seeds or other algorithms may help.

**Comment by jaried** [comment]
Tianshou's sac algorithm is not Automating Entropy Adjustment/ Automating Temperature Parameter alpha, right?

**Comment by Trinkle23897** [comment]
You can change the config to use w/o auto alpha.

**Comment by jaried** [comment]
Is it this one?
```
    parser.add_argument('--auto-alpha', type=int, default=1)
```

**Comment by Trinkle23897** [comment]
https://github.com/thu-ml/tianshou/blob/43792bf5ab7c68dcc72d5a004c4e68d1dc43229c/tianshou/policy/modelfree/sac.py#L85

**Comment by jaried** [comment]
```python
isinstance(alpha, tuple)
True
```

**Comment by jaried** [comment]
Maybe I'm not training enough steps? Five million steps are now trained.

![1656382045371](https://user-images.githubusercontent.com/26672425/176075458-72ab57b9-e13a-483d-91c4-dca9485ce02a.png)

**Comment by Trinkle23897** [comment]
Idk... it depends on your env.

**Comment by jaried** [comment]
My env has 180k timescales and observation has 175 dimensions.

**Comment by jaried** [comment]
I will continue to train to see if the results will improve.

**Comment by jaried** [comment]
I suspect it is the transaction commission issue, because the commission is included in the current step, which makes the agent not dare to place an order easily.
I have tried PPO, and PPO will not trade to a certain extent after training.

**Comment by jaried** [comment]
The problem is on my env. I calculated the transaction slippage, and the slippage setting is too large. I set the slippage to negative reward, and the negative reward for a single step is too large, which makes the agent not dare to place an order easily. I canceled the slippage first, and then tried to train again.

**Comment by jaried** [comment]
After I reduced the transaction slippage setting to 40% of the original, I can clearly see the reward is greatly improved.

![1656557799758](https://user-images.githubusercontent.com/26672425/176583072-af7a3e6c-9913-4558-8b68-def5e30b22a3.png)

**Comment by jaried** [comment]
> Maybe the agent went to the local minimum. Try other seeds or other algorithms may help.

I feel that the sac algorithm is still not suitable for my needs. 

When opening a futures position, due to the calculation of commissions and slippage, the penalty for a single step is too large. After training for a long time, even if there is a chance, the agent sometimes still dare not open a position.

Please, what other algorithm do you recommend?

**Comment by Trinkle23897** [comment]
PPO

**Comment by jaried** [comment]
Thanks, I'm now trying to spread the cost over each step of the day, and then I'll try PPO.
