### ISSUE TITLE
DeprecationWarning occurred when importing tianshou 0.4.8 in python 3.10

### ISSUE THREAD

**Issue by iquhsek** [aai-institute/tianshou#674]
I installed tianshou in a python 3.10 conda environment on macOS. It reported "DeprecationWarning" when I imported tianshou module.

Python 3.10.4 (main, Mar 31 2022, 03:38:35) [Clang 12.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tianshou
/Users/aronqi/miniconda3/envs/singlerl/lib/python3.10/site-packages/torch/utils/tensorboard/__init__.py:4: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if not hasattr(tensorboard, '__version__') or LooseVersion(tensorboard.__version__) < LooseVersion('1.15'):
>>> tianshou.__version__
'0.4.8'

**Comment by Trinkle23897** [comment]
It doesn't matter. It's because of the newest `setuptools` package.

**Comment by GF-Huang** [comment]
Same issue in Python 3.9.13.

![image](https://user-images.githubusercontent.com/4510984/179327246-7aa207db-0ed6-4dc8-940e-3074a23584ea.png)
