### ISSUE TITLE
How to set customed stop_fn?

### ISSUE THREAD

**Issue by c4cld** [aai-institute/tianshou#675]
Currently, stop_fn determines whether early stops training process or not depends on whether mean_rewards is larger than reward_threshold or not.  I want to set a new criteria: If the standard errors of test result in five consecutive epoches are all smaller than a threshold, then stop_fn stops training process.  However, I don't know how to input the standard errors in five consecutive epoches to stop_fn. Could you give me some hints?

**Comment by c4cld** [comment]
And another question is: how to save the best checkpoint of training process? In some training processes, I encountered performance degradtion. So the best checkpoint is not the last checkpoint. I want to set a customed save_best_fn. But I don't know how to input mean rewards of previous checkpoints to the customed save_best_fn. Could you give me some hints? Thanks in advance ^_^

**Comment by Trinkle23897** [comment]
> I don't know how to input the standard errors in five consecutive epochs to stop_fn.
> how to save the best checkpoint of training process?

This example borrows from https://github.com/thu-ml/tianshou/blob/master/test/continuous/test_ppo.py

```python
    # trainer
    trainer = OnpolicyTrainer(
        policy,
        train_collector,
        test_collector,
        ...
    )

    stds = []
    for epoch, epoch_stat, info in trainer:
        print(f"Epoch: {epoch}")
        stds.append(epoch_stat["test_reward_std"] < threshold)
        if len(stds) > 5:
            stds.pop(0)
        if all(stds):
            break
        if your_customized_save_fn(epoch, epoch_stat, info):
            torch.save(policy.state_dict(), path)
```

**Comment by c4cld** [comment]
Thanks for your selfless help  ^_^
