### ISSUE TITLE
TypeError: len() of unsized object

### ISSUE THREAD

**Issue by yangbo19** [aai-institute/tianshou#677]
![1656431070385](https://user-images.githubusercontent.com/95022180/176222894-4b06aa2c-7c1b-4db5-8fd4-c70f448f7b56.png)

**Comment by Trinkle23897** [comment]
Could you please describe your environment's observation and action space? I guess you haven't inherited `gym.Env` so that the action is not in batch-style, i.e., a single integer.

**Comment by yangbo19** [comment]
![1656432007045](https://user-images.githubusercontent.com/95022180/176226300-454d6f25-0559-4621-9d85-053e60f2b009.png)
My environment's sbservation is a class,which concludes a graph.

**Comment by yangbo19** [comment]
![1656432352862](https://user-images.githubusercontent.com/95022180/176227573-248d3b62-9834-413a-90fb-d8286f7c8321.png)
Here is my graph

**Comment by Trinkle23897** [comment]
Could you please add a `print(action.shape, action)` before L246 in `/home/yangbo/anaconda3/envs/pytorch/lib/python3.9/site-packages/tianshou/env/venvs.py` and paste the result?

**Comment by yangbo19** [comment]
![1656471241367](https://user-images.githubusercontent.com/95022180/176341203-53cb4e7c-977c-46a7-9afa-cff3b3aa8ade.png)
Is it enough?

**Comment by yangbo19** [comment]
> Could you please add a `print(action.shape, action)` before L246 in `/home/yangbo/anaconda3/envs/pytorch/lib/python3.9/site-packages/tianshou/env/venvs.py` and paste the result?

Thank you for your reply.I have solved my question.Wish tishou well in future.
