### ISSUE TITLE
TypeError: learn() missing 2 required positional arguments: 'batch_size' and 'repeat'

### ISSUE THREAD

**Issue by yangbo19** [aai-institute/tianshou#678]
![1656556958678](https://user-images.githubusercontent.com/95022180/176581988-fdda9cc3-0e0b-4e1c-8d3a-24d2f5e6e336.png)
Thank you for your help

**Comment by yangbo19** [comment]
I also have a question.My state space is a class that I defined.So my network will get an obs which is numpy.I don't want my network get a batch of data.I hope that the obs is one data,such as len(obs) is one.How can I achieve this?

**Comment by Trinkle23897** [comment]
Could you please paste the code of agent training? Thanks!

**Comment by yangbo19** [comment]
def test_sac():
    env = sps.SpSearch(20, total_step=2000)
    # args.max_action = env.action_space.high[0]
    # train_envs = gym.make(args.task)
    env_fns = [lambda x=i: sps.SpSearch(20, total_step=2000) for i in [2, 3, 4, 5]]
    train_envs = SubprocVectorEnv(env_fns, wait_num=1)
    # test_envs = gym.make(args.task)
    test_envs = SubprocVectorEnv(
        [lambda: sps.SpSearch(20, total_step=2000, i=i) for i in range(1)]
    )
    # seed
    # model
    net = Net().cuda()
    actor = Actor(net).cuda()
    critic = Critic(net).cuda()
    optim = torch.optim.Adam(
        list(actor.parameters()) + list(critic.parameters()), lr=0.00005
    )
    dist = torch.distributions.Categorical
    policy = PPOPolicy(
        actor,
        critic,
        optim,
        dist,
    )
    # collector
    train_collector = AsyncCollector(policy, train_envs, VectorReplayBuffer(1024, 10))
    test_collector = Collector(policy, test_envs)
    # train_collector.collect(n_step=args.buffer_size)
    # log

    def save_fn(policy):
        torch.save(actor.state_dict(),
                   "../../runs/ts_state/input9WL_"  + "_" + "_" + "MCNC" + ".pt")
    def stop_fn(x):
        return False
        # return x >= env.spec.reward_threshold

    writer = SummaryWriter('log/dqn')
    logger = TensorboardLogger(writer)
    # trainer
    result = offpolicy_trainer(
        policy,
        train_collector,
        test_collector,
        1,
        2,
        10,
        1,
        10,
        stop_fn=stop_fn,
        save_fn=save_fn,
        logger=logger,
    )
    train_collector.close()
    test_collector.close()

**Comment by yangbo19** [comment]
![c7fe8e1a6781c992bac3b10c2ed20e9](https://user-images.githubusercontent.com/95022180/176590387-2ae67176-c652-4223-b195-05857fce997e.png)
![b7cb606581456aa729fbe6249681bac](https://user-images.githubusercontent.com/95022180/176590404-b289852c-4011-4cbf-b521-5d85ee4b70c0.png)

**Comment by Trinkle23897** [comment]
PPO is an on-policy algorithm, SAC is an off-policy algorithm. You should use `onpolicy_trainer` for PPO and `offpolicy_trainer` for SAC.

**Comment by Trinkle23897** [comment]
> So my network will get an obs which is numpy.I don't want my network get a batch of data.I hope that the obs is one data,such as len(obs) is one.How can I achieve this?

There are two solutions:
- extract all data from your class to construct a `Batch`, i.e., `Batch(obs=xxx, another_data=xxx)`;
- use `np.array(..., dtype=object)`, see https://tianshou.readthedocs.io/en/master/tutorials/cheatsheet.html#user-defined-environment-and-different-state-representation
<img width="1058" alt="截屏2022-06-30 上午10 35 22" src="https://user-images.githubusercontent.com/8189182/176741571-11d5d241-bbf7-4759-9e6a-b8056c234549.png">

**Comment by yangbo19** [comment]
Thanks for your reply. My obs is a class, so my network will get a numpy when I use parallel environment. I showed my solution below:
![1656643396145](https://user-images.githubusercontent.com/95022180/176813150-72a2e3a8-2a01-44e4-bbd2-3f5520523eb4.png)
Do you have any good ideas for me? My obs is a class that includes a class.
Another question is, my other work's action space is complicated, which is a collection of actions of varying lengths. Do you have any suggestions for me?
Thank you very much!!

**Comment by Trinkle23897** [comment]
> Do you have any good ideas for me? My obs is a class that includes a class.

Once you ensure the `obs` is an numpy array with dtype=object, that should work.

> which is a collection of actions of varying lengths

For this scenario, I'd recommend using the maximum length for all specific kinds of actions. For example:
```python
return Batch(act={
  "act_a": [len_a, *act_a, 0, ..., 0],  # where len(act_a) == maximum length of act_a + 1
  "act_b": [len_b, *act_b, 0, ..., 0],  # same as above
  "xxx": ...,
})
```

Here, different `forward` function's result should have same `len(act_a)` and same `len(act_b)`, but there's no need to ensure `len(act_a) == len(act_b)`.

**Comment by yangbo19** [comment]
Thank you very much. Hope you are well every day！

**Comment by yangbo19** [comment]
I also want to achieve a function. It may be like A2C. I know how to achieve multiple env. It can be achieved by SubprocVectorEnv. But it uses the same network. It will pass a batch of state to network. I hope that I can use multiple network. Or rather, I hope that the number of processes is M*N. M is the number of env and the N is the number of network. I wish that an agent can interact with multiple env and I have multiple agents. The network can use multiprocessing and pipe for concurrent execution, How can I achieve this by using tianshou?
Thank you very much!

**Comment by Trinkle23897** [comment]
Do you mean every timestep you randomly pick a network to generate action from observation?

**Comment by yangbo19** [comment]
> Do you mean every timestep you randomly pick a network to generate action from observation?

Every timestep I want to pick many networks to generate action. I hope the networks to be parallel. If a network represents an agent, the ultimate goal is that many agents can work together.Thank you for your reply.

**Comment by Trinkle23897** [comment]
> I hope the networks to be parallel. If a network represents an agent, the ultimate goal is that many agents can work together.

It cannot be parallelized unless if you use the same network with a different input format such as `(obs, agent_id)`. `agent_id` will transform into different embedding, thus make different actions. In that way you can parallel all network forward process.

**Comment by yangbo19** [comment]
Thank you very much.Tianshuo is really good.
