### ISSUE TITLE
Example Code/Tutorial for Continuous Action Space?

### ISSUE THREAD

**Issue by yanmiao2** [aai-institute/tianshou#685]
Hi developers,

Thanks for the great work, I am very new to Tianshou and RL. Your tutorials are very detailed and helpful; however, I'm wondering **whether you can provide a simple example on continuous action spaces?**

I'm trying to develop a continuous action_space for a customized game I created.  I defined my own `cutomized_env(gym.Env)` with customized action spaces and step(), reset().

```
net = Net(12, 3, hidden_sizes=[16], activation=[torch.nn.ReLU], device=device)
actor = Actor(net, 3, device=device).to(device)
critic = Critic(net, device=device).to(device)
actor_critic = ActorCritic(actor, critic)

# optimizer of the actor and the critic
optim = torch.optim.Adam(actor_critic.parameters(), lr=0.0003)
dist = torch.distributions.Normal
policy = PPOPolicy(
                actor, critic, optim, dist, 
                action_space= spaces.Box(
                    np.array([-1, 0, 0]).astype(np.float32),
                    np.array([+1, +1, +1]).astype(np.float32),
                )  # control_A: -1 to 1, control_B: 0 to 1, control_C: 0 to 1
            )

train_collector = Collector(policy, train_envs, ReplayBuffer(1000))

result = onpolicy_trainer(
    policy,
    train_collector,
    None,
    ...
)
```

The above is the training code, but I kept running into the error message of `TypeError: __init__() missing 1 required positional argument: 'scale'` for the Normal Distribution, any ideas on how to fix it?

**Comment by Trinkle23897** [comment]
Do you mean https://github.com/thu-ml/tianshou/blob/master/test/continuous/test_ppo.py?
All files under `test/` and `examples/` are runnable scripts. Feel free to explore them.

**Comment by yanmiao2** [comment]
That works very well, thanks!

Can you also give some hint/samples on how to visualize the test results? (E.g. I just want to see the visualization result of one test run after training is done. )

I tried using the test_collector, but it seems like an overkill since I just want one run and the collector doesn't have the visualization rendering effect.

**Comment by Trinkle23897** [comment]
Use `render` argument: `--render 0.03`. This is demonstrated in `README.md`.

**Comment by yanmiao2** [comment]
Thanks for the reply! I have one more question regarding how to use the learned policy/model with this example https://github.com/thu-ml/tianshou/blob/master/test/continuous/test_ppo.py. 

Let's say I finished training and save the trained model+policy in `f_model.pth`. Now I have a tensor `A` representing the state(observation), how should I pass that tensor A to the trained model so that I can get corresponding action?

Since the way the above example has is wrapping everything in the test collector, but I only want to know one output(action) given one input(state) using the trained policy/model.

**Comment by Trinkle23897** [comment]
https://github.com/thu-ml/tianshou/issues/672#issuecomment-1166559988
