### ISSUE TITLE
Bug in buffer/base.py

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#687]
-  I have marked all applicable categories:
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
import tianshou, gym, torch, numpy, sys
print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.9 0.24.1 1.11.0+cu113 1.20.1 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)] win32
```
https://github.com/thu-ml/tianshou/blob/master/tianshou/data/buffer/base.py#L89
It should be:
```python
def save_hdf5(self, path: str, compression: Optional[bool] = None) -> None:
```

**Comment by nuance1979** [comment]
I don't think so. See https://docs.h5py.org/en/stable/high/dataset.html#dataset-compression .

**Comment by jaried** [comment]
Hmm, my mistake.
