### ISSUE TITLE
Can the buffer change its size when there is data?

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#690]
-  I have marked all applicable categories:
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
import tianshou, gym, torch, numpy, sys
print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.9 0.24.1 1.11.0+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
```
I created the buffer as follows:
```python
buffer = VectorReplayBuffer(args.buffer_size, len(train_envs))
```
After I read the buffer from the hdf5 file, can I still modify the size of the buffer without affecting the data in the buffer?
```python
buffer = buffer.load_hdf5(buffer_save_file)
```

**Comment by Trinkle23897** [comment]
`load_hdf5` will create a new buffer. The original buffer created in the first line will have 0 ref count and will be discarded.

If you want to merge two buffers together, it's better to use `buffer.update` function to do so.

**Comment by jaried** [comment]
The `VectorReplayBuffer` class inherits the `ReplayBufferManager` class:
https://github.com/thu-ml/tianshou/blob/65054847ef6b238fee20d29a669f923370c19da1/tianshou/data/buffer/vecbuf.py#L13

The `ReplayBufferManager` class rewrites the `update` method and `raise NotImplementedError` directly
https://github.com/thu-ml/tianshou/blob/65054847ef6b238fee20d29a669f923370c19da1/tianshou/data/buffer/manager.py#L98-L100

So, how do I read the buffer?

**Comment by Trinkle23897** [comment]
Not sure what are your requirements.

- ReplayBuffer <- ReplayBuffer: that works
- VectorReplayBuffer <- ReplayBuffer: Since the underlying storage is [ env1 | env2 | ... | envN ], it's not possible to determine what's the suitable way to put data from ReplayBuffer into VectorReplayBuffer (i.e., which env it belongs to?).

I'd recommend using this way to make a workaround:

```python
buf = ReplayBuffer.load_hdf5(buffer_save_file)
for subbuf in vecbuf.buffers:
  buf.update(subbuf)
```

Or if you want `VectorReplayBuffer <- VectorReplayBuffer`:

```python
buf = VectorReplayBuffer.load_hdf5(buffer_save_file)

for buf_id, source in enumerate(buf.buffers):  # move data from buf to (old) vecbuf
  data, idx = source.sample(0)  # get all data
  vecbuf.add(data, buffer_ids=np.full(shape=len(idx), fill_value=buf_id))
```

**Comment by jaried** [comment]
> Or if you want `VectorReplayBuffer <- VectorReplayBuffer`:
> 
> ```python
> buf = VectorReplayBuffer.load_hdf5(buffer_save_file)
> 
> for buf_id, source in enumerate(buf.buffers):  # move data from buf to (old) vecbuf
>   data, idx = source.sample(0)  # get all data
>   vecbuf.add(data, buffer_ids=np.full(shape=len(idx), fill_value=buf_id))
> ```

Yes this is what I want and it works fine.
