### ISSUE TITLE
'str' object has no attribute 'ndim' when trying to use PPO instead of DQN in the tic-tac-toe example 

### ISSUE THREAD

**Issue by szucsaaron2** [aai-institute/tianshou#692]
- [X] I have marked all applicable categories:
    + [X] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [X] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [X] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [X] I have mentioned version numbers, operating system and environment, where applicable:
```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  0.4.9 0.24.1 1.12.0 1.22.3 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 06:57:19) [MSC v.1929 64 bit (AMD64)] win32

Using Win 11
```

Hey!

First of all thanks for the amazing library!
I wanted to use PPO algorithm instead of DQN for this example: https://tianshou.readthedocs.io/en/master/tutorials/tictactoe.html

The full code is here: [test_ppo.zip](https://github.com/thu-ml/tianshou/files/9092790/test_ppo.zip)

Basically what I changed are the imports: 
I added
```python
from tianshou.utils.net.common import Net, ActorCritic
from tianshou.utils.net.discrete import Actor, Critic
from tianshou.trainer import offpolicy_trainer, onpolicy_trainer
```

In the get_agents() function, I tried to replicate the model based on Tianshou\test\discrete\test_ppo
Finally, in the train_agent() function I have changed the offpolicy_trainer to onpolicy_trainer
I also change the parser information by adding
```python
    ppo special
    parser.add_argument('--vf-coef', type=float, default=0.5)
    parser.add_argument('--ent-coef', type=float, default=0.0)
    parser.add_argument('--eps-clip', type=float, default=0.2)
    parser.add_argument('--max-grad-norm', type=float, default=0.5)
    parser.add_argument('--gae-lambda', type=float, default=0.95)
    parser.add_argument('--rew-norm', type=int, default=0)
    parser.add_argument('--norm-adv', type=int, default=0)
    parser.add_argument('--recompute-adv', type=int, default=0)
    parser.add_argument('--dual-clip', type=float, default=None)
    parser.add_argument('--value-clip', type=int, default=0)
```

When I ran the code, I kept on getting AttributeError: 'str' object has no attribute 'ndim'

I tried solving this error by myself, and what I did was modified the Tianshou\tianshou\data\batch.py file, by adding 
`print('OBJECT', obj)` to line 678.
Therefore it looks like this:

```python
for obj in self.__dict__.values():
            print('OBJECT', obj)
            if isinstance(obj, Batch) and obj.is_empty(recurse=True):
```

The last few lines of the output look as follows:

```py
OBJECT [[ True  True  True  True False  True  True  True  True]
 [ True  True  True  True  True  True  True  True False]
 [ True  True  True False  True  True  True  True  True]
 [ True False  True  True  True  True  True  True  True]
 [ True  True  True False  True  True  True  True  True]
 [ True False  True  True  True  True  True  True  True]
 [False  True  True  True  True  True  True  True  True]
 [ True  True False  True  True  True  True  True  True]
 [ True  True False  True  True  True  True  True  True]
 [False  True  True  True  True  True  True  True  True]]
OBJECT ['player_2' 'player_2' 'player_2' 'player_2' 'player_2' 'player_2'
 'player_2' 'player_2' 'player_2' 'player_2']
OBJECT [[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 1]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]
OBJECT [ True  True  True  True False  True  True  True  True]
OBJECT player_2
```

I also compared this to the DQN model, and the difference is on the last line:

`OBJECT ['player_2']`

In DQN the 'player_2' variable is in a list, and not just sitting there as str :)

Could you please help me with what could be wrong here?
Thank you for your work and help!

Best regards,
szucsaaron2

**Comment by Trinkle23897** [comment]
So it's because the current `PPOPolicy.forward` function only supports the case when `obs` is an array or tensor. For tic-tac-toe, it has mask paired with observation. The solution is to modify the forward function in PPO accordingly: https://github.com/thu-ml/tianshou/issues/542#issuecomment-1059986961

**Comment by szucsaaron2** [comment]
Could you please help me with how to do that? 
I have been trying for a few hours, but I always get an error and I am afraid, I might break something or get a "working" script that doesn't have any errors, but doesn't work as intended.
First I tried implementing it exactly as it is in https://github.com/thu-ml/tianshou/issues/542#issuecomment-1059986961 for the pg policy, as PPO also inherits that class.
The problem is, that this error comes from the line above that part namely `logits, hidden = self.actor(obs, state=state)`
So I have tried modifying the forward function in discrete/actor Actor

I modified it to the following:
```
def forward(
        self,
        obs: Union[np.ndarray, torch.Tensor],
        state: Any = None,
        info: Dict[str, Any] = {},
    ) -> Tuple[torch.Tensor, Any]:
        r"""Mapping: s -> Q(s, \*)."""
        batch = obs # MODIFIED HERE
        obs = batch['obs'] # MODIFIED HERE
        logits, hidden = self.preprocess(obs, state)
        logits = self.last(logits)
        if self.softmax_output:
            logits = F.softmax(logits, dim=-1)
            logits *= to_torch_as(batch['mask'], logits) # MODIFIED HERE
        return logits, hidden
```

after this, I got an error saying, 

```
File c:\Users\szucs\anaconda3\envs\deep_rl\lib\site-packages\tianshou\data\batch.py:422, in Batch.__cat(self, batches, lens)
    418         self.__dict__[key] = torch.cat(shared_value)
    419     else:
    420         # cat Batch(a=np.zeros((3, 4))) and Batch(a=Batch(b=Batch()))
    421         # will fail here
--> 422         shared_value = np.concatenate(shared_value)
    423         self.__dict__[key] = _to_array_with_correct_type(shared_value)
    424 keys_total = set.union(*[set(batch.keys()) for batch in batches])

File <__array_function__ internals>:180, in concatenate(*args, **kwargs)

File c:\Users\szucs\anaconda3\envs\deep_rl\lib\site-packages\torch\_tensor.py:757, in Tensor.__array__(self, dtype)
    755     return handle_torch_function(Tensor.__array__, (self,), self, dtype=dtype)
    756 if dtype is None:
--> 757     return self.numpy()
    758 else:
    759     return self.numpy().astype(dtype, copy=False)

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

I have also tried 
```
if self.softmax_output:
            logits *= to_torch_as(batch['mask'], logits) # MODIFIED HERE`
            logits = F.softmax(logits, dim=-1)
```
but that leads to invalid actions, so I just stuck with the first variation.
            

So I changed logits to logits = logit.cpu()

After this, I had a similar problem with the Critic's forward, so I also changed
```
batch = obs
obs = batch['obs'] 
```

And after this finally, I am getting
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0`

**Comment by Trinkle23897** [comment]
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0

This is because `RandomPolicy` generates action in numpy format, while `PPOPolicy` generates action in torch.tensor with device=cuda. How about `Batch(act=act.cpu(), ...)` in forward function?

After the above fix, you'll encounter `'str' object has no attribute 'ndim'` again, instead, this time it happens in `policy.process_fn`. It's because the critic network you use only accept observation in array format instead of corresponding with mask. You can unpack the observation in `critic.forward` and send it to some `nn.Module`. After that the thing should be work.

**Comment by szucsaaron2** [comment]
Thank you for your help! I will check it out as soon as I can!:)

**Comment by szucsaaron2** [comment]
Thank you! I solved the problem!
