### ISSUE TITLE
Processing the PGPolicy's raw output 

### ISSUE THREAD

**Issue by 963141377** [aai-institute/tianshou#694]
I want to sample multiple actions from the network's raw output, so I  canceled the softmax option from original network and divide the output vector into N equal portions. Then I softmax these portions respectively and sample N actions. I did this by modifying forward() fuction in PGPolicy.

I want to know whether it has ready-made tools to achieve the operation I want.     

Thanks for your help.

**Comment by Trinkle23897** [comment]
> I want to know whether it has ready-made tools to achieve the operation I want.

Unfortunately no. But you can inherit from the existing `PGPolicy` class and overwrite `forward` function. That would be cleaner to implement.
