### ISSUE TITLE
Error in obs norm

### ISSUE THREAD

**Issue by tonystark262** [aai-institute/tianshou#697]
I think `isinstance( retval, (tuple, list))` is wrong as returned value will be an instance of (array, list) or (dict, list) etc. 
In my case, my environment return array and dict info upon reset. Here this code doesn't interpret this as having info and because it is a tuple of array, list and not tuple of tuple,list
https://github.com/thu-ml/tianshou/blob/99c99bb09ad44051562539158b849ee9b8b59c08/tianshou/env/venv_wrappers.py#L88-L93

Suggested edit
`reset_returns_info = isinstance(
            retval[0], np.ndarray) and len(retval) == 2 and isinstance(
                retval[1], list)`

**Comment by Trinkle23897** [comment]
Could you please paste a code snippet that can reveal this bug, so that I can add it to the unit test to make things better? Thanks!

**Comment by Trinkle23897** [comment]
`instance(retval, (tuple, list))` means check if `retval` is `tuple` or `list`, instead of checking `retval[0]` is `tuple` and `retval[1]` is `list`. Maybe there's a misunderstand?

**Comment by chenyingong** [comment]
> `instance(retval, (tuple, list))` means check if `retval` is `tuple` or `list`, instead of checking `retval[0]` is `tuple` and `retval[1]` is `list`. Maybe there's a misunderstand?

The current code `reset_returns_info = isinstance( 
     retval, (tuple, list) 
 ) and len(retval) == 2 and isinstance(retval[1], dict)` seems to be a bug. The last item on the RHS should change to `(isinstance(retval[1], dict) or isinstance(retval[1][0], dict))`, similar to the `reset_env` function in [collector.py](https://github.com/thu-ml/tianshou/blob/master/tianshou/data/collector.py#L138).

**Comment by chenyingong** [comment]
> > `instance(retval, (tuple, list))` means check if `retval` is `tuple` or `list`, instead of checking `retval[0]` is `tuple` and `retval[1]` is `list`. Maybe there's a misunderstand?
> 
> The current code `reset_returns_info = isinstance( retval, (tuple, list) ) and len(retval) == 2 and isinstance(retval[1], dict)` seems to be a bug. The last item on the RHS should change to `(isinstance(rval[1], dict) or isinstance(rval[1][0], dict))`, similar to the `reset_env` function in [collector.py](https://github.com/thu-ml/tianshou/blob/master/tianshou/data/collector.py#L138).

I mean `retval` not `rval` since the variables's name are different.

**Comment by Trinkle23897** [comment]
I see, my bad. Thanks for pointing out!
