### ISSUE TITLE
Support for variable actions

### ISSUE THREAD

**Issue by prakhar6sharma** [aai-institute/tianshou#706]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:

Hi,
I am working on a problem that requires doing multiple sequential actions (at each step first selecting x and then selecting y conditioned on x). Moreover, the choices for actions (action space for x and y) are variable.

Now, two ways that I know on how to deal with variable actions are:
1) action masking(-infinite reward) [not suitable for my case because set of all possible actions is huge]
2) building the policy such that it's input is both state and action and then do argmax over actions.

I tried going over the documentation and issues related to the variable action space but couldn't find a way on how to implement this in Tianshou.

How I envision to solve the problem is that at each step() and reset() my environment will return list of available actions(each action itself is an vector) and similar to approach 2 mentioned above, I would generate a score for all all (s,a) pairs using my policy and then do a softmax over them.

I don't have much practical experience with RL. It would be great if you could give me some pointers to how to implement this in Tianshou.

Also, thanks for writing such great library.

**Comment by Trinkle23897** [comment]
> building the policy such that it's input is both state and action and then do argmax over actions.

Feel free to subclass the existing policy. You can overwrite the forward function as:
```py
action1 = self.net1(obs)
action2 = self.net2(obs, action)
...
return Batch(action={"action1": action1, "action2": action2}, ...)
```

**Comment by prakhar6sharma** [comment]
Thanks for your quick reply.

This code will solve the sequential decision problem but how do I deal with the variable actions here.

In the above snippet [**action1 = self.net1(obs)**] , wouldn't the number of output's of self.net1 have to be fixed.

Should I pass the list of available actions back to the policy via the observations. If so then would I need to use the Dict style observations? (using numpy ndarray may cause trouble because the shape would change across steps).

**Comment by Trinkle23897** [comment]
> I need to use the Dict style observations

Feel free to do so. It's naturally supported in tianshou.
