### ISSUE TITLE
Error when add obs with mask into ReplayBuffer

### ISSUE THREAD

**Issue by xrisheng** [aai-institute/tianshou#709]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] RL algorithm bug
    + [x] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```0.4.9 0.25.0 1.12.0+cu102 1.22.4 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] linux

Hello there!

First I would like to thank you for your effort, this project is definitely practical & user-friendily.

I try to use action mask in both dqn & ppo algorithms. The details are discussed in previous issues, but then I encouter a new problem.

![1](https://user-images.githubusercontent.com/6057786/180897636-fadbddde-7d7f-46ec-9deb-f687ab19214a.PNG)

As shown in above, the orginal obs(1X3 array) is wrappered together with another mask(1X12 array).  However, when I try to place it into buffer as in collector.py
![2](https://user-images.githubusercontent.com/6057786/180897907-ef697af4-28e7-42b4-9ae8-a36179f0b801.PNG)

The data is actually not correctly buffered.  after print(buffer[0]), the obs and the mask are single values now. 
![3](https://user-images.githubusercontent.com/6057786/180898244-62f1e7bc-c724-4a1b-b00d-195e94077564.PNG)

This is an unexpected behavior for me. So the question from my side would be:
1. If this is a bug ? 
2. If it's not a good idea to pass mask into replaybuffer, in which function should I unpack the Batch(obs, mask) and have the original obs?

Thanks in advance!

**Comment by Trinkle23897** [comment]
Could you please provide a minimal script to reproduce this behavior? Thanks in advance!

**Comment by xrisheng** [comment]
[test.zip](https://github.com/thu-ml/tianshou/files/9189439/test.zip)
 Please execute the script and set the breakpoint at collector.py, line 329 after
```
            ptr, ep_rew, ep_len, ep_idx = self.buffer.add(
                self.data, buffer_ids=ready_env_ids
            )
```
you can compare the `self.buffer[0]`element and the `self.data` and see the difference.
Thank you for your effort !

Regards,
Risheng

**Comment by xrisheng** [comment]
Hi!
After debug I found out the problem is the following code in /data/buffer/manager.py line 122-123
```
        if self._save_only_last_obs:  # I used to set this boolean to True
            batch.obs = batch.obs[:, -1]
```
As my ```batch.obs``` is actually another ```Batch```, such operation leads to undefined behavior.
Could you please give me a quick fix regarding this issue? 
Thanks!

**Comment by xrisheng** [comment]
Hi! 
I figure out the problem is actually as same as in #208, where you mentioned that "The first dimension of all variables in batch should be equal to the batch-size". In my case, the dim of arrays should be (1, len) instead of (len, ).  Could you please emphasis this point in your documentation, or maybe add some sanity check in code and throw a warning? Thanks!

**Comment by Trinkle23897** [comment]
Please remove the arguments of your replay buffer:
```py
        ignore_obs_next=True,
        save_only_last_obs=True,
```

(and probably remove `stack_num` as well)

`save_only_last_obs` and `stack_num` is the optimization for Atari environment. In Atari games, it has huge observation with size `(4, 84, 84, 3)`, where 4 is from the FrameStack wrapper, which returns `t-3, t-2, t-1, t` 4 steps' stack observation. To save memory, it only stores `t` instead of all 4 frames, and use `stack_num == 4` to restore the original observation.

You can refer to the scripts of mujoco (`examples/mujoco/mujoco_ppo.py`) or `test/[discrete | continuous]/test_ppo.py` to see the standard usage for a general env.
