### ISSUE TITLE
Where is ShmemVectorEnv's optimization based on SubprocVectorEnv?

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#713]
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.9 0.24.1 1.11.0+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```
As the title says, I am using `SubprocVectorEnv` now.

The description for `ShmemVectorEnv` is:
Optimized `SubprocVectorEnv` with shared buffers to exchange observations.

Where is `ShmemVectorEnv` optimized?

**Comment by Trinkle23897** [comment]
It creates a shared buffer instead of using a pipe to exchange data from one process to the other: see https://github.com/thu-ml/tianshou/blob/0f59e38b126f7fb7696b79e53c86cd7b321550cb/tianshou/env/worker/subproc.py#L142-L147
