### ISSUE TITLE
Questions about REDQ

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#720]
1. Why does `REDQ` not use `auto_alpha`?

https://github.com/thu-ml/tianshou/blob/0f59e38b126f7fb7696b79e53c86cd7b321550cb/test/continuous/test_redq.py#L32

2. What do `ensemble_size` and `subset_size` refer to?

https://github.com/thu-ml/tianshou/blob/0f59e38b126f7fb7696b79e53c86cd7b321550cb/test/continuous/test_redq.py#L25-L26

3.The default `update_per_step` is 3. Can I use the default 0.1 of `sac`?

https://github.com/thu-ml/tianshou/blob/0f59e38b126f7fb7696b79e53c86cd7b321550cb/test/continuous/test_redq.py#L38

**Comment by Jimenius** [comment]
You can read the REDQ paper to get a better understanding of the hyper-parameters. https://arxiv.org/pdf/2101.05982.pdf

1. You can use `auto-alpha` and usually we do.
2. The `ensemble-size` is `N` and the `subset-size` is `M` in the paper.
3. The core idea of REDQ is to reduce the variance of temporal difference update with the ensemble Q networks. The property update-to-data (update-per-step in Tianshou) can be increased with the reduced variance, so as to improve sample efficiency. Refer to the question, it's a hyper-parameter to be tuned but we usually set it larger than that in SAC.

**Comment by jaried** [comment]
> 

REDQ has three key hyperparameters, G, N, and M.
So which parameter is G?
update-per-step？

**Comment by Jimenius** [comment]
`G` is the number of critic updates per data sample. It corresponds to `update_per_step` here.

**Comment by jaried** [comment]
Thanks for your answer.
