### ISSUE TITLE
Batch size limited by number of environment

### ISSUE THREAD

**Issue by tonystark262** [aai-institute/tianshou#722]
I have created DummyVectorEnv consisting of 10 environments for training. I am using onPolicy Trainer along with PPO algorithm.
My batch size is 128, step_per_collect=4000 and step_per_epoch=400K.

Now, during the network update, I see network gets a batch size of 10 instead of 128. As I vary the number of env, I find that batch size during update is minimum of batch size specified and number of env.
Is this expected?
If not how do I get more batch size during training?

**Comment by tonystark262** [comment]
Is there a way to get a larger batch size without increasing the number of environment?

**Comment by Trinkle23897** [comment]
10 is from `batch_size` of https://github.com/thu-ml/tianshou/blob/278c91a2228a46049a29c8fa662a467121680b10/tianshou/policy/modelfree/ppo.py#L111

https://github.com/thu-ml/tianshou/blob/278c91a2228a46049a29c8fa662a467121680b10/tianshou/policy/base.py#L277

https://github.com/thu-ml/tianshou/blob/278c91a2228a46049a29c8fa662a467121680b10/tianshou/trainer/onpolicy.py#L131-L136

Could you please print `len(batch)` at the beginning of PPOPolicy.learn function to see what happens?

**Comment by zhen3072** [comment]
is your action 

> self.action_space = spaces.MultiDiscrete(n, n, m, m)
where n,m express specific integers?

I meeting this error.
my program's batch size the number of environment, no [4, the number of env]
