### ISSUE TITLE
Some questions about discretesac

### ISSUE THREAD

**Issue by 127161782** [aai-institute/tianshou#723]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
I want to rewrite discretesac to output multiple actions at the same time, and each action has a different physical meaning. But I don't quite understand the code of learn. For example:
```python

 def learn(self, batch: Batch, **kwargs: Any) -> Dict[str, float]:
        weight = batch.pop("weight", 1.0)  #？？
        target_q = batch.returns.flatten()   # ？？
        act = to_torch(
            batch.act[:, np.newaxis], device=target_q.device, dtype=torch.long
        )

```
Where does "weight" come from, where does Batch encapsulate the pop method and returns attribute？

**Comment by Trinkle23897** [comment]
You can find out more in `BasePolicy.update`:

https://github.com/thu-ml/tianshou/blob/278c91a2228a46049a29c8fa662a467121680b10/tianshou/policy/base.py#L256-L258

https://github.com/thu-ml/tianshou/blob/278c91a2228a46049a29c8fa662a467121680b10/tianshou/policy/base.py#L403-L406

**Comment by 127161782** [comment]
ok，thanks！
