### ISSUE TITLE
env.step API updated in gym 0.25.0

### ISSUE THREAD

**Issue by bitsandscraps** [aai-institute/tianshou#726]
- [X] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [X] new feature request
- [X] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [X] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
Gym 0.25.0 introduced a new [step API](https://github.com/openai/gym/blob/ddce4a56c85ebc7d8a07711231822eefaaa1d6ee/gym/core.py#L133) that returns a tuple of length 5(observation, reward, terminated, truncated, info) instead of 4(observation, reward, done, info).
I think tianshou's setup.py should restrict the gym version to <= 0.24.1 until it supports the new API.

**Comment by Trinkle23897** [comment]
As long as https://github.com/openai/gym/pull/3019 is not merged, it's okay not to restrict the gym version.

**Comment by bitsandscraps** [comment]
My bad. The new version of gym prints warnings when calling `gym.make` without setting the `new_step_api` to True, though.

**Comment by pseudo-rnd-thoughts** [comment]
In gym version 0.25, we have implemented the new termination truncation step api which will raise a warning if users use the old done step api (which is turned on by default). However, v0.25 should be completely backwards compatible.
 
We are planning on removing default support for the old done step API in v0.26 (the planned release is the next week). To use the old step API, we provide a conversion function and wrapper for users if they need it.

**Comment by YouJiacheng** [comment]
@Trinkle23897 Now gym#3019 merged. Maybe restrict <= 0.25.2

**Comment by pseudo-rnd-thoughts** [comment]
I believe that @Markus28 is planning on making a v26 upgrade for Tianshou
