### ISSUE TITLE
The load of the main process is too large. Is there any solution?

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#729]
-  I have marked all applicable categories:
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.9 0.25.0 1.11.0+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```
When I use tianshou multi-environment concurrently, due to the high cpu occupancy rate of the main program, the multi-core of the CPU is not fully utilized. Is there any solution?

**Comment by Trinkle23897** [comment]
It's more or less because of python subprocess and GIL. If your environment is written in Python, unfortunately, for a single-machine case there's no solution IMHO.

**Comment by jaried** [comment]
Is it possible to avoid this problem by writing in C++ and using envpool?

**Comment by Trinkle23897** [comment]
I think so.

**Comment by jaried** [comment]
Thanks for your answer.
