### ISSUE TITLE
Why was support for Tuple spaces removed completely?

### ISSUE THREAD

**Issue by michalgregor** [aai-institute/tianshou#730]
- [X] I have marked all applicable categories:
- [X] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [X] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [X] I have mentioned version numbers, operating system and environment, where applicable:

Hi, everyone, it seems that [this commit](https://github.com/thu-ml/tianshou/commit/43792bf5ab7c68dcc72d5a004c4e68d1dc43229c) introduced the following check into ``BaseVectorEnv``:
```
if isinstance(obs_list[0], tuple):
            raise TypeError(
                "Tuple observation space is not supported. ",
                "Please change it to array or dict space",
            )
```

I've seen that there was some discussion previously about ``Tuple`` spaces not really being a good fit for the way that ``Batch`` works. I am not sure, whether anything changed in this particular PR that precludes ``Tuple`` spaces from working altogether, but previously I was able to make them work (I've built a class that processes the batch into the correct format for the PyTorch module 🤷‍♂️).

If it is just that using them is considered messy / to be discouraged, maybe it's a bit extreme to raise an exception? Couldn't we turn it into a warning or something? Or is there a deeper reason behind the change?

**Comment by Trinkle23897** [comment]
It's because if we use tuple action space together with Batch, there are tons of unpredict behaviors and can cause potential bugs. If we only give use a warning instead of explicitly raising error, it's hard for user to find out such kind of a bug.

**Comment by michalgregor** [comment]
I see – does this really resolve the issue then though? You can still have Tuple spaces nested under a Dict space, no? That will not have the same problems?

**Comment by Trinkle23897** [comment]
No, we recommend to use nested Batch with numpy array instead of batch+tuple, since numpy array has type system.
