### ISSUE TITLE
Unable to load ReplayBuffer from hdf5 file

### ISSUE THREAD

**Issue by mantle2048** [aai-institute/tianshou#733]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  0.4.8  0.21.0  1.8.1+cu101  1.20.2  3.7.10  (default, Feb 26 2021, 18:47:35)  [GCC 7.3.0] linux
  ```
Hi,

I have a hdf5 file `test.hdf5` , which is saved using `tianshou.data.utils.converter.to_hdf5`.

`test.hdf5` has two keys: `obs`  (shape: [3000,213])and `act` (shape: [3000, 4]).

I want to create a [`ReplayBuffer`](https://github.com/thu-ml/tianshou/blob/master/tianshou/data/buffer/base.py#L11) by loading `test.hdf5` and I run the following code:

```python
buffer = ReplayBuffer.load_hdf5(test_path)
print(buffer)
```

However, a `RecursionError` was raised:

```python3
/users/miniconda3/envs/RL/lib/python3.7/site-packages/tianshou/data/buffer/base.py in __repr__(self)
     64     def __repr__(self) -> str:
     65         """Return str(self)."""
---> 66         return self.__class__.__name__ + self._meta.__repr__()[5:]
     67
     68     def __getattr__(self, key: str) -> Any:

/users/miniconda3/envs/RL/lib/python3.7/site-packages/tianshou/data/buffer/base.py in __getattr__(self, key)
     69         """Return self.key."""
     70         try:
---> 71             return self._meta[key]
     72         except KeyError as exception:
     73             raise AttributeError from exception

... last 1 frames repeated, from the frame below ...

/users/miniconda3/envs/RL/lib/python3.7/site-packages/tianshou/data/buffer/base.py in __getattr__(self, key)
     69         """Return self.key."""
     70         try:
---> 71             return self._meta[key]
     72         except KeyError as exception:
     73             raise AttributeError from exception

RecursionError: maximum recursion depth exceeded
```

By looking at the source code, I found that in [`load_hdf5`](https://github.com/thu-ml/tianshou/blob/master/tianshou/data/buffer/base.py#L95) function, [`cls.__new__(cls)`](https://github.com/thu-ml/tianshou/blob/master/tianshou/data/buffer/base.py#L98) will cause a `RecursionError`.

I want to ask what caused this, is it because of the h5 data?

**Comment by Trinkle23897** [comment]
It's because you use a format that isn't recognized by replay buffer. In short, you should first convert the raw h5 data to replay buffer format, and save to hdf5, finally you can directly load this hdf5. Or you can even directly assign elements from raw h5 file to a replay buffer, e.g.,

https://github.com/thu-ml/tianshou/blob/278c91a2228a46049a29c8fa662a467121680b10/examples/offline/utils.py#L24-L33

**Comment by mantle2048** [comment]
That's cool ! Thanks a lot.
