### ISSUE TITLE
Question about MultiAgentPolicyManager.

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#735]
-  I have marked all applicable categories:
    +  new feature request
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.9 0.25.2 1.11.0+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```
Can Tianshou's MultiAgentPolicyManager support multiple agents to maximize the total rew of training with limited resources? such as investment portfolios.

**Comment by Trinkle23897** [comment]
yes

**Comment by jaried** [comment]
Is there a demo of agent collaboration?

**Comment by jaried** [comment]
I'll take a look at the relevant documentation first, and ask you if I have any specific questions.

**Comment by jaried** [comment]
Simultaneous move: at each timestep, all the agents take their actions (example: MOBA games)
For simultaneous move, the solution is simple: we can just add a `num_agent` dimension to state, action, and reward. Nothing else is going to change.

I am going to write environment code for MARL.
Can `agents` use the same policy?

**Comment by Trinkle23897** [comment]
Yes

**Comment by jaried** [comment]
Can Tianshou implement MARL algorithms such as MAPPO, MADDPG, and QMIX?

**Comment by Trinkle23897** [comment]
These are not considered with the initial system design, unfortunately.

**Comment by jaried** [comment]
I read the discussion in [issue #121](https://github.com/thu-ml/tianshou/issues/121), and indeed, at that time these MARL algorithms didn't exist yet. Thanks for your answer.
