### ISSUE TITLE
I trained my env using "tianshou/test/continuous/test_redq.py", but there have some bugs

### ISSUE THREAD

**Issue by zhen3072** [aai-institute/tianshou#736]
“TypeError: only integer tensors of a single element can be converted to an index” is on line 181 of “test_ppo.py”. 

End then，I try change
`    for epoch, epoch_stat, info in trainer:
        print(f"Epoch: {epoch}")
        print(epoch_stat)
        print(info)`
to 
`print(f"Epoch: {trainer.epoch}")
        print(trainer.epoch_stat)
        print(trainer.info)`
but there are no two parameters，epoch_stat and info. 

I guess there is something wrong with my env or your code.
How can I find the right question and solve it ?

**Comment by zhen3072** [comment]
I checked the trainer object and found that the parameters in it were abnormal. Many parameters were 0, test_collector.data.act has not data. It should be my env's problem. I can not find bug in my Env. Could you give me some ideas to find ？ 

my env's action_space is a 1 * n vector. The value of n is determined according to the input of the class. Its order of magnitude is in [100, 300]

**Comment by Trinkle23897** [comment]
Can you share the training script and detailed error message? Either here or send it to my email. I guess you mistakenly use something.

**Comment by zhen3072** [comment]
My training script：
```py
import argparse
import os
import pprint

import gym
import numpy as np
import torch
from torch.distributions import Independent, Normal
from torch.utils.tensorboard import SummaryWriter

from tianshou.data import Collector, VectorReplayBuffer
from tianshou.env import DummyVectorEnv
from tianshou.policy import PPOPolicy
from tianshou.trainer import OnpolicyTrainer
from tianshou.utils import TensorboardLogger
from tianshou.utils.net.common import ActorCritic, Net
from tianshou.utils.net.continuous import ActorProb, Critic

def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--task', type=str, default='stimulateEnv-v0')
    parser.add_argument('--reward-threshold', type=float, default=None)
    parser.add_argument('--seed', type=int, default=1)
    parser.add_argument('--buffer-size', type=int, default=20000)
    parser.add_argument('--lr', type=float, default=1e-3)
    parser.add_argument('--gamma', type=float, default=0.95)
    parser.add_argument('--epoch', type=int, default=5)
    parser.add_argument('--step-per-epoch', type=int, default=150000)
    parser.add_argument('--episode-per-collect', type=int, default=16)
    parser.add_argument('--repeat-per-collect', type=int, default=2)
    parser.add_argument('--batch-size', type=int, default=128)
    parser.add_argument('--hidden-sizes', type=int, nargs='*', default=[512, 512])#default=[64, 64]
    parser.add_argument('--training-num', type=int, default=16)
    parser.add_argument('--test-num', type=int, default=100)
    parser.add_argument('--logdir', type=str, default='log')
    parser.add_argument('--render', type=float, default=0.)
    parser.add_argument(
        '--device', type=str, default='cuda' if torch.cuda.is_available() else 'cpu'
    )
    # ppo special
    parser.add_argument('--vf-coef', type=float, default=0.25)
    parser.add_argument('--ent-coef', type=float, default=0.0)
    parser.add_argument('--eps-clip', type=float, default=0.2)
    parser.add_argument('--max-grad-norm', type=float, default=0.5)
    parser.add_argument('--gae-lambda', type=float, default=0.95)
    parser.add_argument('--rew-norm', type=int, default=1)
    parser.add_argument('--dual-clip', type=float, default=None)
    parser.add_argument('--value-clip', type=int, default=1)
    parser.add_argument('--norm-adv', type=int, default=1)
    parser.add_argument('--recompute-adv', type=int, default=0)
    parser.add_argument('--resume', action="store_true")
    parser.add_argument("--save-interval", type=int, default=4)
    args = parser.parse_known_args()[0]
    return args


def test_ppo(args=get_args()):
    env = gym.make(args.task)
    args.state_shape = env.observation_space.shape or env.observation_space.n
    args.action_shape = env.action_space.shape or env.action_space.n
    args.max_action = env.action_space.shape
    if args.reward_threshold is None:
        default_reward_threshold = {"stimulateEnv-v0": 23}
        args.reward_threshold = default_reward_threshold.get(
            args.task, env.spec.reward_threshold
        )
    # you can also use tianshou.env.SubprocVectorEnv
    # train_envs = gym.make(args.task)
    train_envs = DummyVectorEnv(
        [lambda: gym.make(args.task) for _ in range(args.training_num)]
    )
    # test_envs = gym.make(args.task)
    test_envs = DummyVectorEnv(
        [lambda: gym.make(args.task) for _ in range(args.test_num)]
    )
    # seed
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    train_envs.seed(args.seed)
    test_envs.seed(args.seed)
    # model
    net = Net(args.state_shape, hidden_sizes=args.hidden_sizes, device=args.device)
    actor = ActorProb(
        net, args.action_shape, max_action=args.max_action, device=args.device
    ).to(args.device)
    critic = Critic(
        Net(args.state_shape, hidden_sizes=args.hidden_sizes, device=args.device),
        device=args.device
    ).to(args.device)
    actor_critic = ActorCritic(actor, critic)
    # orthogonal initialization
    for m in actor_critic.modules():
        if isinstance(m, torch.nn.Linear):
            torch.nn.init.orthogonal_(m.weight)
            torch.nn.init.zeros_(m.bias)
    optim = torch.optim.Adam(actor_critic.parameters(), lr=args.lr)

    # replace DiagGuassian with Independent(Normal) which is equivalent
    # pass *logits to be consistent with policy.forward
    def dist(*logits):
        return Independent(Normal(*logits), 1)

    policy = PPOPolicy(
        actor,
        critic,
        optim,
        dist,
        discount_factor=args.gamma,
        max_grad_norm=args.max_grad_norm,
        eps_clip=args.eps_clip,
        vf_coef=args.vf_coef,
        ent_coef=args.ent_coef,
        reward_normalization=args.rew_norm,
        advantage_normalization=args.norm_adv,
        recompute_advantage=args.recompute_adv,
        dual_clip=args.dual_clip,
        value_clip=args.value_clip,
        gae_lambda=args.gae_lambda,
        action_space=env.action_space,
    )
    # collector
    train_collector = Collector(
        policy, train_envs, VectorReplayBuffer(args.buffer_size, len(train_envs))
    )
    test_collector = Collector(policy, test_envs)
    # log
    log_path = os.path.join(args.logdir, args.task, "ppo")
    writer = SummaryWriter(log_path)
    logger = TensorboardLogger(writer, save_interval=args.save_interval)

    def save_best_fn(policy):
        torch.save(policy.state_dict(), os.path.join(log_path, "policy.pth"))

    def stop_fn(mean_rewards):
        return mean_rewards >= args.reward_threshold

    def save_checkpoint_fn(epoch, env_step, gradient_step):
        # see also: https://pytorch.org/tutorials/beginner/saving_loading_models.html
        ckpt_path = os.path.join(log_path, "checkpoint.pth")
        # Example: saving by epoch num
        # ckpt_path = os.path.join(log_path, f"checkpoint_{epoch}.pth")
        torch.save(
            {
                "model": policy.state_dict(),
                "optim": optim.state_dict(),
            }, ckpt_path
        )
        return ckpt_path

    if args.resume:
        # load from existing checkpoint
        print(f"Loading agent under {log_path}")
        ckpt_path = os.path.join(log_path, "checkpoint.pth")
        if os.path.exists(ckpt_path):
            checkpoint = torch.load(ckpt_path, map_location=args.device)
            policy.load_state_dict(checkpoint["model"])
            optim.load_state_dict(checkpoint["optim"])
            print("Successfully restore policy and optim.")
        else:
            print("Fail to restore policy and optim.")

    # trainer
    trainer = OnpolicyTrainer(
        policy,
        train_collector,
        test_collector,
        args.epoch,
        args.step_per_epoch,
        args.repeat_per_collect,
        args.test_num,
        args.batch_size,
        episode_per_collect=args.episode_per_collect,
        stop_fn=stop_fn,
        save_best_fn=save_best_fn,
        logger=logger,
        resume_from_log=args.resume,
        save_checkpoint_fn=save_checkpoint_fn,
    )



    for epoch, epoch_stat, info in trainer:
        print(f"Epoch: {epoch}")
        print(epoch_stat)
        print(info)


    assert stop_fn(info["best_reward"])

    assert stop_fn(trainer.best_reward)


    if __name__ == "__main__":
        pprint.pprint(info)
        # Let's watch its performance!
        env = gym.make(args.task)
        policy.eval()
        collector = Collector(policy, env)
        result = collector.collect(n_episode=1, render=args.render)
        rews, lens = result["rews"], result["lens"]
        print(f"Final reward: {rews.mean()}, length: {lens.mean()}")


def test_ppo_resume(args=get_args()):
    args.resume = True
    test_ppo(args)


if __name__ == "__main__":
    test_ppo()
```

the error message：

```sh
Traceback (most recent call last):
  File "/home/zjw/anaconda3/envs/LEO_Offloading/lib/python3.9/site-packages/tianshou/data/collector.py", line 287, in collect
    result = self.policy(self.data, last_state)
  File "/home/zjw/anaconda3/envs/LEO_Offloading/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zjw/anaconda3/envs/LEO_Offloading/lib/python3.9/site-packages/tianshou/policy/modelfree/pg.py", line 108, in forward
    logits, hidden = self.actor(batch.obs, state=state)
  File "/home/zjw/anaconda3/envs/LEO_Offloading/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zjw/anaconda3/envs/LEO_Offloading/lib/python3.9/site-packages/tianshou/utils/net/continuous.py", line 214, in forward
    mu = self._max * torch.tanh(mu)
TypeError: only integer tensors of a single element can be converted to an index
```

Thank you very much! It interfered with me for a long time

**Comment by zhen3072** [comment]
I just use my env，and utilize RL as solving tools. Therefore, I know a little about Tianshu and RL

**Comment by zhen3072** [comment]
Thinks！My env is：



and their data type are int.&nbsp;
I am not sure whether file should I train，"tianshou/test/continuous/test_ppo.py" or "tianshou/test/discrete/test_ppo.py".&nbsp;
Maybe the latter, so I trained it in ppo_.py, then I miss some bugs like danagi said in the picture.





In&nbsp;Where to put the arguments? obs_next, rew, done, _ = env.step(act) # collector.collect(...) · Issue #525 · thu-ml/tianshou (github.com)&nbsp; I detected "tianshou/test/continuous/test_ppo.py" ;
In&nbsp;The usage of `action_spaces = gym.spaces.MultiDiscrete` in DQN policy, in dqn.py · Issue #236 · thu-ml/tianshou (github.com)&nbsp;, I know that&nbsp;


so I try to train "tianshou/test/continuous/test_ppo.py" in PPO__.py", it also has some bugs ：
------------------------------------------------------


------------------------------------------------------


你好！感谢你的回复！！我根据我的研究方向写了个环境，该环境的action_space是一个多维的MultiDiscrete对象，我应该用tianshou下哪个PPO文件进行实验？&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thu-ml/tianshou"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月30日(星期二) 中午11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thu-ml/tianshou] I trained my env using "tianshou/test/continuous/test_redq.py", but there have some bugs (Issue #736)





 
Can you share the training script and detailed error message? Either here or send it to my email. I guess you mistakenly use something.

**Comment by zhen3072** [comment]
Thinks！My env is：



and their data type are int. 
I am not sure whether file should I train，"tianshou/test/continuous/test_ppo.py" or "tianshou/test/discrete/test_ppo.py". 
Maybe the latter, so I trained it in ppo_.py, then I miss some bugs like danagi said in the picture.





In Where to put the arguments? obs_next, rew, done, _ = env.step(act) # collector.collect(...) · Issue #525 · thu-ml/tianshou (github.com)&nbsp; I detected "tianshou/test/continuous/test_ppo.py" ;
In The usage of `action_spaces = gym.spaces.MultiDiscrete` in DQN policy, in dqn.py · Issue #236 · thu-ml/tianshou (github.com)&nbsp;, I know that 


so I try to train "tianshou/test/continuous/test_ppo.py" in PPO__.py", it also has some bugs ：
------------------------------------------------------


------------------------------------------------------


你好！感谢你的回复！！我根据我的研究方向写了个环境，该环境的action_space是一个多维的MultiDiscrete对象，我应该用tianshou下哪个PPO文件进行实验？ 


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "thu-ml/tianshou"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月30日(星期二) 中午11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thu-ml/tianshou] I trained my env using "tianshou/test/continuous/test_redq.py", but there have some bugs (Issue #736)





 
Can you share the training script and detailed error message? Either here or send it to my email. I guess you mistakenly use something.

**Comment by Trinkle23897** [comment]
What's your observation space and action space? Can you print them and paste here? Because I don't know what your `stimulateEnv-v0` is. Or you can delete the unnecessary part of your environment and return only fake data, and paste here.

**Comment by zhen3072** [comment]
My action_space:
```py
self.action_space = spaces.MultiDiscrete(
    action_space_,
    dtype=np.int64
)
action_space_ is a list with 255 elements.
self.observation_space = spaces.MultiDiscrete(
    observation_space_,
    dtype=np.float32
)
```
observation_space_ is a list with 130 elements.
elements of action_space_ is like that  `[5, 5, 6, 6, 6, ... , 6, ... , 6, 50, 50, ... , 50]`
elements of self.observation_space randomly generated by specified interval

**Comment by Trinkle23897** [comment]
Since your action space is multi discrete, I'd recommend you to use BranchDQN; or if you can convert it to continuous action space, you can use all examples under `test/continuous/`.

In short, you cannot use a policy that is designed for continuous action space (like redq) with an env that has discrete action space.

**Comment by zhen3072** [comment]
Thank you for your help! 
I'm trying BDQ. Whether 'MultiDiscreteToDiscrete(env)' is already available? 
My action_space is a spaces.MultiDiscrete obj not continuous, so I need to convert `env = ContinuousToDiscrete(env, args.action_per_branch)` to `env = MultiDiscreteToDiscrete(env)`

**Comment by zhen3072** [comment]
Thank you very much for your help! 
I'm trying to train '/thu-ml/tianshou/test/discrete/test_bdq.py' , and I meet a bug that  each dimension of the act in train_collector is not in the interval. 
I made the following changes to this file.
1) ' #env = ContinuousToDiscrete(env, args.action_per_branch)'  in 52 (because my action is MultiDiscrete not continuous, and the function named 'ContinuousToDiscrete()' has 'self.action_space = gym.spaces.MultiDiscrete(action_per_dim)' )
2) change 'lambda: ContinuousToDiscrete(gym.make(args.task), args.action_per_branch)' in 69 to
'lambda: gym.make(args.task)'
3) change 'lambda: ContinuousToDiscrete(gym.make(args.task), args.action_per_branch)' in  to
'lambda: gym.make(args.task)'

I find my action's each element is between 0 and (args.action_per_branch - 1), but what I want is action's every elements are within the bounds of env.action_space which is a gym.space.MultiDiscrete obj

**Comment by Trinkle23897** [comment]
cc @BFAnas

**Comment by BFAnas** [comment]
Can you print the action space before and after wrapping your environment in ContinousToDiscrete?

**Comment by zhen3072** [comment]
because of my action_space's class, the action space after wrapping my environment in ContinousToDiscrete has bug. And   I have solved the above problem. Based on '/thu-ml/tianshou/test/discrete/test_bdq.py', modify the following code↓
```py
def test_bdq(args=get_args()):
    env = gym.make(args.task)
    #env = ContinuousToDiscrete(env, args.action_per_branch)

    args.state_shape = env.observation_space.shape or env.observation_space.n
    args.num_branches = env.action_space.shape[0]
    _ = env.action_space.nvec
    args.action_per_branch = _.tolist()
```

And, 
```py
train_envs = DummyVectorEnv(
        [
            #lambda: ContinuousToDiscrete(gym.make(args.task), args.action_per_branch)
            lambda: gym.make(args.task)
            for _ in range(args.training_num)
        ]
    )
    test_envs = DummyVectorEnv(
        [
            #lambda: ContinuousToDiscrete(gym.make(args.task), args.action_per_branch)
            lambda: gym.make(args.task)
            for _ in range(args.test_num)
        ]
    )
```

But there are other problems.
```
Traceback (most recent call last):
  File "/home/zjw/anaconda3/envs/mytest/lib/python3.9/site-packages/tianshou/trainer/base.py", line 439, in run
    deque(self, maxlen=0)  # feed the entire iterator into a zero-length deque
  File "/home/zjw/anaconda3/envs/mytest/lib/python3.9/site-packages/tianshou/trainer/base.py", line 251, in __iter__
    self.reset()
  File "/home/zjw/anaconda3/envs/mytest/lib/python3.9/site-packages/tianshou/trainer/base.py", line 236, in reset
    test_result = test_episode(
  File "/home/zjw/anaconda3/envs/mytest/lib/python3.9/site-packages/tianshou/trainer/utils.py", line 27, in test_episode
    result = collector.collect(n_episode=n_episode)
  File "/home/zjw/anaconda3/envs/mytest/lib/python3.9/site-packages/tianshou/data/collector.py", line 289, in collect
    result = self.policy(self.data, last_state)
  File "/home/zjw/anaconda3/envs/mytest/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zjw/anaconda3/envs/mytest/lib/python3.9/site-packages/tianshou/policy/modelfree/bdq.py", line 106, in forward
    logits, hidden = model(obs_next, state=state, info=batch.info)
  File "/home/zjw/anaconda3/envs/mytest/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zjw/anaconda3/envs/mytest/lib/python3.9/site-packages/tianshou/utils/net/common.py", line 452, in forward
    action_scores = torch.stack(action_out, 1)
RuntimeError: stack expects each tensor to be equal size, but got [10, 3] at entry 0 and [10, 4] at entry 3
```

my arg.action_per_branch is `[3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30]` the same as my action_space.
And the action_out of `/home/zjw/anaconda3/envs/mytest/lib/python3.9/site-packages/tianshou/utils/net/common.py` is 
![image](https://user-images.githubusercontent.com/49418907/189056295-50dc3da4-e5c1-4fdd-9e5f-bafe4280fd6b.png)

**Comment by Trinkle23897** [comment]
ping @BFAnas again

**Comment by BFAnas** [comment]
Right now BDQ doesn't support a different number of actions per branch. I'll try to work on it this weekend.

**Comment by zhen3072** [comment]
thanks！！
I'm trying, and I have solved the action_score problem for my application scenario
I have modified 
![image](https://user-images.githubusercontent.com/49418907/190053318-ead937b4-e0fa-4903-9ac7-1fc900f5d121.png)
 to make the program work.
Specifically through the code mentioned earlier, and modify the 
![image](https://user-images.githubusercontent.com/49418907/190053432-b23daa70-a603-4c73-9d4b-85e58502dad7.png)
of 
![image](https://user-images.githubusercontent.com/49418907/190053451-a264404a-9315-4bf2-bb3d-4793ac4988e4.png)

**Comment by zhen3072** [comment]
My action_space:
```python
self.action_space = spaces.MultiDiscrete(
    action_space_,
    dtype=np.int64
)
```
action_space_ is a list with 255 elements.
```python
self.observation_space = spaces.MultiDiscrete(
    observation_space_,
    dtype=np.float32
)
```
observation_space_ is a list with 130 elements.

elements of action_space_ is like that  `[5, 5, 6, 6, 6, ... , 6, ... , 6, 50, 50, ... , 50]`

elements of self.observation_space randomly generated by specified interval

**Comment by Trinkle23897** [comment]
ping @BFAnas again
