### ISSUE TITLE
Package protobuf version requirement

### ISSUE THREAD

**Issue by bitsandscraps** [aai-institute/tianshou#739]
- [X] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [X] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [X] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [X] I have mentioned version numbers, operating system and environment, where applicable:

Output of  `conda search tianshou --info -c conda-forge`

```
tianshou 0.4.9 pyhd8ed1ab_0
---------------------------
file name   : tianshou-0.4.9-pyhd8ed1ab_0.tar.bz2
name        : tianshou
version     : 0.4.9
build       : pyhd8ed1ab_0
build number: 0
size        : 91 KB
license     : MIT
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/tianshou-0.4.9-pyhd8ed1ab_0.tar.bz2
md5         : 58cecf8ddc75f149daaf513b21acfa98
timestamp   : 2022-07-05 03:43:29 UTC
dependencies:
  - gym >=0.15.4
  - h5py >=2.10.0
  - numba >=0.51.0
  - numpy >=1.16.1
  - python >=3.6
  - pytorch >=1.4.0
  - tensorboard >=2.5.0
  - tqdm
 ```

`get_install_requires()` in [setup.py](https://github.com/thu-ml/tianshou/blob/278c91a2228a46049a29c8fa662a467121680b10/setup.py#L16)

```
def get_install_requires() -> str:
    return [
        "gym>=0.23.1",
        "tqdm",
        "numpy>1.16.0",  # https://github.com/numpy/numpy/issues/12793
        "tensorboard>=2.5.0",
        "torch>=1.4.0",
        "numba>=0.51.0",
        "h5py>=2.10.0",  # to match tensorflow's minimal requirements
        "protobuf~=3.19.0",  # breaking change, sphinx fail
    ]
```

`setup.py` requires the version of  `protobuf` to be 3.19.X, but conda recipe does not have such.
Is it okay to install a more recent version of protobuf if I'm using conda?
I want to install a package that requires `protobuf`'s version to be higher than 3.20.0.

**Comment by Trinkle23897** [comment]
> Is it okay to install a more recent version of protobuf if I'm using conda?

Totally fine!

**Comment by bitsandscraps** [comment]
Thanks a lot.
