### ISSUE TITLE
Batch shuffling in PPO.

### ISSUE THREAD

**Issue by KwanWaiChung** [aai-institute/tianshou#741]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

```python
    def learn(  # type: ignore
        self, batch: Batch, batch_size: int, repeat: int, **kwargs: Any
    ) -> Dict[str, List[float]]:
        losses, clip_losses, vf_losses, ent_losses = [], [], [], []
        for step in range(repeat):
            if self._recompute_adv and step > 0:
                batch = self._compute_returns(batch, self._buffer, self._indices)
            for minibatch in batch.split(batch_size, merge_last=True):
                # calculate loss for actor
                 ...
```
From the code in PPOPolicy, it seems that for each repeat we didn't shuffle the order of the batches. I didn't really dig deep into the code but I think if we are shuffling the batches, we should add shuffle=True to batch.split(). Shuffling the batches is crucial to the performance of PPO (forgive me for not citing the reference). Can you confirm that the code is indeed not shuffling? And if it is, do you think we should shuffle that?

**Comment by Trinkle23897** [comment]
https://github.com/thu-ml/tianshou/blob/278c91a2228a46049a29c8fa662a467121680b10/tianshou/data/batch.py#L741-L744

Shuffle defaults to True.
