### ISSUE TITLE
Two naive questions about the code implementation

### ISSUE THREAD

**Issue by KID0031** [aai-institute/tianshou#743]
Hi, I'm a beginner to RL and tianshou, when I read the code of policy gradient, I have two questions that I still can't figure out after searching.

The first is in pg.py, if we use reward normalization, it will initialize `v_s_` with `ret_rms.mean` and use `_gae_return()` to calculate the return(what does this resulted return stand for?), I'm confused why it doesn't just initialize `v_s_` to all zeros and use gae to calculate the episodic return, then normalize it, I think the results would be different.

The second is in learning part of pg.py, it uses `result = self(minibatch)`, I think `self` is a policy object and how it is called with a minibatch.

These are my questions, thanks for your time : )

**Comment by ChenDRAG** [comment]
The first question. In pg.py, the gae_lambda is set to 1.0. As a result, computing gae return is equivalent to vanilla return.  
Suppose your trajectory looks like (s1 a1 r1 s2 a2 s2 ......  s8 a8 r8, done=False). 
The undiscounted return for s1 would be, r1 + r2 + ... + r8 + V(s8) * (1-done).
The "V(s8)" here stands for bootstrapping value `v_s_[8]`, and thus `ret_rms.mean`. Clearly, when the trajectory is not finished,  `ret_rms.mean` is a much better estimate for V(s8) than 0. If all trajectories end with a `done=True` flag. It doesn't matter what the value of "V(s8)" is.

**Comment by ChenDRAG** [comment]
Second question, calling a Pytorch module is equivalent to calling the `forward` function of this module. This is a property of Pytorch, not Tianshou.
