### ISSUE TITLE
PPO: wrong old log prob

### ISSUE THREAD

**Issue by ikamensh** [aai-institute/tianshou#745]
## RL algorithm bug

Ratio probability of the action should have been saved for original weights taking this action, it currently re-computes the probability with updated weights which is incorrect.

https://github.com/thu-ml/tianshou/blob/278c91a2228a46049a29c8fa662a467121680b10/tianshou/policy/modelfree/ppo.py#L100

**Comment by Trinkle23897** [comment]
The `process_fn` function is only executed before `learn` function, so that it is calculated by the original weights. I agree it's somehow inefficient but it's not a bug.

**Comment by ikamensh** [comment]
Makes sense, I think I was missing that replay buffer always deletes everything after learning, so weights don't change between rollout and process_fn.
