### ISSUE TITLE
Can VectorReplayBuffer save h5 files according to env_id?

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#746]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [x] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:

```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.9 0.25.2 1.11.0+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
```
For example, I have 10 envs, and the buffer_size is 10m. The memory required for each save is huge. Can I save the buffers of each env separately and read them separately?

```python
buffer.save_hdf5(buffer_save_file, compression='gzip')
```

```python
                        buf = VectorReplayBuffer.load_hdf5(buffer_save_file)
                        for buf_id, source in enumerate(buf.buffers):  # move data from buf to (old) buffer
                            data, idx = source.sample(0)  # get all data
                            args.buffer.add(
                                data, buffer_ids=np.full(shape=len(idx), fill_value=(buf_id % args.env_num)))
                        del buf
```

**Comment by Trinkle23897** [comment]
Yes it's definitely possible:
```python
for b in buf.buffers:
  b.save_hdf5(...)
```

For PrioVecBuf, I don't think it's possible right now.
