### ISSUE TITLE
How do i make changes to a batch that has already been in a "VectorReplayBuffer"

### ISSUE THREAD

**Issue by P1G3s** [aai-institute/tianshou#756]
let's say i want to replace the reward of the last batch in the buffer, i tried:
```
buffer[len(buffer)-1].rew = new_reward
```
but it turns out the change didn't apply at all, maybe i did it wrong or is there any other way to do this?

**Comment by Trinkle23897** [comment]
buffer._meta.rew[i] = new_reward

**Comment by P1G3s** [comment]
works like a charm, thanks!
