### ISSUE TITLE
[Bug] ImportError: cannot import name 'PettingZooEnv' from 'tianshou.env' (/usr/local/lib/python3.7/dist-packages/tianshou/env/__init__.py)

### ISSUE THREAD

**Issue by WillDudley** [aai-institute/tianshou#758]
https://colab.research.google.com/drive/1RBqk1EirO-pYf4n8Hmwr9gHiucqP8_wg?usp=sharing

See above colab

**Comment by Trinkle23897** [comment]
You need to install pettingzoo. https://github.com/thu-ml/tianshou/blob/41ae3461f660a142dd48af134efe04d2b0dee105/tianshou/env/__init__.py#L13-L16

**Comment by WillDudley** [comment]
@Trinkle23897 Forgot to add that  on the colab.

It works on colab but not locally or via github actions (see https://github.com/WillDudley/tianshoututtest/actions/runs/3292135240/jobs/5427138282 )

**Comment by Trinkle23897** [comment]
Can you try `from tianshou.env.pettingzoo_env import PettingZooEnv` in your CI pipeline to see what happens?

**Comment by WillDudley** [comment]
@Trinkle23897 
Like this? https://github.com/WillDudley/tianshoututtest/actions/runs/3292589602/jobs/5428126538

**Comment by Trinkle23897** [comment]
okay so temporary solution: `pip install packaging`

**Comment by WillDudley** [comment]
@Trinkle23897 

Now I get a `np` error: https://github.com/WillDudley/tianshoututtest/actions/runs/3304031454/jobs/5452655687

Strangely, I even get this by using PR 751 (PZ API update), even though I got it running before (I can't find the original project, though)

**Comment by Trinkle23897** [comment]
I think the reason is you directly use an numpy  array as obs, instead of wrapping it to {obs, mask, agent_id}

**Comment by WillDudley** [comment]
Interesting, thanks for your help! I'll need to look at this in more detail when I get the time.
