### ISSUE TITLE
TypeError: render() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by cz-37** [aai-institute/tianshou#759]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)

  0.4.10 0.25.2 1.12.1+cu113 1.21.6 3.7.15 (default, Oct 12 2022, 19:14:55) 
  [GCC 7.5.0] linux

  ```

New to `tianshou` and `pettingzoo` library, following tutorial: https://github.com/thu-ml/tianshou/blob/master/docs/tutorials/tictactoe.rst

Copy paste the two files:
1. https://github.com/thu-ml/tianshou/blob/master/test/pettingzoo/tic_tac_toe.py
2. https://github.com/thu-ml/tianshou/blob/master/test/pettingzoo/test_tic_tac_toe.py

Running
```
$ python test_tic_tac_toe.py
...
$ python test_tic_tac_toe.py --watch --resume-path log/tic_tac_toe/dqn/policy.pth --opponent-path log/tic_tac_toe/dqn/policy.pth

  File "/content/tic_tac_toe.py", line 240, in watch
    result = collector.collect(n_episode=1, render=args.render)
  File "/usr/local/lib/python3.7/dist-packages/tianshou/data/collector.py", line 354, in collect
    self.env.render()
  File "/usr/local/lib/python3.7/dist-packages/tianshou/env/venvs.py", line 355, in render
    return [w.render(**kwargs) for w in self.workers]
  File "/usr/local/lib/python3.7/dist-packages/tianshou/env/venvs.py", line 355, in <listcomp>
    return [w.render(**kwargs) for w in self.workers]
  File "/usr/local/lib/python3.7/dist-packages/tianshou/env/worker/dummy.py", line 49, in render
    return self.env.render(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tianshou/env/pettingzoo_env.py", line 150, in render
    return self.env.render(mode)
TypeError: render() takes 1 positional argument but 2 were given

```

**Comment by Trinkle23897** [comment]
What's your pettingzoo version?

**Comment by cz-37** [comment]
```
>>> import pettingzoo
>>> pettingzoo.__version__
'1.22.0'
```

**Comment by cz-37** [comment]
> What's your pettingzoo version?


```
>>> import pettingzoo
>>> pettingzoo.__version__
'1.22.0'
```
What is the supported `pettingzoo` version? at least for the tutorial

**Comment by cz-37** [comment]
Confirm working with  pettingzoo `v1.21.0`

**Comment by Trinkle23897** [comment]
It's because at some point, pettingzoo changed its behavior of `render` function: https://github.com/Farama-Foundation/PettingZoo/pull/800
