### ISSUE TITLE
Question - add scalar values to logger 

### ISSUE THREAD

**Issue by AlessandroZavoli** [aai-institute/tianshou#763]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [X] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

Dear all, 
I would like to add a scalar coming from the info variable returned by env.step() during training/test.
Is there a minimal working example?

**Comment by Trinkle23897** [comment]
Of course! 
Doc: https://tianshou.readthedocs.io/en/master/tutorials/cheatsheet.html#handle-batched-data-stream-in-collector
Code: https://github.com/thu-ml/tianshou/blob/41ae3461f660a142dd48af134efe04d2b0dee105/test/base/test_collector.py#L59-L106
