### ISSUE TITLE
Offline RL example bug.

### ISSUE THREAD

**Issue by LLYYKK** [aai-institute/tianshou#766]
When I tried to run the offline RL example, the following bug came up:

'''
in load_buffer_d4rl replay_buffer = ReplayBuffer.from_data(TypeError: ReplayBuffer.from_data() missing 2 required positional arguments: 'terminated' and 'truncated'
‘’‘

The d4rl dataset  do not have keys of 'terminated' and 'truncated', but .from_data requires.

**Comment by Trinkle23897** [comment]
@nuance1979 Could you please take a look?

**Comment by LLYYKK** [comment]
> @nuance1979 Could you please take a look?

I just try to run the d4rl example of CQL in the examples folder.While using the load_buffer_d4rl function, it actually gets a dataset without 'terminated' and 'truncated'  keys. But others functions need them strictly....

**Comment by nuance1979** [comment]
@LLYYKK Thanks for reporting! This is a breaking chance introduced to support gym>=0.26.0 (#748). I'll submit a PR soon.
