### ISSUE TITLE
pettingzoo render have problem

### ISSUE THREAD

**Issue by siwuxei** [aai-institute/tianshou#767]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ *] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  0.4.10 0.26.2 1.10.2 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```
Thanks to the developer for opening the source of this project. I have been using it for a while, and recently I'm using pettingzoo to build a private environment. Recently, pettingzoo was updated to PettingZoo == 1.22.1, and there was an error in rendering.

Use the test file [tictactoe.py](https://github.com/thu-ml/tianshou/blob/master/test/pettingzoo/tic_tac_toe.py)  provided by you, an error will be reported in the render link after the training is completed. The error is as follows:

  ```python
render() takes 1 positional argument but 2 were given
  ```

After investigation, it is because pettingzoo updated the input position of the render parameter.

Is there any good compatibility method?

**Comment by Trinkle23897** [comment]
A temporary solution is to install `pettingzoo<1.22`. I need to ping them.
https://github.com/Farama-Foundation/PettingZoo/pull/800
