### ISSUE TITLE
Args of Net and MLP mismatch

### ISSUE THREAD

**Issue by oleotiger** [aai-institute/tianshou#770]
**new feature request**
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
```bash
print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.10 0.21.0 1.12.1.post200 1.23.3 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0] linux
```
1. Type of args `norm_layer` and `activation` of `tianshou.utils.net.common.Net` is `Optional[ModuleType]`, while that of MLP is Optional[Union[ModuleType, Sequence[ModuleType]]]. In `init` of `Net`, call of `MLP()` with `norm_layer` and `activation` miss adaptation to type `Sequence[ModuleType]` .
  I think it's better to keep consistent of the type of args between Net and MLP.

2. Beside `norm_layer` and `activation`, I suggest that add concomitant args to pass args or kwargs for init of norm_layer and activation.
  For example,
```python
def miniblock(
        input_size: int,
        output_size: int = 0,
        norm_layer: Optional[ModuleType] = None,
        norm_args: Optional[(Optional[Tuple], Optional[Dict])] = None,
        activation: Optional[ModuleType] = None,
        act_args: Optional[(Optional[Tuple], Optional[Dict])] = None,
        linear_layer: Type[nn.Linear] = nn.Linear,
) -> List[nn.Module]:
```
Add `act_args: Optional[args or kwargs or sequence of args/kwargs],` to Net and MLP.

**Comment by Trinkle23897** [comment]
would you like to make a pull request?

**Comment by oleotiger** [comment]
> 

Fine, need I create a branch?

**Comment by Trinkle23897** [comment]
Fork, create a branch, commit, open pull request

**Comment by oleotiger** [comment]
> Fork, create a branch, commit, open pull request

ok
