### ISSUE TITLE
Squashed Actions in SACPolicy

### ISSUE THREAD

**Issue by bitsandscraps** [aai-institute/tianshou#771]
- [X] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [X] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [X] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [X] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [X] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
The SACPolicy outputs [squashed actions](https://github.com/thu-ml/tianshou/blob/06aaad460e402bfa4ae3b631a5e7f64d0b1d5405/tianshou/policy/modelfree/sac.py#L126).
Due to the properties of tanh, the actions are bounded above by 1 and below by -1, regardless of the environment's action space.
Is this an intended behavior?

**Comment by Trinkle23897** [comment]
Yes but the action re-scaling is in BasePolicy https://github.com/thu-ml/tianshou/blob/06aaad460e402bfa4ae3b631a5e7f64d0b1d5405/tianshou/policy/base.py#L153
and will trigger by collector https://github.com/thu-ml/tianshou/blob/06aaad460e402bfa4ae3b631a5e7f64d0b1d5405/tianshou/data/collector.py#L312

**Comment by bitsandscraps** [comment]
https://github.com/thu-ml/tianshou/blob/06aaad460e402bfa4ae3b631a5e7f64d0b1d5405/examples/mujoco/mujoco_sac.py#L115-L127

Should I add `action_scaling=True` to the previous snippet if I want the code to work for general action spaces?

**Comment by Trinkle23897** [comment]
I think so (by default it's True)

**Comment by bitsandscraps** [comment]
Oh it was set to True in the `__init__` of `DDPGPolicy`. My bad.
