### ISSUE TITLE
about the gym version

### ISSUE THREAD

**Issue by andeyeluguo** [aai-institute/tianshou#772]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

gym 0.26.0 does not work, but 
pip install gym==0.25.0 will work.

python examples/atari/atari_dqn.py
will get the results.

**Comment by Markus28** [comment]
Thanks for creating the issue. It appears that examples/atari/atari_wrapper is the problem. I will fix this :)

**Comment by 911091933** [comment]
Thanks
