### ISSUE TITLE
How to set BatchNorm1d for actor in DDPG?

### ISSUE THREAD

**Issue by oleotiger** [aai-institute/tianshou#773]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
```

0.4.10 0.21.0 1.12.1.post200 1.23.3 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0] linux
```
In the example `examples/mujoco/mujoco_ddpg.py`, there is only hidden layers in Actor model.

It raises error when I add norm layers in Actor:
```python
# code 
net_a = Net(args.state_shape, hidden_sizes=args.hidden_sizes, device=args.device, norm_layer=nn.BatchNorm1d,
activation=nn.LeakyReLU)
```
Error:
`ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256])`

This is due to `offpolicy_trainer.run -->trainer.__next__() --> train_step() --> train_collector.collect() -->self.policy.actor.forward() -->batch_norm() --> _verify_batch_size(input.size()`

I'm newbee in pytorch and RL, here I have 2 question:
1. In train_collector.collect(), is actor,forward() training or predicting? If predicting, should I set actor.eval()?
2. What other changes should I make to add norm layers in Actor?

I have read #185 and #198 , but I don't think the answer solved my question.

**Comment by Trinkle23897** [comment]
BN is kind of annoying to implement in RL because of the different states it requires to run. I'd recommend not using BN in RL because some previous empirical results show there's no juicy part for applying BN in RL. However, LayerNorm is quite good compared with BN.

> In train_collector.collect(), is actor.forward() training or predicting? If predicting, should I set actor.eval()?

It's `predicting`. `actor.eval` is automatically set in this phase.

> What other changes should I make to add norm layers in Actor?

At that moment (2020, the above two issues) if I remember correctly, I need to manually disable `actor.eval`. Otherwise, BN cannot collect the info of mean/std.
