### ISSUE TITLE
Link for mujoco pretained agent/log detail doesn't work

### ISSUE THREAD

**Issue by hmishfaq** [aai-institute/tianshou#778]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [x] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:

The link provided for pretrained agents, detailed graphs (single agent, single game) and log details for mujoco environment (https://cloud.tsinghua.edu.cn/d/f45fcfc5016043bc8fbc/) does not work. Is there any updated link?

**Comment by ChenDRAG** [comment]
I will try updating the link shortly after. PR #779

**Comment by ChenDRAG** [comment]
https://drive.google.com/drive/folders/1IycImzTmWcyEeD38viea5JHoboC4zmNP?usp=share_link

If the saved checkpoints do not work in the latest version of the library. You could try switching to the commit id recommended on this [page](https://github.com/thu-ml/tianshou/tree/master/examples/mujoco#footnote2).
