### ISSUE TITLE
Any plan to include Bootstrapped DQN?

### ISSUE THREAD

**Issue by hmishfaq** [aai-institute/tianshou#783]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [X] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
Is there any plan to implement Bootstrapped DQN with tianshou?
https://arxiv.org/abs/1602.04621

**Comment by nuance1979** [comment]
Would you be interested in submitting a PR? [Here](https://tianshou.readthedocs.io/en/latest/contributing.html) is the contribution guideline.
