### ISSUE TITLE
How to implement simple action mask for multiple policies?

### ISSUE THREAD

**Issue by adiyaDalat** [aai-institute/tianshou#784]
I'm using a custom env which requires action mask for some situation (like when obs[0] = 0).  

I only found mask implementation in DQN where action needs to be transformed into dict. 

Since I'm experimenting on multiple discrete policies such as SAC/DQN/A2C/PPO, is there a universal method to implement mask on action in forward function of these policies? 

example like below:
environment has "0/1/2" three actions, when obs[0] = 0, action 0 and 2 are unavailable and action 1 is available. 

`
def action_masks(self):
        if obs[0] == 0:
            return [False, True, False]
        else:
            return [True, True, True]
`

**Comment by Trinkle23897** [comment]
Sorry for the late reply. Unfortunately, it needs some extra work to do. I can briefly explain how to make it happen.

We usually use a categorical distribution or Q table for discrete action space. Q table with mask is implemented (DQN), categorical distribution needs to add https://github.com/thu-ml/tianshou/issues/542#issuecomment-1059986961

It's hard to define a mask for continuous action.

Feel free to submit a pull request if you are interested in adding this feature to the main repo.
