### ISSUE TITLE
Basic Questions about Tianshou

### ISSUE THREAD

**Issue by uinversion** [aai-institute/tianshou#790]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates

Hello. I've been using Tianshou for a few days now, and I think that it is much better than any other library that I've tried (I think the design is genius as it is very easy to use but also allows a ton of customisation!).

I am still a bit new to RL though, so I had a few basic questions about the library, and I was wondering if anyone can please help me. I really appreciate your help.

 - What is the relation between batch size and episodes per collect. Correct me if I'm wrong but for neural nets, batch size is defined as "number of samples used for a single network update". Episodes per collect is defined in the wiki as "the number of episodes the collector would collect before the network update". What is the difference between these two?
 - Do epochs mean the same thing as in neural networks? If I say epochs=10 (for on policy), will data be collected only once but trained 10 times over? (is this off policy?)
 - I'm trying to decide what replay buffer size to use for my (on policy) train collector. I'm assuming that if my buffer size is too small, then some of the collected data will be overwritten, which would be wasteful. I have a feeling that buffer size should be a function of step per epoch, episodes per collect and batch size (would there be anything else?). If  I'm working on a task with a large batch size and step per epoch, what buffer size should I use?

Thank you very much for help!

**Comment by Trinkle23897** [comment]
> What is the relation between batch size and episodes per collect. Correct me if I'm wrong but for neural nets, batch size is defined as "number of samples used for a single network update". Episodes per collect is defined in the wiki as "the number of episodes the collector would collect before the network update". What is the difference between these two?

In the world of RL, you need to get sampled trajectories first and then use these trajectories to update nn. ep_per_collect stands for the first one and batch_size is for the second one.

> Do epochs mean the same thing as in neural networks? If I say epochs=10 (for on policy), will data be collected only once but trained 10 times over? (is this off policy?)

Nope. The term `epoch` only exists in tianshou in the world of rl. If you set epoch=10, it will have 10 [train_collector, test_collector] calls, i.e., 10 evals. The length of each epoch is defined by collector-related hyper-params.

> I'm trying to decide what replay buffer size to use for my (on policy) train collector. I'm assuming that if my buffer size is too small, then some of the collected data will be overwritten, which would be wasteful. I have a feeling that buffer size should be a function of step per epoch, episodes per collect and batch size (would there be anything else?). If I'm working on a task with a large batch size and step per epoch, what buffer size should I use?

That's most of it. Feel free to play with these hyper-parameters to see the different training behavior. It's very cheap to run a cartpole-level experiment in tianshou.
The main thing you should consider is "how many times one data sample has been updated to neural net on average". It's tricky but if this number is too big or too small, the result won't be as good as you expected.

**Comment by uinversion** [comment]
I understand how it works now, thank you very much for help!

**Comment by uinversion** [comment]
Hello, I actually had a quick question. Just to make sure I understand epoch correctly, is there any difference between using say using 1 epoch and 1000 step per epoch versus 10 epochs and 100 step per epoch.

Also, apologies for incorrectly closing this issue, I'm new to github.

**Comment by Trinkle23897** [comment]
The only difference is the number of evaluation in your case. The training step is the same.

**Comment by uinversion** [comment]
I see. Thanks!
