### ISSUE TITLE
A reproduce problem, and a way to solve it

### ISSUE THREAD

**Issue by zh4men9** [aai-institute/tianshou#794]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

I used the`/tianshou/examples/mujoco/mujoco_td3.py` to train the td3 algorithm. But I found that, with the same seed, the outcomes aren't the same.

I check the source code carefully, and debug it. Finally, I found the bug caused by the `train_collector.collect(n_step=args.start_timesteps, random=True)` in `/tianshou/examples/mujoco/mujoco_td3.py`. Because the `_action_space` doesn't set seed in `train_collector`. So, I modified the `init` function in `class Collector`:

```python
self._action_space = self.env.action_space
# add a seed set
self._action_space.seed(self.env.config['seed'])
```

After this change, I got the same results in two runs with the same seed.

I don't know which algorithms have this problem, so I do not provide a `pull` request, I just write down what I have found.

I hope this can help someone!

``` python
import tianshou, gym, torch, numpy, sys
print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)

0.4.11 0.26.2 1.14.0.dev20221204+cu117 1.23.5 3.8.15 (default, Nov 24 2022, 15:19:38) 
[GCC 11.2.0] linux
```

**Comment by Trinkle23897** [comment]
This is a long-existing bug in gym. The best way to solve it is to add an env wrapper that forcibly set action_space seed whenever user calls either `seed()` or `reset(seed=seed)` function.

**Comment by MischaPanch** [comment]
After moving to gymnasium, hopefully this is sorted
