### ISSUE TITLE
fetch_her_ddpg warning

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#797]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.11 0.26.2 1.12.1+cu116 1.23.3 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)] win32
```
[fetch_her_ddpg.py](https://github.com/thu-ml/tianshou/blob/master/examples/mujoco/fetch_her_ddpg.py)

When I change the `traning-number` to >=2 such as 4, a warning appears:

```python
\tianshou\data\collector.py:255: UserWarning: n_step=1 is not a multiple of #env (4), which may cause extra transitions collected into the buffer
```

**Comment by Trinkle23897** [comment]
that doesn't matter most of the time :)
