### ISSUE TITLE
How to Use Policies With Complex Inputs

### ISSUE THREAD

**Issue by fishbotics** [aai-institute/tianshou#809]
Hi,

I have a policy class that takes in a point cloud with N points (dimensions [B x N x 4]) and joint states for a robot ([B x K]). I was intending to have my environment generate these point clouds as observations and return this state as a Tuple. Essentially my step function (in the Gymnasium environment) would then look like:

```
def step(self, action):                                                                
    joint_states = self.get_joint_states(action)
    point_cloud = self.render_point_cloud(action)
    ...
    return (joint_states, point_cloud), reward, terminated, truncated, info
```

However, when I try to use PPO, I get an error saying that Tuple-based observation spaces are not supported by Tianshou for vector environments. 
```
  File "/usr/local/lib/python3.8/dist-packages/tianshou/env/venvs.py", line 215, in reset
    raise TypeError(
TypeError: ('Tuple observation space is not supported. ', 'Please change it to array or dict space')
```

What is the right design here? How should I be representing observations like this?

Thanks for your help!

**Comment by fishbotics** [comment]
For what it's worth, I tried switching to a dictionary state. I'm still a bit confused here though. The `Critic` class seems to require that the input (which is automatically set as the observation) should be able to be converted to a Tensor:
https://github.com/thu-ml/tianshou/blob/c8be85b2407bb3b094be92c7a27657231e143963/tianshou/utils/net/continuous.py#L125

Also, is this the standard practice? Should I be casting numpy arrays to tensors in my forward calls as well? What's the right point at which to move things over to Pytorch (since as far as I can tell, Gymnasium still expects everything to be Numpy)

**Comment by Trinkle23897** [comment]
Sorry for the late reply. The right thing to do is:

1. use dict as obs type: 
```
return {"joint_states": joint_states, "point_cloud": point_cloud}, reward, terminated, truncated, info
```
2. You should customize your network class to accept type `Batch` as input observation, for example, 
```
real_obs = np.concatenate([obs.joint_states, obs.point_cloud])
# and then send real_obs to nn forward function
```
It's because we don't know ahead of time what user wants to set as a part of the network input.
