### ISSUE TITLE
How to save best success rate model when training?

### ISSUE THREAD

**Issue by whc688** [aai-institute/tianshou#822]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
0.4.11 0.21.0 1.13.1+cu117 1.23.5 3.8.16 (default, Jan 17 2023, 23:13:24) 
[GCC 11.2.0] linux

I'm using a custom env, and task succeeds when some condition are met. How can i save best success rate model when training and how can i calculate success rate of my policy when testing?

**Comment by Trinkle23897** [comment]
Use multiple episode to evaluate the model, calculate mean(success_rate) over these episodes.
You can customize your save condition (save_checkpoint_fn), the metric is the same as above.

**Comment by whc688** [comment]
Thanks for your kind reply! But where can i add the code to calculate success_rate? I think i need to add the part of logging success into Colletor.collect, (because i need to log whether an episode is success or not), and change BaseTrainer.test_step and test_episode to calculate mean success_rate and save best .Is there an easier way to do that？

**Comment by Trinkle23897** [comment]
You can set reward: only final step can have a non-zero value, 0 for fail, 1 for success. Collector will calculate mean reward for you. And that's only for test_env

**Comment by whc688** [comment]
Many thanks, i'll try that

**Comment by zichunxx** [comment]
> You can set reward: only final step can have a non-zero value, 0 for fail, 1 for success. Collector will calculate mean reward for you. And that's only for test_env

Hi! @Trinkle23897  It seems that this method only works for the env with binary and sparse reward?

**Comment by Trinkle23897** [comment]
I don't think so. If you can set a flag in `env.__init__` that would explicitly control whether it gives original reward or modified reward (0/1), it would behave correctly in train_envs (original reward) and test_envs (modified reward). We only use test_envs to gather evaluation result, instead of reusing train_envs.

**Comment by zichunxx** [comment]
Thanks for the guidance @Trinkle23897. With the method you mentioned, I think the test reward (0/1) can also be treated as a test success rate during training, am I right? I'm trying to log the test success rate during training. But for now, the logger seems to log some specific parameters, such as actor loss. If I understand you correctly, I'd like to log the variation in success rate over the training in the way you suggest.
