### ISSUE TITLE
puzzle about policy test

### ISSUE THREAD

**Issue by GongYanfu** [aai-institute/tianshou#824]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:

![image](https://user-images.githubusercontent.com/46698455/223968063-8e80744d-d978-464d-9517-abc2b0f3e350.png)

If I only want to test a model using trained result "policy.pth", how should I implement the code?
can you share us the example code?
I find the test examples for online algorithms under test folder need train the policy and then to evaluate.

**Comment by nuance1979** [comment]
Take a look at https://github.com/thu-ml/tianshou/blob/bc222e87a636f13575d65b5603ad43af5e39090e/examples/atari/atari_dqn.py#L200

**Comment by GongYanfu** [comment]
I have gotten it.
ok thanks for your answer.
