### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'scale'

### ISSUE THREAD

**Issue by Caopeng17** [aai-institute/tianshou#827]

**Comment by Trinkle23897** [comment]
can you provide more info? like your command, python package version:
```python
import tianshou, gymnasium as gym, torch, numpy, sys
print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
```

Otherwise I cannot reproduce your error

**Comment by Caopeng17** [comment]
0.4.11 0.26.3 1.13.1 1.20.1 3.8.8 (default, Apr 13 2021, 12:59:45)  [Clang 10.0.0 ] darwin

**Comment by Caopeng17** [comment]
I use a PPO policy to sample multidimensional actions, and I run into this problem.

**Comment by Caopeng17** [comment]
policy = PPOPolicy(actor, critic, optim, dist, action_scaling=True), action_scaling=True is don't work

**Comment by Trinkle23897** [comment]
Does your env have discrete or continuous action space?

**Comment by Caopeng17** [comment]
thanks, have dealed

**Comment by Caopeng17** [comment]
```py
env = gym.make('MyEnv-v1')

from gym.utils.env_checker import check_env

train_envs = DummyVectorEnv([lambda: gym.make('MyEnv-v1', edges=edges, targetQ=Q) for _ in range(1)])
test_envs = DummyVectorEnv([lambda: gym.make('MyEnv-v1', edges=edges, targetQ=Q) for _ in range(1)])

np.random.seed(123)
torch.manual_seed(123)
train_envs.seed(123)
test_envs.seed(123)

# # model & optimizer
net = Net(state_shape=env.observation_space.shape,
          action_shape=env.action_space.shape,
          hidden_sizes=[5, 5])
actor = ActorProb(net, env.action_space.shape)
critic = Critic(net)
actor_critic = ActorCritic(actor, critic)
# orthogonal initialization
for m in actor_critic.modules():
        if isinstance(m, torch.nn.Linear):
            torch.nn.init.orthogonal_(m.weight)
            torch.nn.init.zeros_(m.bias)
optim = torch.optim.Adam(actor_critic.parameters(), lr=0.0003)

def dist(*logits):
    return Independent(Normal(*logits), 1)

#  policy
policy = PPOPolicy(actor, critic, optim, dist, action_space=env.action_space)

# collector
train_collector = Collector(policy, train_envs, VectorReplayBuffer(10, len(train_envs)))
test_collector = Collector(policy, test_envs)


def stop_fn(mean_rewards):
    return mean_rewards >= 0
# trainer
result =onpolicy_trainer(
    policy,
    train_collector,
    test_collector,
    max_epoch=0,
    step_per_epoch=1,
    repeat_per_collect=1,
    episode_per_test=1,
    batch_size=1,
    stop_fn=stop_fn,
)
```
Why is my program stuck in an infinite loop？is the problem of MyEnv?

**Comment by Trinkle23897** [comment]
It's difficult to determine the exact cause of the infinite loop without more information about your custom environment MyEnv-v1. However, I can provide some suggestions on how to debug the issue.

1. First, make sure that your custom environment is implemented correctly and adheres to the OpenAI Gym standards. You can use check_env() from gym.utils.env_checker to verify this:
```py
env = gym.make('MyEnv-v1')
check_env(env)
```
If check_env() does not raise any errors or warnings, your environment is likely implemented correctly.

2. Check if the stop_fn function is set up properly. In your code, the stopping condition is when the mean reward is greater than or equal to 0. If the mean rewards never reach this value, the training will continue indefinitely. To avoid this, you can set a maximum number of epochs or steps for training, or use a different stopping condition.
3. Ensure that the values for max_epoch, step_per_epoch, repeat_per_collect, and episode_per_test are appropriate for your problem. In your current code, max_epoch is set to 0, which means the training loop will not run any epochs. You should set this to a higher value.
4. Make sure that your environment's step() function eventually returns done=True for each episode. If the environment never signals the end of an episode, the training loop might get stuck.
5. Verify that your environment's reset() function properly resets the environment's state to the initial state or a random starting state. If the environment does not reset correctly, it may lead to an infinite loop.
6. Test your environment by running a few episodes using a random policy, just to make sure the environment works as expected and episodes can be completed.
```py
for i_episode in range(5):
    observation = env.reset()
    done = False
    t = 0
    while not done:
        action = env.action_space.sample()
        observation, reward, term, trunc, info = env.step(action)
        done = term | trunc
        t += 1
        if t > 10000:  # Prevent the loop from running indefinitely
            print("Episode did not finish after 10000 steps")
            break
    print(f"Episode {i_episode + 1} finished after {t} steps")
```
By following these suggestions, you can narrow down the possible causes of the infinite loop and identify the issue with your environment or training loop.

**Comment by duoduoqio** [comment]
> thanks, have  dealed 
Could you tell me how it was resolved? I have the same problem. Thank you.
TypeError: __init__() missing 1 required positional argument: 'scale'

**Comment by Caopeng17** [comment]
The distribution function was misused. I suggest that you should check what distribution is the wanted in your program. Thanks
---- Replied Message ----
| From | Jiading ***@***.***> |
| Date | 09/14/2023 10:06 |
| To | thu-ml/tianshou ***@***.***> |
| Cc | codeCao ***@***.***>,
Author ***@***.***> |
| Subject | Re: [thu-ml/tianshou] TypeError: __init__() missing 1 required positional argument: 'scale' (Issue #827) |

thanks, have dealed
Could you tell me how it was resolved? I have the same problem. Thank you.
TypeError: init() missing 1 required positional argument: 'scale'
