### ISSUE TITLE
Incorrect Conda installation instructions

### ISSUE THREAD

**Issue by arvganesh** [aai-institute/tianshou#828]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [X] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:

The documentation says to install Tianshou via conda with:
```
conda -c conda-forge install tianshou
```

But when I do this, I get this error: `CommandNotFoundError: No command 'conda conda-forge'.`

I had to do this instead:
```
conda install tianshou -c conda-forge
```
Details:
- OS: Ubuntu 22.04
- Shell: bash

**Comment by Trinkle23897** [comment]
hmm I think both commands work. what's your shell and os? It seems it misunderstands (or ignores) `-c` so that `conda -c conda-forge` would be interpreted to `conda conda-forge`

**Comment by arvganesh** [comment]
Updated post to include details. Sorry about that!

**Comment by Trinkle23897** [comment]
my bad, it's a typo:
- `conda install -c conda-forge tianshou`
- `conda install tianshou -c conda-forge`

these two work, but `conda -c conda-forge install tianshou` doesn't work

**Comment by arvganesh** [comment]
Thanks!
