### ISSUE TITLE
TypeError: isinstance() arg 2 must be a type or tuple of types

### ISSUE THREAD

**Issue by lyysxb** [aai-institute/tianshou#829]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
Hi~
  I follow the code on the official documentation, but I got an error when I ran it
`train_envs = ts.env.DummyVectorEnv([lambda: gym.make(task) for _ in range(train_num)])`
  TypeError: isinstance() arg 2 must be a type or tuple of types

**Comment by Trinkle23897** [comment]
can you run this and post result here?
```py
import tianshou, gymnasium as gym, torch, numpy, sys
print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
```

**Comment by lyysxb** [comment]
0.5.0 0.27.1 1.12.0 1.22.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32

**Comment by lyysxb** [comment]
> can you run this and post result here?
> 
> ```python
> import tianshou, gymnasium as gym, torch, numpy, sys
> print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
> ```

0.5.0 0.27.1 1.12.0 1.22.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32

**Comment by lyysxb** [comment]
> can you run this and post result here?
> 
> ```python
> import tianshou, gymnasium as gym, torch, numpy, sys
> print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
> ```

Sorry,it‘s my fault.
`import gymnasium as gym`
I forget to import gymnasium

**Comment by Trinkle23897** [comment]
Correct. 
```py
import gym
train_envs = ts.env.DummyVectorEnv([lambda: gym.make("CartPole-v1") for _ in range(2)])
```
will raise the issue. The solution is 
```py
import gymnasium as gym
train_envs = ts.env.DummyVectorEnv([lambda: gym.make("CartPole-v1") for _ in range(2)])
```
