### ISSUE TITLE
Vector Environment when no PettingZooEnv 

### ISSUE THREAD

**Issue by jamartinh** [aai-institute/tianshou#831]
Revision f0afdeaf6af671c71f0daa87ee85b680da68f38f  introduced an issue in:

[venvs.py](https://github.com/thu-ml/tianshou/blob/d5d521b3295e716eca67c49295bb4db8c5b47a2a/tianshou/env/venvs.py)

```python 

try:
    from tianshou.env.pettingzoo_env import PettingZooEnv
except ImportError:
    PettingZooEnv = None  # type: ignore
```

> Process Process-1:
> Traceback (most recent call last):
>   File "/data/conda/envs/python3.10/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
>     self.run()
>   File "/data/conda/envs/python3.10/lib/python3.10/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/data/conda/envs/python3.10/lib/python3.10/site-packages/tianshou/env/worker/subproc.py", line 81, in _worker
>     env = env_fn_wrapper.data()
>   File "/data/conda/envs/python3.10/lib/python3.10/site-packages/tianshou/env/venvs.py", line 49, in patched
>     if isinstance(env, (gym.Env, PettingZooEnv)):
> TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union

**Comment by jamartinh** [comment]
Perhaps a gimnaisum port issue = that type(gymnaisum.Env) != type(gym.Env)

So the issue does not raise when the first argument of isinstance matches

**Comment by Trinkle23897** [comment]
can you try `pip install pettingzoo`?
