### ISSUE TITLE
Python 3.9 DeprecationWarning: pkg_resources is deprecated as an API

### ISSUE THREAD

**Issue by skandermoalla** [aai-institute/tianshou#835]
A seemingly minor warning. I couldn't find where it came from to fix it.

- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:

To reproduce the warning:
  ```bash
>>> import tianshou
/Users/skander/miniforge3/envs/implicit-upg/lib/python3.9/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/Users/skander/miniforge3/envs/implicit-upg/lib/python3.9/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)

>>> import tianshou, gymnasium as gym, torch, numpy, sys
>>> print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.5.0 0.27.1 2.0.0 1.23.5 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11) 
[Clang 14.0.6 ] darwin
  ```

**Comment by nuance1979** [comment]
I believe this is coming from a dependency of `tianshou`, not `tianshou` itself. See [here](https://setuptools.pypa.io/en/latest/pkg_resources.html). There is no action to be taken on our side.
