### ISSUE TITLE
puzzle about how to modify an existed buffer from .hdf5 file

### ISSUE THREAD

**Issue by GongYanfu** [aai-institute/tianshou#838]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
print(gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.26.1 1.10.0+cu111 1.23.5 3.8.13 (default, Oct 21 2022, 23:50:54) 
[GCC 11.2.0] linux

and I used the latest version of tianshou

I used qrdqn to get the dataset for training offline BCQ.
then used the hdf5 file to make dataset.
but after I get the buffer, I want to change some data in the buffers.
How should I make it?
I cant understant this from source code and document.

**Comment by Trinkle23897** [comment]
ah you need to use buffer._meta.xxx instead of buffer.xxx to modify the data
https://github.com/thu-ml/tianshou/blob/7f8fa241dd501dbab7dba5c7e95f66702ecf039b/tianshou/data/buffer/base.py#L62

**Comment by GongYanfu** [comment]
should I only use buffer._meta.xxx to change it?
are you sure that there's no need for changing the correspondening data in other attributes?



---- Replied Message ----
| From | Jiayi ***@***.***> |
| Date | 03/28/2023 23:29 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [thu-ml/tianshou] puzzle about how to modify an existed buffer from .hdf5 file (Issue #838) |

ah you need to use buffer._meta.xxx instead of buffer.xxx to modify the data

**Comment by Trinkle23897** [comment]
The way we use buffer._meta.xxx is to discourage users from changing data in buffer, but it's okay to change the real data inside `_meta` on the fly. If you keep the original shape the same, it would work out-of-the-box

**Comment by GongYanfu** [comment]
It means that I just need change the data in buffer._meta. then the corresponding value in other attributes will change according to the value in buffer._meta.

Do I understand correctly?



---- Replied Message ----
| From | Jiayi ***@***.***> |
| Date | 03/28/2023 23:37 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [thu-ml/tianshou] puzzle about how to modify an existed buffer from .hdf5 file (Issue #838) |

The way we use buffer._meta.xxx is to discourage users from changing data in buffer, but it's okay to change the real data inside _meta on the fly. If you keep the original shape the same, it would work out-of-the-box

**Comment by Trinkle23897** [comment]
yes, exactly

**Comment by GongYanfu** [comment]
🆗
I will try it tomorrow morning.
thanks for your answer



---- Replied Message ----
| From | Jiayi ***@***.***> |
| Date | 03/28/2023 23:45 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [thu-ml/tianshou] puzzle about how to modify an existed buffer from .hdf5 file (Issue #838) |

yes, exactly

**Comment by GongYanfu** [comment]
Can I use the content of hdf5 file to reconstruct a ReplayBuffer and then use this ReplayBuferr after changing data to construct another hdf5 file ?

**Comment by Trinkle23897** [comment]
Yes

**Comment by GongYanfu** [comment]
ok thanks
will try it

**Comment by GongYanfu** [comment]
I used buffer.__getattr__(‘xxx’)[index] = new_content to change the dataset
will this change take effect?
like bellow:
![image](https://user-images.githubusercontent.com/46698455/228758775-6c552150-498f-44fa-845a-5a1e994e0031.png)

**Comment by Trinkle23897** [comment]
can you print `replay_buffer._meta.rew[index]` to double check you successfully modify the value?

**Comment by GongYanfu** [comment]
Yes, its modified successfully.
I used replay_buffer._meta.rew[index] to check and its the ideal val.
