### ISSUE TITLE
question with the from mujoco_env import make_mujoco_env

### ISSUE THREAD

**Issue by guoyihonggyh** [aai-institute/tianshou#839]
I am trying to run the example ppo. And there is a package I need to import which is:

from mujoco_env import make_mujoco_env

I am wondering which package is it? 

- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

**Comment by guoyihonggyh** [comment]
>>> print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.5.1 0.28.1 2.0.0+cu117 1.23.5 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] linux

**Comment by nuance1979** [comment]
The file in the same directory: https://github.com/thu-ml/tianshou/blob/master/examples/mujoco/mujoco_env.py
