### ISSUE TITLE
some mistakes in test/continuous, especially when use ActorProb and subclass of PGPolicy or DDPGPolicy

### ISSUE THREAD

**Issue by wujiren** [aai-institute/tianshou#844]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
in tianshou/test/continuous folder (https://github.com/thu-ml/tianshou/tree/master/test/continuous) (all the codes and files i mentioned below are in this folder), many examples use ActorProb, which contains a parameter max_action, the parameter scales the output within [-max_action,max_action]. But in PolicyClass, also contain parameters action_scaling and action_bound_method, which will do clip and scale again.(PGPoicy and DDPGPolicy set the action_scaling = True and action_bound_method = "clip" as default, so all subclass of PGPolicy use these default value)。so i think all the cases use ActorProb in test/continuous folder will project actions twice.
in the test examples, the max_action is small (i think it is 2), it is hard to detect the small difference, only some algorithm can be used in both discrete actions and continuous actions will appears that continuous actions will slightly underperform. In my custom env, follow the example codes, if the max_action is very large, the ActorProb scales the action to a large number first, then the PolicyClass clip or do tanh will project the action near -1 or 1, and then rescale the action near -max_action or max_action, it will make the algorithm learn nothing.
some example code are below:
（here i must say sorry, previously i gave an example use codes from test_redq.py, i find the parameter setting is correct because in ActorProb it set "unbounded = True", actually when i report the issue, i use the example of test_ppo.py, in that  setting, the ActorProb use default setting of "unbounded" parameter which is False, and it actually scales the action twice, and i re-edit the blow codes, use codes from test_ppo.py now ）
https://github.com/thu-ml/tianshou/blob/master/test/continuous/test_ppo.py
```python
    actor = ActorProb(
        net, args.action_shape, max_action=args.max_action, device=args.device
    ).to(args.device)
```
```
    policy = PPOPolicy(
        actor,
        critic,
        optim,
        dist,
        discount_factor=args.gamma,
        max_grad_norm=args.max_grad_norm,
        eps_clip=args.eps_clip,
        vf_coef=args.vf_coef,
        ent_coef=args.ent_coef,
        reward_normalization=args.rew_norm,
        advantage_normalization=args.norm_adv,
        recompute_advantage=args.recompute_adv,
        dual_clip=args.dual_clip,
        value_clip=args.value_clip,
        gae_lambda=args.gae_lambda,
        action_space=env.action_space,
    )
```
which i think should be
```python
    actor = ActorProb(
        net, args.action_shape, max_action=args.max_action, device=args.device, 
        unbounded=False
    ).to(args.device)
```
or 
```
    policy = PPOPolicy(
        actor,
        critic,
        optim,
        dist,
        discount_factor=args.gamma,
        max_grad_norm=args.max_grad_norm,
        eps_clip=args.eps_clip,
        vf_coef=args.vf_coef,
        ent_coef=args.ent_coef,
        reward_normalization=args.rew_norm,
        advantage_normalization=args.norm_adv,
        recompute_advantage=args.recompute_adv,
        dual_clip=args.dual_clip,
        value_clip=args.value_clip,
        gae_lambda=args.gae_lambda,
        action_space=env.action_space,
        action_scaling = False,
        action_bound_method = ""
    )
```
only one of the tow changes should be selected.
some files in the example folder also appear the same mistake.
hope i did not make mistake.

**Comment by wujiren** [comment]
@

**Comment by ChenDRAG** [comment]
Yes, you are correct. Thanks a lot for pointing out the problem. 

I think the proposal 
```
    actor = ActorProb(
        net, args.action_shape, max_action=args.max_action, device=args.device, 
        unbounded=**True**
    ).to(args.device)
```
would solve your problem.

Currently, the double-clipping method used in Tianshou is somewhat misleading or could be easily misunderstood. We will scan the whole repository to avoid similar bugs and see if we can improve over the current code setting. Feel free to open a PR if you have better ideas to improve the code and are interested.

**Comment by ChenDRAG** [comment]
The second option is
```
    actor = ActorProb(
        net, args.action_shape, max_action=1.0, device=args.device, 
        unbounded=False
    ).to(args.device)
```
I think (guess) the second option might be a better option than the first one.

**Comment by wujiren** [comment]
maybe a not so graceful implementation is to add some codes like: 
```python
assert self.action_bound_method == "" or not hasattr(self.actor, "unbounded") or self.actor.unbounded
```
or just force 
```python
if self.action_bound_method:
    self.actor.unbounded = True
```
