### ISSUE TITLE
using DistributedDataParallel to train on multi-GPU

### ISSUE THREAD

**Issue by whc688** [aai-institute/tianshou#857]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:

import tianshou, gym, torch, numpy, sys
print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.11 0.21.0 1.10.1 1.23.5 3.8.16 (default, Jan 17 2023, 23:13:24) 
[GCC 11.2.0] linux

Hi!
I'm using a modified DQN policy(based on tianshou.policy.DQNPolicy) and using tianshou.trainer.offpolicy_trainer, and i've noticed that we can use torch.nn.DataParallel to train the policy on multi-GPU. Since DistributedDataParallel is faster than DataParallel, is it possible to use DistributedDataParallel to train policy on multi-GPU, and where should i change? 
Thanks a lot!

**Comment by Trinkle23897** [comment]
You can write your version of utils.network to use DDP. In my opinion, the clearest way is to write distributed training logic at the model level and keep RL training logic single-thread.
