### ISSUE TITLE
Is time limits correctly handled in tianshou?

### ISSUE THREAD

**Issue by ligengen** [aai-institute/tianshou#858]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

According to [handling time limits in gymnasium](https://gymnasium.farama.org/tutorials/gymnasium_basics/handling_time_limits/#solution), I think the implementation in tianshou does not distinguish "terminated" and "truncated" correctly: [code](https://github.com/thu-ml/tianshou/blob/1423eeb3b2828e1ffa03b0a2a2ae13473a82713a/tianshou/policy/base.py#L394)

I wonder if this is a potential problem.

**Comment by Trinkle23897** [comment]
https://github.com/thu-ml/tianshou/blob/1423eeb3b2828e1ffa03b0a2a2ae13473a82713a/tianshou/policy/base.py#L393

value_mask handles terminate flag. This way can handle both gym (which only has done) and gymnasium (has btoh term and trunc)
