### ISSUE TITLE
running on highway_env is very slow

### ISSUE THREAD

**Issue by huang6668** [aai-institute/tianshou#864]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
It appears that running DQN with tianshou on highway_env is very slow, while it doesn't have the same issue when running on CartPole.

**Comment by Trinkle23897** [comment]
It's expected because highway_env is not as fast as cartpole

**Comment by huang6668** [comment]
Okay, thank you for your help. I'm new to reinforcement learning and there are many things I don't understand. I apologize for that. I'm not sure why I'm encountering the following situation when training under the highway_env environment. The 0% and whether it's normal are unclear to me, and I'm also not sure why the reward has become 0：

Epoch #1: 101it [00:02, 44.70it/s, env_step=100, len=5, loss=725.267, n/ep=2, n/st=10, rew=-119.50]                         
Epoch #1: test_reward: -20.320321 ± 89.708056, best_reward: -0.488600 ± 85.420588 in #0
Epoch #2: 101it [00:01, 57.07it/s, env_step=200, len=10, loss=815.136, n/ep=1, n/st=10, rew=60.90]                         
Epoch #2: test_reward: -4.090600 ± 86.539569, best_reward: -0.488600 ± 85.420588 in #0
Epoch #3: 101it [00:01, 59.77it/s, env_step=300, len=8, loss=874.648, n/ep=1, n/st=10, rew=60.70]                         
Epoch #3: test_reward: -5.900862 ± 87.048834, best_reward: -0.488600 ± 85.420588 in #0
Epoch #4: 101it [00:01, 57.17it/s, env_step=400, len=9, loss=868.791, n/ep=1, n/st=10, rew=60.80]                         
Epoch #5:   0%|          | 0/100 [00:00<?, ?it/s]Epoch #4: test_reward: -11.311584 ± 88.335914, best_reward: -0.488600 ± 85.420588 in #0
Epoch #5: 101it [00:02, 47.30it/s, env_step=500, len=13, loss=877.151, n/ep=0, n/st=10, rew=0.00]                         
Epoch #6:   0%|          | 0/100 [00:00<?, ?it/s]Epoch #5: test_reward: 0.000550 ± 0.005470, best_reward: 0.000550 ± 0.005470 in #5
Epoch #6: 101it [00:02, 49.95it/s, env_step=600, len=13, loss=877.113, n/ep=1, n/st=10, rew=0.00]                         
Epoch #6: test_reward: 0.000000 ± 0.000000, best_reward: 0.000550 ± 0.005470 in #5

**Comment by huang6668** [comment]
It seems that the reward becoming 0 is possibly due to my setting of target_update_freq=500. However, I'm not sure if the appearance of 0% is related to episode_per_test=100 in the trainer.

**Comment by huang6668** [comment]
Thank you so much for your help! Your solution worked perfectly and I really appreciate your time and effort in helping me
