### ISSUE TITLE
Issue when using self-defined enviromnment as a class according to gym standard.

### ISSUE THREAD

**Issue by DomOConner** [aai-institute/tianshou#865]
- [ ] I have marked all applicable categories:
    + [1] exception-raising bug
    + [1] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [1] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [1] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [1] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
0.5.1 0.28.1 1.4.0 1.22.4 3.8.16 (default, Mar  2 2023, 03:21:46) 
[GCC 11.2.0] linux

**I defined my own environment according to gym standard. I modified the code from a example test_PPO.
I got the following Error:**
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify float64 and array(float64, 1d, C) for 'gae.2', defined at /home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/policy/base.py (431)

**The whole message is:**
2023-05-05 16:17:06.057039: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/test/CoppeliaSim_Edu_V4_2_0_Ubuntu20_04/:/home/test/CoppeliaSim_Edu_V4_2_0_Ubuntu20_04/
2023-05-05 16:17:06.057070: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Epoch #1:   4%|####8                                                                                                                                 | 5422/150000 [00:06<02:49, 851.45it/s]
Traceback (most recent call last):
  File "/home/test/DRL-EMS/tianshou-master/ev_exp/test_ppo.py", line 208, in <module>
    test_ppo()
  File "/home/test/DRL-EMS/tianshou-master/ev_exp/test_ppo.py", line 183, in test_ppo
    for epoch, epoch_stat, info in trainer:
  File "/home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/trainer/base.py", line 299, in __next__
    self.policy_update_fn(data, result)
  File "/home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/trainer/onpolicy.py", line 131, in policy_update_fn
    losses = self.policy.update(
  File "/home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/policy/base.py", line 276, in update
    batch = self.process_fn(batch, buffer, indices)
  File "/home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/policy/modelfree/ppo.py", line 92, in process_fn
    batch = self._compute_returns(batch, buffer, indices)
  File "/home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/policy/modelfree/a2c.py", line 101, in _compute_returns
    unnormalized_returns, advantages = self.compute_episodic_return(
  File "/home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/policy/base.py", line 343, in compute_episodic_return
    advantage = _gae_return(v_s, v_s_, rew, end_flag, gamma, gae_lambda)
  File "/home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify float64 and array(float64, 1d, C) for 'gae.2', defined at /home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/policy/base.py (431)

File "../../miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/policy/base.py", line 431:
def _gae_return(
    <source elided>
    #print(returns.shape)
    for i in range(len(rew) - 1, -1, -1):
    ^

During: typing of assignment at /home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/policy/base.py (431)

File "../../miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/policy/base.py", line 431:
def _gae_return(
    <source elided>
    #print(returns.shape)
    for i in range(len(rew) - 1, -1, -1):

**I tried several methods to convert the type but nothing worked out. So I wonder what can I do? Can you give some example for self-define env as a class in tianshu? to help us understand the rule. My environment works well in spinningup.**

**Comment by DomOConner** [comment]
I have also tried to comment the numba part in the base.py code as:

#@njit
def _gae_return(
    v_s: np.ndarray,
    v_s_: np.ndarray,
    rew: np.ndarray,
    end_flag: np.ndarray,
    gamma: float,
    gae_lambda: float,
) -> np.ndarray:
    returns = np.zeros(rew.shape)
    delta = rew + v_s_ * gamma - v_s
    discount = (1.0 - end_flag) * (gamma * gae_lambda)
    gae = 0.0
    for i in range(len(rew) - 1, -1, -1):
        gae = delta[i] + discount[i] * gae
        #print(gae.shape)
        returns[i] = gae
        return returns

then the error becomes:

File "/home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/policy/base.py", line 434, in _gae_return
    returns[i] = gae.reshape(-1)
ValueError: could not broadcast input array from shape (5422,) into shape (1,)

where the shape of returns is (5422,1), that of gae is (5422,), idk how to fix the problem.

Thank you for your help!

**Comment by DomOConner** [comment]
**This is the environment I defined, the IWM part is another py file for calculation. This environment works in spinningup. Can you help me with where the problem lies? And also, in tianshou API, how can I terminate each epoch by the 'done' signal in step(), and run for all epochs, without using a stop_function?** 

`
#import gym
import gymnasium as gym
import pandas as pd
import numpy as np
from dualIWM import IWM

class DoubleMotorEnv(gym.Env):
    def __init__(self):
         df = pd.read_csv('DrivingCycle/testcycle.csv')
        self.speed_data = df['Speed'].values  
        self.acceleration_data = df['Acc'].values 
        self.gradient_data = df['Gra'].values 

        self.current_step = 0
        self.current_speed = self.speed_data[self.current_step]  
        self.current_acceleration = self.acceleration_data[self.current_step]  
        self.current_gradient = self.gradient_data[self.current_step]
        self.current_soc = 0.9  

       
        self.observation_space = gym.spaces.Box(low=-np.inf, high=np.inf, shape=(4,))

        
        self.action_space = gym.spaces.Box(low=0, high=1, shape=(4,))

    def reset(self):
        
        self.current_step = 0
        self.current_speed = self.speed_data[self.current_step]  
        self.current_acceleration = self.acceleration_data[self.current_step]  
        self.current_gradient = self.gradient_data[self.current_step]
        self.current_soc = 0.9  

        return (np.array([self.current_speed, self.current_acceleration, self.current_gradient, self.current_soc]), {})

    def step(self, action, ready_env_ids=[0]):
         #print(action)
        mode_f, mode_r, rate_f, rate_r = action

        mode_f = (mode_f+1)/2
        mode_r = (mode_r+1)/2
        rate_f = (rate_f+1)/2
        rate_r = (rate_r+1)/2
       
        iwm = IWM()
        out, cost, soc_new = iwm.run2(self.current_speed, self.current_acceleration, self.current_gradient, mode_f, mode_r, rate_f, rate_r, self.current_soc)
     
        

        # update
        self.current_step += 1
        self.current_speed = self.speed_data[self.current_step]
        self.current_acceleration = self.acceleration_data[self.current_step]
        self.current_soc = soc_new
       
        reward = -cost

     
        done = self.current_step >= len(self.speed_data)-1 

        return np.array([self.current_speed, self.current_acceleration, self.current_gradient, self.current_soc[0]]), reward, done, False, {}
`

**Comment by xins981** [comment]
> * [ ]  I have marked all applicable categories:
>   
>   * [1] exception-raising bug
>   * [1] RL algorithm bug
>   * [ ]  documentation request (i.e. "X is missing from the documentation.")
>   * [ ]  new feature request
> * [1] I have visited the [source website](https://github.com/thu-ml/tianshou/)
> * [1] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
> * [1] I have mentioned version numbers, operating system and environment, where applicable:
>   ```python
>   import tianshou, gymnasium as gym, torch, numpy, sys
>   print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
>   ```
> 
> 0.5.1 0.28.1 1.4.0 1.22.4 3.8.16 (default, Mar 2 2023, 03:21:46) [GCC 11.2.0] linux
> 
> **I defined my own environment according to gym standard. I modified the code from a example test_PPO. I got the following Error:** numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend) Cannot unify float64 and array(float64, 1d, C) for 'gae.2', defined at /home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/policy/base.py (431)
> 
> **The whole message is:** 2023-05-05 16:17:06.057039: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/test/CoppeliaSim_Edu_V4_2_0_Ubuntu20_04/:/home/test/CoppeliaSim_Edu_V4_2_0_Ubuntu20_04/ 2023-05-05 16:17:06.057070: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine. Epoch #1: 4%|####8 | 5422/150000 [00:06<02:49, 851.45it/s] Traceback (most recent call last): File "/home/test/DRL-EMS/tianshou-master/ev_exp/test_ppo.py", line 208, in test_ppo() File "/home/test/DRL-EMS/tianshou-master/ev_exp/test_ppo.py", line 183, in test_ppo for epoch, epoch_stat, info in trainer: File "/home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/trainer/base.py", line 299, in **next** self.policy_update_fn(data, result) File "/home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/trainer/onpolicy.py", line 131, in policy_update_fn losses = self.policy.update( File "/home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/policy/base.py", line 276, in update batch = self.process_fn(batch, buffer, indices) File "/home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/policy/modelfree/ppo.py", line 92, in process_fn batch = self._compute_returns(batch, buffer, indices) File "/home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/policy/modelfree/a2c.py", line 101, in _compute_returns unnormalized_returns, advantages = self.compute_episodic_return( File "/home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/policy/base.py", line 343, in compute_episodic_return advantage = _gae_return(v_s, v_s_, rew, end_flag, gamma, gae_lambda) File "/home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args error_rewrite(e, 'typing') File "/home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite raise e.with_traceback(None) numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend) Cannot unify float64 and array(float64, 1d, C) for 'gae.2', defined at /home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/policy/base.py (431)
> 
> File "../../miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/policy/base.py", line 431: def _gae_return( #print(returns.shape) for i in range(len(rew) - 1, -1, -1): ^
> 
> During: typing of assignment at /home/test/miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/policy/base.py (431)
> 
> File "../../miniconda3/envs/tianshou/lib/python3.8/site-packages/tianshou/policy/base.py", line 431: def _gae_return( #print(returns.shape) for i in range(len(rew) - 1, -1, -1):
> 
> **I tried several methods to convert the type but nothing worked out. So I wonder what can I do? Can you give some example for self-define env as a class in tianshu? to help us understand the rule. My environment works well in spinningup.**

hxd, Have you successfully integrated CoppeliaSim to Tianshou? can this bug be solved ?

**Comment by zerzerzerz** [comment]
I define my custom env and meet the same problem. After checking my code, I find that my `env.step(act)` return a `np.ndarray, shape=(1, )` as reward, which should be a Python scaler (float). After fixing this, my custom env works.
Besides, I found my bug via these steps: 1) comment the decorator `@njit` above `_gae_return` and `_nstep_return` in 

[https://github.com/thu-ml/tianshou/blob/f8808d236f53d86583c74f459365c9cc4184256c/tianshou/policy/base.py#L413](https://github.com/thu-ml/tianshou/blob/f8808d236f53d86583c74f459365c9cc4184256c/tianshou/policy/base.py#L413) and [https://github.com/thu-ml/tianshou/blob/f8808d236f53d86583c74f459365c9cc4184256c/tianshou/policy/base.py#L432](https://github.com/thu-ml/tianshou/blob/f8808d236f53d86583c74f459365c9cc4184256c/tianshou/policy/base.py#L432), so I can use vscode to debug these functions and find the bugs.

**Comment by MischaPanch** [comment]
Seems resolved, and also not in tianshou scope. Closing this
