### ISSUE TITLE
A question about training.

### ISSUE THREAD

**Issue by huang6668** [aai-institute/tianshou#867]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

Hello, I am new to reinforcement learning and tianshou. May I ask how to train according to the number of episodes instead of the number of steps?

**Comment by Trinkle23897** [comment]
In trainer, set `step_per_collect` to None and `episode_per_collect` to a non-None number, see https://github.com/thu-ml/tianshou/blob/f8808d236f53d86583c74f459365c9cc4184256c/tianshou/trainer/base.py#L384-L386

**Comment by huang6668** [comment]
Thanks！
