### ISSUE TITLE
GAE implementation is wrong

### ISSUE THREAD

**Issue by vmoens** [aai-institute/tianshou#869]
I believe this implementation is wrong:

https://github.com/thu-ml/tianshou/blob/f8808d236f53d86583c74f459365c9cc4184256c/tianshou/policy/base.py#L413C5-L429

here is the proposed fix:
```python
@njit
def _gae_return(
    v_s: np.ndarray,
    v_s_: np.ndarray,
    rew: np.ndarray,
    end_flag: np.ndarray,
    gamma: float,
    gae_lambda: float,
) -> np.ndarray:
    returns = np.zeros(rew.shape)
---     delta = rew + v_s_ * gamma - v_s
+++     delta = rew + v_s_ * gamma * (1.0 - end_flag) - v_s
    discount = (1.0 - end_flag) * (gamma * gae_lambda)
    gae = 0.0
    for i in range(len(rew) - 1, -1, -1):
        gae = delta[i] + discount[i] * gae
        returns[i] = gae
    return returns
```

The reason it's wrong is that if your sequence ends with a done state, you will have a delta that takes the next state value into account (when it should not).

**Comment by Trinkle23897** [comment]
I believe it's the simplified formula and should produce the same result (because initially, I used your suggested version, and later I found the term could be eliminated). If you found a set of data that causes inconsistency, could you paste it here? Thanks!

**Comment by vmoens** [comment]
Say
```
r=[1,1,1]
v=[2,2,2]
v_=[2,2,2]
terminal=[0,0,1]
```
You'd expect the last advantage to be 
```
r[2]-v[2]
```
Not 
```
r[2]+gamma v_[2] - v[2]
```
Since the state is terminal

**Comment by ChenDRAG** [comment]
@vmoens The problem you are worried about is taken care of by the value_mask function before passing v_s_ into _gae_return().

See:

https://github.com/thu-ml/tianshou/blob/f8808d236f53d86583c74f459365c9cc4184256c/tianshou/policy/base.py#L338

**Comment by vmoens** [comment]
Got it thanks for looking into it.
If I may: if I was maintaining this I'd take care of having functionals that return uncorrupted results when used in isolation even if they're private, it could prevent errors down the line!
But it's a very personal opinion feel free to ignore it!

**Comment by ChenDRAG** [comment]
Thanks for the suggestions. Will think about how to make it happen.

**Comment by spacegoing** [comment]
I run into this issue today. It was really painful to track down to this bug.

The thing is that using old envs like mujoco HalfCheetah-v2 (maybe also others), done wasn't by `terminated` but `truncated`. In this case, in `BasePolicy.value_mask(buffer, indices)` should we use `batch.done` instead of `batch.terminated`?

+1 for vmoens' suggestion
