### ISSUE TITLE
Log information for non-episodic environment

### ISSUE THREAD

**Issue by spacegoing** [aai-institute/tianshou#870]
I notice under the current implementation, logging (`self.logger.log_train_data(result, self.env_step)`) and reporting 
```
 result = self.train_collector.collect(
            n_step=self.step_per_collect, n_episode=self.episode_per_collect
        )
```
is  based on n/ep, episodic value.

However, for a non-episodic environment, what is the best practice for logging and reporting reward for each epoch / train update?

Many thanks!

**Comment by Trinkle23897** [comment]
It needs more definition. If you just log the sum of reward, it might be partial-episoded and it's not aligned with commonly-used definition. Feel free to hack around by yourself!
