### ISSUE TITLE
Are there any way to merge two VectorReplayBuffer

### ISSUE THREAD

**Issue by Moirai7** [aai-institute/tianshou#876]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

**Comment by Trinkle23897** [comment]
It depends on your usecase. If the two vecbuf are with exactly the same shape (same num env), you can create a third one whose size is twice larger than existing buffers, and extract data from buffer, and add it one by one. Otherwise the data would be override because of limit space.

**Comment by Moirai7** [comment]
> It depends on your usecase. If the two vecbuf are with exactly the same shape (same num env), you can create a third one whose size is twice larger than existing buffers, and extract data from buffer, and add it one by one. Otherwise the data would be override because of limit space.

Thanks for the prompt reply! Yes, the vecbufs have the same shape. Would you please provide more intructions to extract data and add it to buffer? Thanks again for your help!

**Comment by Trinkle23897** [comment]
a simple solution is (pseudocode):
```py
buffer = ReplayBuffer(...)  # with enough size, not vecbuf
for subbuf in vecbuf1.buffers:
  buffer.update(subbuf)
for subbuf in vecbuf2.buffers:
  buffer.update(subbuf)
```

**Comment by Moirai7** [comment]
It works! Thank you for your help.
