### ISSUE TITLE
[Bug] L4-Policy.ipynb

### ISSUE THREAD

**Issue by TachikakaMin** [aai-institute/tianshou#879]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [x] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

https://colab.research.google.com/drive/1MhzYXtUEfnRrlAVSB3SR83r0HA5wds2i?usp=sharing

```python
obs = env.reset()
for i in range(3):
  act = policy(Batch(obs=obs[np.newaxis, :])).act.item()
  obs_next, rew, done, info = env.step(act)
  # pretend ending at step 3
  done = True if i==2 else False
  info["id"] = i
  buf.add(Batch(obs=obs, act=act, rew=rew, done=done, obs_next=obs_next, info=info))
  obs_next = obs
```
I think the last line should be obs=obs_next

**Comment by ChenDRAG** [comment]
Yes, you are right. I've updated the notebook. Thanks a lot for pointing this out!
I will close the issue for now, feel free to reopen it.
