### ISSUE TITLE
TypeError: PPOPolicy.learn() missing 2 required positional arguments: 'batch_size' and 'repeat'

### ISSUE THREAD

**Issue by Leaflowave** [aai-institute/tianshou#897]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [x] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
0.5.0 0.26.3 1.12.1 1.23.5 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)] win32

"TypeError: PPOPolicy.learn() missing 2 required positional arguments: 'batch_size' and 'repeat'".

This error occurs when I tried to replace the Onpolicy of /pettingzoo/Pistonball_continuous.py  by Offpolicy.

I found that in offpolicy.py 'batch_size' and 'repeat' are not defined:
`losses = self.policy.update(self.batch_size, self.train_collector.buffer)`

whereas in onpolicy.py 'batch_size' and 'repeat' are properly defined:
`losses = self.policy.update(
            0,
            self.train_collector.buffer,
            batch_size=self.batch_size,
            repeat=self.repeat_per_collect,
        )`

It seems the offpolicy.py does not properly deal with the two parameters.

**Comment by Trinkle23897** [comment]
PPO is not an off-policy algorithm, please use OnPolicyTrainer instead

**Comment by Leaflowave** [comment]
Thanks for your answer.
