### ISSUE TITLE
PettingZooEnv: question about the rewards

### ISSUE THREAD

**Issue by pluieciel** [aai-institute/tianshou#900]
https://github.com/thu-ml/tianshou/blob/f8808d236f53d86583c74f459365c9cc4184256c/tianshou/env/pettingzoo_env.py#L98

Hello, 
Thanks a lot for your great work!

I am using a custom pettingzoo ACEEnv env_pet, my rewards emit from env_pet.last(), which return "self._cumulative_rewards[agent],"
but in PettingZooEnv, the env.step() return "env_pet.rewards" (line 117-119), which, if i am correct, should related to "rew" from line 88 or "env_pet._cumulative_rewards".

The reason is that in my env_pet, I record rewards at end of one cycle in 'env_pet._cumulative_rewards' and clear 'env_pet.rewards', so I cannot get the rewards with the wrapped PettingZooEnv(env_pet).

**Comment by MischaPanch** [comment]
Closing this as stale. Sorry, I can't properly understand the nature of the problem from the description. If you feel like this is important, and is actually a problem of tianshou, feel free to reopen and edit the description
