### ISSUE TITLE
Current master branch fails make pytest

### ISSUE THREAD

**Issue by BFAnas** [aai-institute/tianshou#904]
- [X] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [X] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [X] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [X] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  0.5.1 0.29.0 2.0.1+cu117 1.24.4 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0] linux
  ```
When I clone the repo, create a new conda environment and run `pip install -e ".[dev]"` and then run `make pytest`, I get the following errors:
```
========================================================================================== short test summary info ===========================================================================================
FAILED test/base/test_batch.py::test_batch - TypeError: Batch does not support heterogeneous list/tuple of tensors as unique value yet.
FAILED test/base/test_buffer.py::test_replaybuffer - TypeError: Batch does not support heterogeneous list/tuple of tensors as unique value yet.
FAILED test/discrete/test_drqn.py::test_drqn - RuntimeError: cuDNN version incompatibility: PyTorch was compiled  against (8, 5, 0) but found runtime version (8, 4, 1). PyTorch already comes bundled with cuDNN. One option to resolving this error is...
```
I think this is the raison why recent pull requests don't pass the automatic checks.
@Trinkle23897 @ChenDRAG

**Comment by Trinkle23897** [comment]
I’ll try to revive master next week

**Comment by BFAnas** [comment]
Hi @Trinkle23897 first thanks for this great library, I want to open a discussion about the future of this project and if you want to allow some people to help with reviewing and approving the pull requests. I'll post about it in the discussions section.
