### ISSUE TITLE
question for custom environment

### ISSUE THREAD

**Issue by cicada9911** [aai-institute/tianshou#905]
I am training a custom environment, but I don’t know why train/episode always stays at 5, and train/reward doesn’t seem to converge at all. Here is an image of the training process, and I hope the author can guide me on why this is happening.
![微信图片_20230801194204](https://github.com/thu-ml/tianshou/assets/88363731/4ff6145d-83fa-4854-aa68-793ec44cfc79)
![微信图片_20230801194212](https://github.com/thu-ml/tianshou/assets/88363731/5af8e34a-e703-47fa-a903-770d0f050371)

**Comment by MischaPanch** [comment]
It might be that logging starts later than 0 but that's not a real issue. As to the convergence - unfortunately, RL is generally hard. On a custom env all guarantees are gone and you are out in wild water. It could fail for a million of different reasons

**Comment by MischaPanch** [comment]
I'm not the author of tianshou, of course, just giving my two cents after working for some years on RL in industry

**Comment by MischaPanch** [comment]
Closing this since it's not a tianshou issue
