### ISSUE TITLE
Modernize build, dependencies and types

### ISSUE THREAD

**Issue by MischaPanch** [aai-institute/tianshou#914]
This issue is addressing previous comments and discussions about tianshou and adds some new ones. A preliminary list of tasks is:

- [ ] Deprecate python 3.8, use inbuilt types for annotations wherever possible (i.e. `list[str]` instead of `List[str]`, and so on)
- [ ] Use ruff and black instead of current formatter
- [ ] Move build to poetry, if possible
- [ ] If moved to poetry: replace `make` by [poethepoet](https://github.com/nat-n/poethepoet).
- [ ] Adjust pre-commit and CI to handle all these changes

Optional:
- [ ] Improve how documentation is built (not sure whether it's necessary)

@Trinkle23897 We havent't discussed using poe instead of make yet. I suggest doing it because:

1. No need for an external tool, nor an external config file
2. Works with poetry out of the box. Currently `make` will install dependencies into whichever virtualenv it's called from, which is not very safe or clean (in my opinion)
3. In fact, no additional dependencies or check for install will be needed, as one can use poetry's dependency groups for that

**Comment by MischaPanch** [comment]
I can take care of this, feel free to assign me, if you want :)

**Comment by Trinkle23897** [comment]
Nice, I'm in favor of it, thanks!
