### ISSUE TITLE
Turn tutorials into notebooks that are then executed in CI

### ISSUE THREAD

**Issue by MischaPanch** [aai-institute/tianshou#916]
Thin involves at least

- [x] Copy all notebooks from drive to a new folder in repo called `notebooks`
- [x] Adjust notebooks to current state of tianshou (using master)
- [x] Include `nbstripout` and `black[jupyter]` into lint and format
- [x] Prepare jupyter-book build compatible with tianshou styles and logo
- [x] Execute jupyter-book as part of CI
- [x] Include the built book in the docs built by sphinx (also in CI)

Additional:
- [x] Look into binder/colab integration with the notebooks now being in the repo
- [x] Extend notebooks and fix typos if needed
- [ ] Make mypy check notebooks, if possible

**Comment by MischaPanch** [comment]
@schroedk wanna look into it? Not sure it makes sense to address it before #914 is completed

**Comment by MischaPanch** [comment]
@carlocagnetta is working on this

**Comment by carlocagnetta** [comment]
>     * [ ]  Make mypy check notebooks, if possible

mypy does not perform type checking on Jupyter files, but we could use nbQA to make it possible:
https://nbqa.readthedocs.io/en/latest/readme.html#readme
