### ISSUE TITLE
some problem about the render in examples/inverse/irl_gail.py 

### ISSUE THREAD

**Issue by lzl60109** [aai-institute/tianshou#928]
when I have trained the agent of the environment **_'door-v0'_** with the irl_gail.py,  and I tended to use the scripted 
`python examples/irl_gail.py --watch --render=0.003`   to render the agent,but it did't work.

```
(adroit_gail) liang@liang-virtual-machine:~/py_project/hand_dapg/dapg$ python examples/run_gail.py --watch --render=0.003
Warning: Flow failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'flow'
Warning: CARLA failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'carla'
pybullet build time: May 20 2022 19:44:17
/home/liang/miniconda3/envs/adroit_gail/lib/python3.8/site-packages/gym/logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))
Observations shape: (39,)
Actions shape: (28,)
Action range: -1.0 1.0
/home/liang/py_project/hand_dapg/dapg/d4rl/d4rl/hand_manipulation_suite/door_v0.py:13: UserWarning: This environment is deprecated. Please use the most recent version of this environment.
  offline_env.OfflineEnv.__init__(self, **kwargs)
load datafile: 100%|█████████████████████████████| 7/7 [00:00<00:00, 319.08it/s]
dataset_size 6703
dataset loaded
Loaded agent from:  /home/liang/py_project/hand_dapg/dapg/log/door-v0/gail/seed_0_0830_124658-door_v0_gail/policy.pth
Final reward: -63.212167691569064, length: 200.0
```

it just printed the Final reward and didn't appears the glfw，but when i rendered the openAI gym environment, like the Hopper, it works.Can you tell me what's the matter?

**Comment by Trinkle23897** [comment]
could you please check if creating a `door-v0` env and call `env.render()` function manually works or not?

**Comment by lzl60109** [comment]
yes, you're right,when i used the hand_dapg environment,i did't create the window glfw,but it works when i used the openAI gym environment like "HalfCheetah-v2/Hopper-v2".Can you tell me what's the matter of this?Is it the matter of my machine or i did't install the tianshou successfully?Thank you very much!
```
import gym
import d4rl

env = gym.make('door/relocate-v0')
env.reset()

for _ in range(1000):
    action = env.action_space.sample()
    env.step(action)
    env.render()
    env.reset()
env.close()
```

**Comment by lzl60109** [comment]
actually, when i used the code below,i can be created the window glfw of hand_dapg environment, but i did't work in the openAI gym environment.Do you know how to modify it so that they can be used at the same time?
```
import gym
import d4rl

env = gym.make('door-v0')
env.reset()

for _ in range(1000):
    action = env.action_space.sample()
    print(action)
    env.step(action)
    env.env.mj_render()
    env.reset()
env.close()
```

**Comment by Trinkle23897** [comment]
The environment itself doesn't properly wire up `env.render()` to `env.env.mj_render()`, so it's an issue for environment itself. Could you try gymnasium (instead of gym) works with your above scripts?

**Comment by lzl60109** [comment]
yes,I try the code below,but it did't work again.And I also tested in `tianshou=0.4.7` and `tianshou=0.5.0.`
```
import gymnasium as gym
import d4rl

env = gym.make('door-v0')
env.reset()

for _ in range(1000):
    action = env.action_space.sample()
    print(action)
    env.step(action)
    env.render()
    env.reset()
env.close()
```
It reported the error below
```
Traceback (most recent call last):
  File "/home/liang/py_project/hand_dapg/dapg/examples/test.py", line 4, in <module>
    env = gym.make('door-v0')
  File "/home/liang/miniconda3/envs/mjrl-env/lib/python3.7/site-packages/gymnasium/envs/registration.py", line 740, in make
    env_spec = _find_spec(id)
  File "/home/liang/miniconda3/envs/mjrl-env/lib/python3.7/site-packages/gymnasium/envs/registration.py", line 537, in _find_spec
    _check_version_exists(ns, name, version)
  File "/home/liang/miniconda3/envs/mjrl-env/lib/python3.7/site-packages/gymnasium/envs/registration.py", line 403, in _check_version_exists
    _check_name_exists(ns, name)
  File "/home/liang/miniconda3/envs/mjrl-env/lib/python3.7/site-packages/gymnasium/envs/registration.py", line 381, in _check_name_exists
    f"Environment `{name}` doesn't exist{namespace_msg}.{suggestion_msg}"
gymnasium.error.NameNotFound: Environment `door` doesn't exist.
```
In addition, I would like to mention that in the `tianshou=0.5.0` version, `irl_gail.py` does not seem to work, because in line 103,the code below would got a error `Error:SubprocVectorEnv has no attribute norm_obs`.
 ```
train_envs = SubprocVectorEnv(
        [lambda: NoRewardEnv(gym.make(args.task)) for _ in range(args.training_num)],
        norm_obs=True
    )
```
So,now the version of tianshou i used is the 0.4.7, but i also test the scripts in the newest version 0.5.0

**Comment by lzl60109** [comment]
hello,is it any solution of the render problem?

**Comment by Trinkle23897** [comment]
Hey, sorry for the delay!

For norm_obs issue: please refer to 
[examples/offline/d4rl_td3_bc.py](https://github.com/thu-ml/tianshou/blob/600f4bbd555a1995ad5e2dc9ce74304de0941fcb/examples/offline/d4rl_td3_bc.py#L90) -- You should use  `VectorEnvNormObs` venv wrapper now. Sorry for the breakage here!

@MischaPanch I think we should also add type check for all test/example scripts to avoid such thing happen in the future

**Comment by MischaPanch** [comment]
Right, I'll adjust it directly in the newest PR so that examples are also covered by type-checks
