### ISSUE TITLE
module 'tianshou.trainer' has no attribute 'offpolicy_trainer'

### ISSUE THREAD

**Issue by LeiLei-Ya** [aai-institute/tianshou#930]
Why is it that when I follow the Quick start steps, when I run to the trainer step:
"result = ts.trainer.offpolicy_trainer(
    policy, train_collector, test_collector, epoch, step_per_epoch, step_per_collect.
    test_num, batch_size, update_per_step=1 / step_per_collect,
    train_fn=lambda epoch, env_step: policy.set_eps(eps_train),
    test_fn=lambda epoch, env_step: policy.set_eps(eps_test),
    stop_fn=lambda mean_rewards: mean_rewards >= env.spec.reward_threshold,
    logger=logger)
print(f'Finished training! Use {result["duration"]}')"

The following error occurs?
**module 'tianshou.trainer' has no attribute 'offpolicy_trainer'**

I print the version returned 1.0.0

**Comment by Trinkle23897** [comment]
oops sorry could you try `OnpolicyTrainer(...).run()` instead of `onpolicy_trainer(...)`?

**Comment by MischaPanch** [comment]
That one's on me, master is currently undergoing several changes and there might updates missing in the docs, sry for that

**Comment by LeiLei-Ya** [comment]
Thank you very sincerely for your reply, when i replace **onpolicy_trainer** with **OnpolicyTrainer(...) .run()** the code throws another error：“ __init__() got multiple values for argument 'max_epoch' ”

**Comment by LeiLei-Ya** [comment]
Thank you very sincerely for your reply, when i replace **onpolicy_trainer** with **OnpolicyTrainer(...) .run()** the code throws another error：“ __init__() got multiple values for argument 'max_epoch' ”

**Comment by MischaPanch** [comment]
Right, you can't use the args directly, because the order changed (the signature was previously inconsistent with the BaseTrainer init). Pls use it like in one of the scripts under `examples/offline`, e.g.

```python

    result = OfflineTrainer(
        policy=policy,
        buffer=buffer,
        test_collector=test_collector,
        max_epoch=args.epoch,
        step_per_epoch=args.update_per_epoch,
        episode_per_test=args.test_num,
        batch_size=args.batch_size,
        stop_fn=stop_fn,
        save_best_fn=save_best_fn,
        logger=logger,
    ).run()
```

Essentially it means, to fix the example, replace all your args by kwargs and respect the signature of OfflineTrainer (same as BaseTrainer)


@Trinkle23897 It probably makes sense to move the tutorial notebooks to the repo instead of keeping them in drive, right? See also #916

**Comment by Trinkle23897** [comment]
> It probably makes sense to move the tutorial notebooks to the repo instead of keeping them in drive, right?

SGTM!
