### ISSUE TITLE
question about modify the metwork

### ISSUE THREAD

**Issue by huang6668** [aai-institute/tianshou#931]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
I tried to replace the preprocess_net of the Actor and Critic networks in the DIscreteSAC algorithm with a convolutional neural network instead of an MLP, but I failed. Is there an example to guide me to continue?

**Comment by MischaPanch** [comment]
You could have a look at the atari examples, there the nets are built with convolutional layers

**Comment by huang6668** [comment]
Thanks for your answer.
