### ISSUE TITLE
Create high level interfaces for config and experiments

### ISSUE THREAD

**Issue by MischaPanch** [aai-institute/tianshou#938]
Users should be able to quickly create a trainable policy without having to go through details of instantiating trainers, collectors, and so on. Once an env factory is written, starting the training should be easy. Loading the env and policy from a checkpoint should also be simple. Some inspiration can be taken from the way rllib or SB3 do this - we should just take the best parts/ideas from there though (if any).

This issue has probably one of the highest impact/effort ratios among the existing ones, as it will extend the target audience of tianshou. At least the following points should be fulfilled:
 

- [x] Config can be easily read and saved
- [x] Config can easily be manipulated from the command line
- [x] Config is saved with each experiment and agent **and env** are recreated from it at loading. Note that the recreation of custom envs from config is crucial. This means that custom env factories should be registered or at least passed at loading time.

The implementation will require at least

- [ ] Factoring out a bunch of utils from the example scripts
- [x] Removing the whole args stuff. In my current implementation (not in this repo), config, defaults and explanations are read off from the dataclasses using jsonargparse
- [x] Changing at least some of the example scripts to use the new structure. In fact, I believe that after this there might remain just a few script that are started using different yaml files.
- [x] Write at least some small documentation

A tangential, but I believe very important and useful feature would be: **compatibility with SB3 and rllib**.

What I mean by that is the following: the config determines the training entirely. SB3 and rllib also have high level interfaces, with their own way to configure stuff, their own names and ways to start the training. This complicates comparisons in benchmarking, and also makes users' lives more difficult, in case they want to switch from one lib to another. Note that many "industry" users will never want to go beyond the high level interfaces.

Just by mapping names to each other we could easily implement methods like `to_sb3_config` or `to_rllib_config` and even simple functions like `train_with_rllib(config)` and `train_with_sb3(config)`, in addition to the standard `train`. This will make reliable performance comparisons very simple, and is thus related to #935. For algorithms or options not implemented in other frameworks, one raises a `NotImplementedError`, but at least for the standard algorithms the overlap of what is implemented in all libraries is substantial.

@opcode81 Do you want to take a look at it? I will give you access to our fork and internal repositories where I have implemented parts of this with jsonarparse. I also included nni support for these configs, which should also make user's life easy.

**NOTE:**
We don't have to fully nail it at the beginning, and it also doesn't need to be exhaustive. Would be nice to cover the most commonly used algos in the beginning, say SAC, PPO and TD3.

Once released, there should be as few breaking changes to the high level interfaces as possible, so the new features should spend quite some time in alpha/beta stage before being fully publicized. Having just something for now would already be a great improvement. One can address this issue in multiple PRs building on each other. For example, the compatibility layer with sb3/rllib should be a separate PR.

**Comment by MischaPanch** [comment]
@Trinkle23897 I think this is the one my colleagues and I will address next. I tried to write a comprehensible description above, feel free to share your thoughts!

**Comment by spacegoing** [comment]
@MischaPanch @Trinkle23897 My concern is will this add engineering complexity for tianshou?

I think there is a trade-off between easy for using v.s. flexibility for development. I don't know tianshou's main use case is for research or application.

As an RL researcher, one of the main reason I'm using tianshou is because tianshou's significantly smaller codebase and fewer levels of encapsulation than other frameworks (especially Rllib).

If I'm seeking usability or production-grade codebase, I'll go for RLlib. But as a researcher, my main requirement is a concise code base to get quick and dirty work done. The current version of Tianshou positioned it really well targeting this part of users. Too many levels of encapsulations really hurt research purpose-based users.

BTW just curious, is Jiayi still maintaining this repo or handing it over? I'm happy to help :D

**Comment by MischaPanch** [comment]
Hi @spacegoing, thank you for voicing your concern!

To make it clear from the beginning: by no means I want to turn tianshou into another Rllib.

I believe that it's a common misconception that high-level interfaces and good, modular low-level interfaces are necessarily conflicting technical goals. I definitely don't want to make tianshou less friendly for researchers and a small, simple core code is an important requirement for this friendliness. 

This issue is a good example for the compatibility of the two goals - it's a pure addition of convenience layers that don't affect the existing code, and thus don't make researcher's lives harder. They will be in their own modules, serving their own purpose. Examples on how to assemble building blocks into algorithms will still remain. The existence of lightning did not make pytorch less accessible to researchers, same for keras and tensorflow (I would actually argue the contrary).

But I do get where your concern is coming from: in reality, projects that focus on simplicity of high-level usability tend to neglect the importance of modular and non-complex lower level interfaces. This is why almost no researchers use rllib, and comparatively few use SB3. It's more of a phychological than a technical issue. For tianshou, I believe that a low entry barrier for researchers will always be a priority - but it doesn't inhibit to build a low entry barrier for less experienced users as well.

**Comment by MischaPanch** [comment]
As for the other question: I am merely a maintainer, @Trinkle23897 remains the owner and can kick me out at any time if I misbehave ^^.

If you want to help, I think that improving the core of tianshou is necessary before adding more features or fixing complicated issues like the RNN related one.

Some low-hanging fruits that I haven't started yet are for example #933 or #917. Also #898 #922 and #893 require attention. Wanna take on one of these?

**Comment by MischaPanch** [comment]
Btw, me and almost everyone I talked to got burned when using rllib. I personally don't want to touch it again, at least for a very long time, even in industry projects where all I want is a trainer

**Comment by spacegoing** [comment]
@MischaPanch LoL I can't agree more. For some reason, I have to use Rllib and it's a pain in my ass everyday, for more than a year.

> Btw, me and almost everyone I talked to got burned when using rllib. I personally don't want to touch it again, at least for a very long time, even in industry projects where all I want is a trainer

Using Tianshou feels like breeze for me and that's why I kind of terrified when first see this issue.

Many thanks for your explanation. It makes much more sense to me now.

Just FYI, the way I use tianshou is simply writing a customized ConfigDict https://github.com/spacegoing/ray_ppo_trainable/blob/e79c4df48490e526ee4ac7b459a8c8f2b59bd3dc/utils_ray.py#L6 and then write configs/ hyperparams in a yaml file: https://github.com/spacegoing/ray_ppo_trainable/blob/main/ts_ppo_config.yaml.

This is also how I implemented a ray.tune.Trainable version of tianshou.

PS: I'm happy to take the RNN-related issues. I "kind of feel like solved" that issue for PPO. I'll take a closer look to https://github.com/thu-ml/tianshou/issues/937. Many thanks for your time and patience. Have a nice day:D

**Comment by MischaPanch** [comment]
Thanks to you too! Sure, if you already advanced on the RNN issues, makes sense if you address them first.

Note that performance tests will be paramount for solving this, and we don't have any in CI right now

**Comment by opcode81** [comment]
I started working on this two days ago.
For the eager, you may have a look at the work in progress [here](https://github.com/aai-institute/tianshou/tree/feat/high-level-api). I'll post an update (and perhaps open a PR) once we have a sufficiently good basis for discussion.

**Comment by MischaPanch** [comment]
Reopening this until documentation is fully written and integrated, and the compatibility with SB3/Rllib is established

**Comment by MischaPanch** [comment]
@carlocagnetta is currently working on #916 , and generally on improved documentation. When he's done, we should add tutorial notebooks on the high-level usage of tianshou

**Comment by opcode81** [comment]
I propose that we make the abstraction layer that adds support for other frameworks a separate issue. It can be developed separately from the high-level API as such.

**Comment by MischaPanch** [comment]
> I propose that we make the abstraction layer that adds support for other frameworks a separate issue. It can be developed separately from the high-level API as such.

Yes, I'll move this to a subissue of the benchmarking/comparison story.

However, before we close this issue, documentation on highlevel interfaces should be added. After the overhaul of the docs was merged today, it is possible to address it. The docs extension should happen at least in

- [x] Readme (mention the example scripts and the new industry-usage-compatibility of tianshou)
- [ ] Landing page in docs (mention new interfaces, also link to examples)
- [ ] Tutorials on IDE usage with configuration (Add your gif and explanations from wiki to a tutorial file)
- [ ] Optionally, add a tutorial notebook on the new interfaces. Similar to an example script in scope, but with more explanations

We can split the tasks between us if you want, @opcode81. Once it's added to the docs, the issue can be closed.

@Trinkle23897 I think when this and #996 is finished, I'd like to make a 0.6 release. We are not at 1.0.0 yet (need at least benchmarking, HPO, regression tests), but the recent extensions should be useful to have in an intermediate release, I think.

**Comment by Trinkle23897** [comment]
sgtm, lmk if you need extra permissions to release

**Comment by MischaPanch** [comment]
Closing this, separate issues on documentation will follow
