### ISSUE TITLE
Regarding the question of how test_reward is calculated in TensorBoard,

### ISSUE THREAD

**Issue by huang6668** [aai-institute/tianshou#940]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
May I ask how the test_reward is calculated? I'm not sure if test_reward is the average or the sum of rewards across each test_env. In my custom environment, the maximum reward is set to 50, but the test_reward can reach over 100. I have saved the rewards for each environment during training, and they all match my settings. However, the test_reward is much higher than what I have set. I'm not sure what's going wrong. Could you please help me understand and resolve this issue?

**Comment by MischaPanch** [comment]
I think test reward commonly refers to the whole-episode reward. For example, in HalfCheetah, the max reward is something like 4800, but test reward can reach up to 16000 with good trainings.

So there is a difference between max reward per step and max reward per episode.

Feel free to close this issue if the answer resolves your question

**Comment by huang6668** [comment]
Can I understand the test_reward as the result of the reward of each step in an episode?If I use episode_per_collect instead of step_per_collect, is test_reward then the total reward for each episode in each environment, rather than the sum of rewards for each step?

**Comment by MischaPanch** [comment]
test_reward should be the sum of rewards over an episode (i.e. over steps). The number of test environments plays no role for it's value, more test-envs just give more datapoints

**Comment by Trinkle23897** [comment]
test_reward is from test_collector, where it collects `n_episodes` full episode and calculate the average episodic reward across those sampled trajectory

**Comment by huang6668** [comment]
I now fully understand. Thank you very much for your help and patient explanation.
