### ISSUE TITLE
Fix documentation build

### ISSUE THREAD

**Issue by BFAnas** [aai-institute/tianshou#941]
- [X] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [X] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [X] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [X] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [X] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  1.0.0 0.29.0 2.0.1+cu117 1.24.4 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0] linux
  ```
@MischaPanch Request to update the Contrib documentation as now poetry is being used as the main development tool.

**Comment by MischaPanch** [comment]
The contrib docs are already updated on master but apparently not released yet. The release seem to have happened manually so far. 

@Trinkle23897 could you release the new docs? Should we automate this process in the future?

**Comment by Trinkle23897** [comment]
the current doc build is failing on master: https://readthedocs.org/projects/tianshou/builds/
It's triggered by every master commit, no need to build/release manually

**Comment by MischaPanch** [comment]
Ah, it's done in readthedocs, I missed that. I don't think I have the permissions to fix this. 

@Trinkle23897 we could move the documentation to github pages, I have a GH action ready for that. What do you think? Should give a better control over the docs build.

**Comment by Trinkle23897** [comment]
I'd prefer the original link since many existing references explicitly rely on that link prefix. I'll fix it later
