### ISSUE TITLE
Make tests and examples pass  mypy

### ISSUE THREAD

**Issue by MischaPanch** [aai-institute/tianshou#952]

**Comment by dantp-ai** [comment]
I can pick this up as a first issue. This is to be run on the newest version of main branch, right?

**Comment by MischaPanch** [comment]
Yes, that would be amazing, thanks! But don't underestimate it, it's probably gonna be quite a lot of rather painful work.

Let me know if you need help, I can also recommend another issue, if you want.

**Comment by dantp-ai** [comment]
Yep, a bit of clarification would be nice as the general objective is not clear to me. 

I see that there is a poe task called `type-check` that runs `mypy tianshou`, but I guess there is more to this issue than running that and solving the potential issues. Btw, I did ran that task and no issues were found.

**Comment by dantp-ai** [comment]
Oh I see, there are a bunch of issues popping up when running `mypy test` and `mypy examples`. These are the issues to be resolved.

**Comment by dantp-ai** [comment]
I will begin with the `test` module since it has the most issues.

**Comment by MischaPanch** [comment]
Hey @dantp-ai, how is it going with this issue? Do you need any help on your PR?

**Comment by dantp-ai** [comment]
I opened this _draft_ PR: https://github.com/thu-ml/tianshou/pull/1017

I'll keep you posted. So far, I'm knocking off the issues from the test dir.

**Comment by MischaPanch** [comment]
Great, let me know if you have questions or need help with something. And thanks again for taking this one, it will go a long step towards better tests and examples!

**Comment by dantp-ai** [comment]
Interesting to me at least, is that the `cpu-extra (macOS/Windows-latest, 3.11)` workflow runs the reduced tests with `poetry run poe test-reduced` and the `cpu (Ubuntu, 3.11)` worfklow runs the complete tests with `poetry run poe test`. 

Is this workflow setup intended like that?

**Comment by MischaPanch** [comment]
Yes, to reduce the resources required for CI. The idea is that most tests will run through on every OS. So to make sure that tianshou works on all OSs, it's enough to run a full test suite on the "most important one" (Ubuntu) and to run a reduced test suite on the other ones 

In addition, some things only work on Ubuntu - like envpool and installing Ray with poetry.

We should probably document this explicitly. Does the scheme make sense to you?

**Comment by MischaPanch** [comment]
We could also give up on that, just use more resources, and ignore some specific, OS dependent tests. I'd consider this after a general restructuring of tests, I'm not a big fan of the current structure of the integration tests

**Comment by dantp-ai** [comment]
@MischaPanch I am a bit busy this week, but I am making steady progress on the remaining issues. I will open the PR as soon as they are fixed. If I run into urgent blockers, I will open a draft PR to discuss them with you.

**Comment by MischaPanch** [comment]
Great, @dantp-ai, thank you!

Mypy support for notebooks was merged a few days ago, so after this issue is finished, we have a form of automatic QA for all code in tianshou. Looking forward to the next PR :)

**Comment by dantp-ai** [comment]
WIP:

Listing the files with most of the issues here to have a sense of reference for the progress being made.

- [x] test/base/test_returns.py
- [x] test/base/test_buffer.py
- [x] test/base/test_batch.py
- [x] test/base/test_collector.py
- [x] test/base/test_env.py
- [x] test/base/test_policy.py
- [x] test/base/test_env_finite.py

---
~114~ ~99~ ~59~ ~11~ 0 issues left in `test`.
~138~ ~98~ ~80~ ~42~ ~32~ 9 issues left in `examples`.

The end is in sight.

**Comment by dantp-ai** [comment]
I noticed that ellipses and integers or slices and integers are commonly used when testing batches and buffers. Currently, the `IndexType` is defined as `slice | int | np.ndarray | list[int]`.

Should we also support something like:

```
from types import EllipsisType

IndexType = slice | int | np.ndarray | list[int] | tuple[EllipsisType, int] | tuple[slice, int] | tuple[list[slice], int]
```

The above is just an example. The implementation is more complex because we need to place one ellipsis or any number of slices anywhere: `a[..., 0], a[1, ...], a[:, :, 2], a[2, :, 0]` should all be valid.

**Comment by MischaPanch** [comment]
One really needs to go through rather ugly gymnastics for this... I feel like the IndexType is becoming overly complex, is possible to factor out things? Like for example

```python
_SingleIdxType = slice | int | EllipsisType | ...
IndexType =  _SingleIdxType | Sequence[_SingleIdxType] | np.ndarray
```

I also feel like `Sequence` should cover the majority of things, even though in some situations `tuple` might actually behave differently from `list`, if I remember numpy correctly. However, maintaining all possible sequence types here might be too hard/annoying
