### ISSUE TITLE
Bug in MultiAgentPolicyManager - and Fix

### ISSUE THREAD

**Issue by FahmidMorshed** [aai-institute/tianshou#967]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

I tried running MARL with multiple SAC as internal policies for each agent for one of my custom-made petting zoo environments. After rigorous debugging, I realized that the MultiAgentPolicyManager in version 0.5.1 needs a train(self, mode: bool = True) method that iteratively sets all the internal policies to _mode_. Otherwise, the internal policies are never called in eval mode. I am not sure if this is also true when used with other types of internal policies. 

The following function solves the issue if added to _tianshou/policy/multiagent/mapolicy.py_ :
```python
def train(self, mode: bool = True):
      """Sets each internal policy in training mode."""
      for agent_id, policy in self.policies.items():
          policy.train(mode)
      return self
```
I can do a pull-request to the main branch, if needed.

**Comment by Trinkle23897** [comment]
Oops sorry, and yeah good catch! Feel free to submit a PR.

**Comment by FahmidMorshed** [comment]
Added a RP to fix the issue. Ty.
